### ISSUE TITLE
Nothing happens on windows 10

### ISSUE THREAD

**Issue by dorukguner** [malwaredllc/byob#106]
Hi I'm trying to run byob on windows 10, however when I run the dropper nothing happens.

I have accessed http://127.0.0.1:13338 (where the payloads are hosted) and can see the server's working fine. I'm using python 2.7.15

Here's a screenshot:
![image](https://user-images.githubusercontent.com/38545816/55723764-30d8b180-5a4d-11e9-85e8-4db5da98da0b.png)

Cheers

**Comment by malwaredllc** [comment]
Try using the server's external IP instead of the local host.

**Comment by dorukguner** [comment]
> Try using the server's external IP instead of the local host.

The same thing happens.

**Comment by malwaredllc** [comment]
Can you please run both the server and client (`a.py` in your example) with the  `--debug` argument and provide the debugging output here?

**Comment by dorukguner** [comment]
After running with --debug flag I've found that the client thinks that I am running a virtual machine, however this is not the case. 

After answering no to the virtual machine abort prompt the client starts up however is unable to find any of the modules it tries to import and so am unable to run any of the commands after shelling into the client from the server.

![image](https://user-images.githubusercontent.com/38545816/55774623-3ed41400-5ad9-11e9-9eb2-7f5db986f81d.png)

**Comment by ninjaspl0it** [comment]
Works fine on my system running W10, as long as you choose no to quit when VM detected. Would be nice if this could be a feature to add when compiling

**Comment by malwaredllc** [comment]
@dorukguner  @ninjaspl0it I disabled the "auto-abort if VM is detected" feature because it has caused a lot of confusion. 
Also, a lot of bug fixes have been pushed recently, so I'd recommend doing a fresh install and trying again.
