### ISSUE TITLE
Client.py returning TypeError

### ISSUE THREAD

**Issue by Bosskee** [malwaredllc/byob#109]
Hello, I'm trying to compile an Exe in it's most basic form, this is my query:
`python client.py 1.2.3.4.5.6 1337 --freeze`

BYOB successfully launches but it returns this at the end:

```
b'52 INFO: PyInstaller: 3.4'
Traceback (most recent call last):
  File "client.py", line 434, in <module>
    main()
  File "client.py", line 192, in main
    dropper = _dropper(options, var=var, key=key, modu
  File "client.py", line 416, in _dropper
    name = generators.freeze(name, icon=options.icon,
  File "C:\Users\Name\Desktop\byob-master\byob\core\ge
    if 'EXE' in line and 'complete' in line: break
TypeError: a bytes-like object is required, not 'str'
```

**Comment by malwaredllc** [comment]
I believe this is a Python 3 error - we are still working on Python 3 compatibility. If you use Python 2 it should work.

**Comment by Bosskee** [comment]
> I believe this is a Python 3 error - we are still working on Python 3 compatibility. If you use Python 2 it should work.

Ahh I see!

I tried running it with Python 2 but it threw me this error instead(BYOB unrelated):
```
Traceback (most recent call last):
  File "client.py", line 98, in <module>
    import colorama
ImportError: No module named colorama
```

Don't get why colorama is recognized by Python 3 but not by Python 2..

**Comment by Bosskee** [comment]
Tried running the setup.py with Python2 but it threw this:
```
C:\Users\Name\Desktop\byob-master\byob>python2 setup.py
'where' is not recognized as an internal or external command,
operable program or batch file.
DEBUG:__main__:Error in pip package installer: Command 'where pip' returned non-zero exit status 1
Installing requirements.txt
```
Setup works with Python3

**Comment by Bosskee** [comment]
> I believe this is a Python 3 error - we are still working on Python 3 compatibility. If you use Python 2 it should work.

Which version of Python 2 do you recommend?

**Comment by malwaredllc** [comment]
Any version should work, I personally have 2.7.15
