### ISSUE TITLE
Client.py ValueError

### ISSUE THREAD

**Issue by Pvnic** [malwaredllc/byob#114]
Hi ! I still got an issues that pop just after running client.py

« C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob>py client.py 127.0.0.1 80 --freeze

88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'

[>] Modules
        Adding modules...  (3 modules added to client)

[>] Imports
        Adding imports...- (25 imports from 3 modules)

[>] Payload
        Uploading payload... -(hosting payload at: http://127.0.0.1:81///payloads/n8A.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://127.0.0.1:81///stagers/n8A.py)

[>] Dropper
        Writing dropper...  (334 bytes written to byob_n8A.py)
        Compiling executable...
289 INFO: PyInstaller: 3.3.1
289 INFO: Python: 2.7.15
292 INFO: Platform: Windows-10-10.0.17134
295 INFO: wrote C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob\Thomas.spec
298 INFO: UPX is not available.
Traceback (most recent call last):
 File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 101, in <module>
    run()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 162, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob\Michel\Desktop\byob-master' not found »

**Comment by FraggleR0ck** [comment]
You have the environment variables set correctly? I'm not having this issue.

**Comment by malwaredllc** [comment]
Looks like PyInstaller is searching for the script in a directory that doesn't exist (`ValueError: script **'C:\Users\Thomas Michel\Desktop\byob-master (1)\byob-master\byob\Michel\Desktop\byob-master'** not found`). I'm not sure why it's doing this, but the fact that it's appending the parts of the file path following the space in your username (`Michel\Desktop\byob-master`) may indicate the space in the file path is causing issues. Try moving `byob-master` (not `byob-master (1)`) to your root directory and generating the client from there, and let me know if that works.
