### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by didi110296** [malwaredllc/byob#115]
Hello, I encounter a problem, I compiled under Windows 10 an .exe, when running it I receive a windows warning message:

Title: Fatal error detected
Message: Failed to execute script test (test is the name of my .exe)

This is my warn-test.txt file
`missing module named 'win32com.gen_py' - imported by win32com (conditional, optional), C:\Python27\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py (top-level)
missing module named pyimod03_importers - imported by C:\Python27\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py (top-level)
missing module named 'multiprocessing.popen_fork' - imported by C:\Python27\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py (conditional, optional)
missing module named 'multiprocessing.popen_spawn_win32' - imported by C:\Python27\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py (conditional, optional)
missing module named 'multiprocessing.spawn' - imported by C:\Python27\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py (conditional)
missing module named resource - imported by posix (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named posix - imported by os (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named rourl2path - imported by urllib (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _datetime - imported by future.backports.datetime (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _pybsddb - imported by bsddb (conditional, optional), bsddb.db (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named bsddb3 - imported by bsddb (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named macresource - imported by MacOS (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named MacOS - imported by platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'setuptools._vendor.six.moves' - imported by 'setuptools._vendor.six.moves' (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _curses - imported by curses (top-level), curses.has_key (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.eye - imported by numpy (delayed), numpy.core.numeric (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.histogramdd - imported by numpy (delayed), numpy.lib.twodim_base (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.ndarray - imported by numpy (top-level), numpy.ma.core (top-level), numpy.ma.extras (top-level), numpy.ma.mrecords (top-level), numpy.ctypeslib (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.amax - imported by numpy (top-level), numpy.ma.core (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.amin - imported by numpy (top-level), numpy.ma.core (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.iscomplexobj - imported by numpy (top-level), numpy.ma.core (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.bool_ - imported by numpy (top-level), numpy.ma.core (top-level), numpy.ma.mrecords (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.array - imported by numpy (top-level), numpy.ma.core (top-level), numpy.ma.extras (top-level), numpy.ma.mrecords (top-level), numpy.ctypeslib (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.expand_dims - imported by numpy (top-level), numpy.ma.core (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.dtype - imported by numpy (top-level), numpy.ma.mrecords (top-level), numpy.ctypeslib (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.recarray - imported by numpy (top-level), numpy.ma.mrecords (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named lzma - imported by numpy.lib._datasource (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'urllib.error' - imported by numpy.lib._datasource (delayed, conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.single - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.double - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.csingle - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.cdouble - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.inexact - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.complexfloating - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.add - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.geterrobj - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.intp - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.object_ - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.divide - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.conjugate - imported by numpy.core (top-level), numpy.fft.fftpack (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.sqrt - imported by numpy.core (top-level), numpy.linalg.linalg (top-level), numpy.fft.fftpack (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.integer - imported by numpy.core (top-level), numpy.fft.helper (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named pathlib - imported by numpy.compat.py3k (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.lib.i0 - imported by numpy.lib (top-level), numpy.dual (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named builtins.bool - imported by builtins (conditional), numpy.core.numerictypes (conditional), numpy.lib._iotools (conditional), numpy (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named builtins.float - imported by builtins (conditional), numpy.core.numerictypes (conditional), numpy.lib._iotools (conditional), numpy (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named builtins.complex - imported by builtins (conditional), numpy.core.numerictypes (conditional), numpy.lib._iotools (conditional), numpy (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.float32 - imported by numpy.core (top-level), numpy.testing._private.utils (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.float64 - imported by numpy.core (delayed), numpy.testing._private.utils (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.signbit - imported by numpy.core (delayed), numpy.testing._private.utils (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy.core.number - imported by numpy.core (delayed), numpy.testing._private.utils (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named pickle5 - imported by numpy.core.numeric (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named nose - imported by numpy.testing._private.utils (delayed, optional), numpy.testing._private.decorators (delayed), numpy.testing._private.noseclasses (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'nose.util' - imported by numpy.testing._private.noseclasses (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named scipy - imported by numpy.testing._private.nosetester (delayed, conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'nose.plugins' - imported by numpy.testing._private.noseclasses (top-level), numpy.testing._private.nosetester (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named pytest - imported by numpy._pytesttester (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _xmlrpclib - imported by xmlrpclib (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named configparser - imported by numpy.distutils.system_info (conditional), numpy.distutils.npy_pkg_config (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named Numeric - imported by numpy.distutils.system_info (delayed, conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numarray - imported by numpy.distutils.system_info (delayed, conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named __svn_version__ - imported by numpy.f2py.__version__ (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named numpy_distutils - imported by numpy.f2py.diagnose (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'numpy_distutils.command' - imported by numpy.f2py.diagnose (delayed, conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'numpy_distutils.fcompiler' - imported by numpy.f2py.diagnose (delayed, conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'numpy_distutils.cpuinfo' - imported by numpy.f2py.diagnose (delayed, conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named setuptools.extern.six - imported by setuptools.extern (top-level), setuptools.monkey (top-level), setuptools.dist (top-level), setuptools.extern.six.moves (top-level), setuptools.py33compat (top-level), setuptools.config (top-level), setuptools.command.easy_install (top-level), setuptools.sandbox (top-level), setuptools.py27compat (top-level), setuptools.package_index (top-level), setuptools.wheel (top-level), setuptools.pep425tags (top-level), setuptools.command.egg_info (top-level), setuptools.command.sdist (top-level), setuptools.command.bdist_egg (top-level), setuptools.unicode_utils (top-level), setuptools.command.develop (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
runtime module named setuptools.extern.six.moves - imported by setuptools.dist (top-level), setuptools.py33compat (top-level), ConfigParser (top-level), setuptools.command.easy_install (top-level), setuptools.sandbox (top-level), setuptools.command.setopt (top-level), setuptools.package_index (top-level), setuptools.ssl_support (top-level), setuptools.command.egg_info (top-level), setuptools.command.py36compat (top-level), setuptools.namespaces (top-level), C:\Users\didi1\byob\byob\test.py (top-level), setuptools.msvc (top-level), 'setuptools._vendor.six.moves' (top-level)
missing module named setuptools.extern.six.moves.map - imported by setuptools.extern.six.moves (top-level), setuptools.dist (top-level), setuptools.command.easy_install (top-level), setuptools.sandbox (top-level), setuptools.package_index (top-level), setuptools.ssl_support (top-level), setuptools.command.egg_info (top-level), setuptools.namespaces (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'setuptools.extern.pyparsing' - imported by setuptools._vendor.packaging.markers (top-level), setuptools._vendor.packaging.requirements (top-level)
missing module named ordereddict - imported by pkg_resources._vendor.pyparsing (optional), setuptools._vendor.pyparsing (optional)
missing module named _thread.RLock - imported by _thread (optional), pkg_resources._vendor.pyparsing (optional), setuptools._vendor.pyparsing (optional)
excluded module named site - imported by distutils.command.install (top-level), setuptools.command.easy_install (top-level), distutils.command.build_ext (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named backports - imported by setuptools.ssl_support (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named wincertstore - imported by setuptools.ssl_support (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'setuptools.extern.packaging.utils' - imported by setuptools.wheel (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _manylinux - imported by setuptools.pep425tags (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named setuptools.extern.six.moves.filter - imported by setuptools.extern.six.moves (top-level), setuptools.dist (top-level), setuptools.ssl_support (top-level), setuptools.command.py36compat (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named setuptools.extern.six.moves.filterfalse - imported by setuptools.extern.six.moves (top-level), setuptools.dist (top-level), C:\Users\didi1\byob\byob\test.py (top-level), setuptools.msvc (top-level)
missing module named termios - imported by getpass (optional), tty (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named EasyDialogs - imported by getpass (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _scproxy - imported by urllib (conditional), future.backports.urllib.request (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _thread.get_ident - imported by _thread (conditional, optional), future.backports.misc (conditional, optional), numpy.core.arrayprint (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named reprlib.recursive_repr - imported by reprlib (conditional), future.backports.misc (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'test.support' - imported by future.moves.test.support (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'test.test_support' - imported by future.moves.test.support (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named dbm - imported by future.standard_library (delayed, optional), future.moves.dbm (conditional), whichdb (optional), anydbm (top-level), future.moves.dbm.ndbm (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'dbm.dumb' - imported by future.moves.dbm.dumb (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'dbm.gnu' - imported by future.moves.dbm.gnu (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named gdbm - imported by anydbm (top-level), future.moves.dbm.gnu (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'dbm.ndbm' - imported by future.moves.dbm.ndbm (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'setuptools.extern.packaging.version' - imported by setuptools.config (top-level), C:\Users\didi1\byob\byob\test.py (top-level), setuptools.msvc (top-level)
missing module named 'setuptools.extern.six' - imported by setuptools (top-level), setuptools.extension (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _imp - imported by pkg_resources (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named pkg_resources.extern.six - imported by pkg_resources.extern (top-level), pkg_resources (top-level), pkg_resources.py31compat (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'pkg_resources.extern.six.moves' - imported by pkg_resources (top-level), C:\Users\didi1\byob\byob\test.py (top-level), pkg_resources._vendor.packaging.requirements (top-level)
missing module named 'importlib.machinery' - imported by numpy.compat.py3k (delayed, conditional), pkg_resources (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named pkg_resources.extern.appdirs - imported by pkg_resources.extern (top-level), pkg_resources (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named pkg_resources.extern.packaging - imported by pkg_resources.extern (top-level), pkg_resources (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _sysconfigdata - imported by distutils.sysconfig (delayed), sysconfig (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.requirements (top-level), pkg_resources._vendor.packaging.markers (top-level)
missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs (delayed, conditional, optional)
missing module named com - imported by pkg_resources._vendor.appdirs (delayed)
missing module named setuptools.extern.packaging - imported by setuptools.extern (top-level), setuptools.dist (top-level), setuptools.command.egg_info (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named gestalt - imported by platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named Carbon - imported by plistlib (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'Carbon.Files' - imported by plistlib (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'Carbon.File' - imported by plistlib (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _xmlplus - imported by xml (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named java - imported by platform (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'java.lang' - imported by platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level), xml.sax._exceptions (conditional)
missing module named vms_lib - imported by platform (delayed, conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'urllib3.packages.six.moves.urllib' - imported by 'urllib3.packages.six.moves.urllib' (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named OpenSSL - imported by urllib3.contrib.pyopenssl (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'cryptography.hazmat' - imported by urllib3.contrib.pyopenssl (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'cryptography.x509' - imported by urllib3.contrib.pyopenssl (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'OpenSSL.crypto' - imported by urllib3.contrib.pyopenssl (delayed), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named cryptography - imported by urllib3.contrib.pyopenssl (top-level), requests (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named grp - imported by shutil (optional), tarfile (optional), distutils.archive_util (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named winreg.OpenKeyEx - imported by winreg (delayed, optional), platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named winreg.QueryValueEx - imported by winreg (delayed, optional), platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named winreg.CloseKey - imported by winreg (delayed, optional), platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named winreg.HKEY_LOCAL_MACHINE - imported by winreg (delayed, optional), platform (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named socks - imported by urllib3.contrib.socks (optional), C:\Users\didi1\byob\byob\test.py (top-level)
runtime module named urllib3.packages.six.moves - imported by httplib (top-level), urllib3.connectionpool (top-level), urllib3.util.response (top-level), 'urllib3.packages.six.moves.urllib' (top-level), urllib3.response (top-level), urllib3.util.queue (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named "'urllib3.packages.six.moves.urllib'.parse" - imported by urllib3.request (top-level), urllib3.poolmanager (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named brotli - imported by urllib3.util.request (optional), urllib3.response (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'backports.ssl_match_hostname' - imported by setuptools.ssl_support (optional), urllib3.packages.ssl_match_hostname (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named ipaddress - imported by urllib3.packages.ssl_match_hostname._implementation (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named simplejson - imported by requests.compat (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named SOCKS - imported by ftplib (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _dummy_threading - imported by dummy_threading (top-level), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'urllib.parse' - imported by numpy.lib._datasource (delayed, conditional), urllib3.packages.rfc3986.compat (optional), requests.compat (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'urllib.request' - imported by numpy.lib._datasource (delayed, conditional), requests.compat (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'collections.abc' - imported by numpy.core.numeric (optional), numpy.lib.function_base (optional), numpy.lib.npyio (conditional), numpy.testing._private.decorators (optional), urllib3._collections (optional), requests.compat (conditional), C:\Users\didi1\byob\byob\test.py (top-level), pkg_resources._vendor.pyparsing (optional), setuptools._vendor.pyparsing (optional)
missing module named os2 - imported by os (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named _emx_link - imported by os (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named ce - imported by os (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named riscos - imported by os (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named riscospath - imported by os (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named riscosenviron - imported by os (conditional, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named org - imported by pickle (optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named 'org.python' - imported by copy (optional), setuptools.sandbox (conditional), C:\Users\didi1\byob\byob\test.py (top-level), xml.sax (delayed, conditional)
missing module named pwd - imported by posixpath (delayed, conditional), getpass (delayed), distutils.util (delayed, conditional, optional), shutil (optional), tarfile (optional), distutils.archive_util (optional), webbrowser (delayed), netrc (conditional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named readline - imported by cmd (delayed, conditional, optional), pdb (delayed, optional), C:\Users\didi1\byob\byob\test.py (top-level)
missing module named fcntl - imported by tempfile (optional), subprocess (conditional), C:\Users\didi1\byob\byob\test.py (top-level)`

I have correctly installed all dependencies.

PS: When compiling a message in the console say
`32517 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named Math`
Thanks for your answers 👍

**Comment by malwaredllc** [comment]
Are you sure you've installed `pypiwin32`(Python extensions for Windows) and `pycryptodomex` (cryptography library)?

**Comment by didi110296** [comment]
Requirement already satisfied: pypiwin32 in c:\python27\lib\site-packages (223)
Requirement already satisfied: pycryptodomex in c:\python27\lib\site-packages (3.8.1)
Requirement already satisfied: pywin32>=223 in c:\python27\lib\site-packages (from pypiwin32) (224)

**Comment by malwaredllc** [comment]
Did it throw any error messages when you generated the client?

**Comment by didi110296** [comment]
No error when generating, expect
`32517 INFO: Loading module hook "hook-Crypto.py"... Traceback (most recent call last): File "<string>", line 2, in <module> ImportError: No module named Math`

I'm trying to install visual studio 15 for get compilation packages from vs

**Comment by didi110296** [comment]
I've found what the error, i've just use a bad port forwarded.

**Comment by Fngye** [comment]
how to solve the problem？ple
