### ISSUE TITLE
Neither Python3 nor Python2 works now, great!

### ISSUE THREAD

**Issue by TormentedSoul666** [malwaredllc/byob#120]
Python2: python2 client.py --pastebin *BLUR* --encrypt --compress *BLUR* 445 escalate persistence process
"File "/home/jonas/byob/byob/core/util.py", line 444, in pastebin
    from urllib2 import urlsplit,urlunsplit
ImportError: cannot import name urlsplit" You are using urllib2 for Python2, which is deprecated due to malware behavior.
Python3: 
python3 client.py --pastebin *BLUR* --encrypt --compress *BLUR* 445 escalate persistence process
"File "client.py", line 309, in _payload
    output = security.encrypt_xor(payload, base64.b64decode(kwargs['key']))
  File "/home/jonas/byob/byob/core/security.py", line 400, in encrypt_xor
    data    = bytes(data) + (int(block_size) - len(bytes(data)) % int(block_size)) * bytes(padding)
TypeError: string argument without an encoding"

Can you put my nose on the solution?

**Comment by intrct** [comment]
For starters, the project wasn't written for Python 3, that is something the community is actively working on.

As for the Python 2 issue, 

> ImportError: cannot import name urlsplit" You are using urllib2 for Python2, which is deprecated due to malware behavior.

**Comment by TormentedSoul666** [comment]
Thank yo, you are king.
