### ISSUE TITLE
Dependencies are not correctly evaluated

### ISSUE THREAD

**Issue by TormentedSoul666** [malwaredllc/byob#123]
python2 client.py --name BLUR --pastebin BLUR --encrypt --compress --freeze BLUR 1337

[>] Modules
	Adding modules... - (3 modules added to client)

[>] Imports
	Adding imports..- (24 imports from 3 modules)

[>] Payload
	Compressing payload...  (123,119 bytes reduced to 63,175 bytes (-49.0% smaller)                         
	Encrypting payload.../ (63,175 bytes increased to 84,248 bytes (33.0% larger)                          
	Uploading payload... -
Traceback (most recent call last):
  File "client.py", line 438, in <module>
    main()
  File "client.py", line 190, in main
    payload = _payload(options, var=var, key=key, modules=modules, imports=imports, hidden=hidden)
  File "client.py", line 321, in _payload
    url = util.pastebin(payload, options.pastebin)
  File "/root/byob/byob/core/util.py", line 444, in pastebin
    from urllib2 import urlsplit,urlunsplit
ImportError: cannot import name urlsplit

**Comment by TormentedSoul666** [comment]
urllib2 is not available as a standalone package anymore.

**Comment by malwaredllc** [comment]
This has been fixed by PR #127
