### ISSUE TITLE
Python3-executed bot will not gracefully failover to passive on disconnect

### ISSUE THREAD

**Issue by intrct** [malwaredllc/byob#126]
Bot attempts to leverage 100% on the single thread it has at time of spontaneous drop from the server connection.

Suspicion at this time is a looping behavior in Python3 is failing to set passive, working on testing.

**Comment by malwaredllc** [comment]
Thanks for making note of this issue, and nice work on PR #127 by the way.

**Comment by intrct** [comment]
NP --Just trying to make it usable in v3 so people can keep learning.
