### ISSUE TITLE
'dict' object has no attribute 'send_tasks'

### ISSUE THREAD

**Issue by ashcatium** [malwaredllc/byob#134]
I got everything running right, but I cannot use broadcast module. I want to tell all my infected computers run reboot in terminal. Also, how do I make the payload reconnect them without clicking it again?

**Comment by intrct** [comment]
Few items:
  Python version used for C2?
  Python version for bots?

Some features have not been fixed in Python 3, and persistence is one possible issue.

**Comment by malwaredllc** [comment]
@ashcatium Python3 support has been completed in #191
