### ISSUE TITLE
freeze error not recognized as an internal or external command

### ISSUE THREAD

**Issue by alkafaiz** [malwaredllc/byob#135]
I tried to create executable file using freeze command but this error appeared.
![image](https://user-images.githubusercontent.com/23336030/59314215-eb539180-8ce6-11e9-92d0-5e418586d959.png)
It kept printing null, I looked at the source code, my guess is on the while true loop in generators.py. but still not sure how to fix it.
```
    process = subprocess.Popen('{} -m PyInstaller {}'.format(sys.executable, fspec), 0, None, subprocess.PIPE, subprocess.PIPE, subprocess.PIPE, shell=True)
   
    while True:
        try:
            line = process.stderr.readline().rstrip()            
        except:           
            break
        if line.strip() != None:            
            util.display(line, color='reset', style='dim')
            line = line.decode('utf-8')           
            if 'EXE' in line and 'complete' in line:
                break
        time.sleep(0.25)
    output = os.path.join(path, 'dist', name + str('.exe' if os.name == 'nt' else ''))
    print(output)
```
help please?

**Comment by malwaredllc** [comment]
Is there a space in the path name of the Python executable on your machine?

**Comment by alkafaiz** [comment]
I guess it's on the machine, my user folder's name contains white space

**Comment by malwaredllc** [comment]
Yeah PyInstaller (the package used for compiling Python scripts into binary executables) doesn't handle white spaces in file paths. 
Try running it using a path without white spaces and it will work.
