### ISSUE TITLE
Adding script to BYOB

### ISSUE THREAD

**Issue by joker8989** [malwaredllc/byob#136]
Can i add my features to BYOB project? is so how can i do it? where to import the modules where to add the files?

thankx

**Comment by malwaredllc** [comment]
If you just want your own scripts to be available for clients to use, you can add the scripts to the `byob/modules/` directory on the machine you're using as the C2 server, and they will become available for clients to remotely import (`load <module>` command) then execute (`run <module>` command).

If you're talking about or new features/modules for the project, you can create a pull request, which I will review and potentially merge if it doesn't break anything and it seems like a cool/useful feature.
