### ISSUE TITLE
i am so confused

### ISSUE THREAD

**Issue by irequis** [malwaredllc/byob#139]
ive been trying to test this for about 3 hours by hosting on my pc and using my laptop as the 'test subject', everytime i execute the client.py on my pc it gets to the writing the dropper and gives me this message, (and i cant figure out for the life of me why)

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

im sure its just something to do with me not knowing how to set the byob up correctly but im lost.

this could be something extremely simple but i dont even know where to start. any help appreciated.

**Comment by malwaredllc** [comment]
There is probably a space in the file path (e.g. C:\Program Files\...) which PyInstaller (the package used to compile the python script into a binary executable) doesn't handle properly. 
To get around this issue, try using a different file path without a space.
