### ISSUE TITLE
byob SUPPORTED?

### ISSUE THREAD

**Issue by joker8989** [malwaredllc/byob#148]
Hey i am testing this tool but its big problem is that is very laggy the shell always crashes only the screenshot command works keylogger start does not work/perssitence i have not tested random and miner...
![Screenshot (158)](https://user-images.githubusercontent.com/35543679/64886802-b2bdae00-d66f-11e9-898c-ebdf31d93e6e.png)
![Screenshot (159)](https://user-images.githubusercontent.com/35543679/64886803-b3564480-d66f-11e9-9a4a-b245dd5b2808.png)
![Screenshot (160)](https://user-images.githubusercontent.com/35543679/64886804-b4877180-d66f-11e9-811c-f88c1cc0ab6e.png)

**Comment by malwaredllc** [comment]
Yes

**Comment by joker8989** [comment]
@malwaredllc i have edited my post was posted itself

**Comment by joker8989** [comment]
@malwaredllc Can you give me support about my issues? the screenshots above?

**Comment by malwaredllc** [comment]
@joker8989  The issues with the shell have been fixed in #191 as well as bugs in various modules - try again with a clean install and let me know if you have any issues.
