### ISSUE TITLE
BYOB not creating an EXE

### ISSUE THREAD

**Issue by jchernin4** [malwaredllc/byob#150]
I ran every command correctly and when it is finished running client.py with --freeze it says something like this:
(16,317,804 bytes saved to file: /DIRECTORY/byob/byob/dist/byob_bai)
but for most people it would be byob_bai.exe
I tried renaming the file (adding .exe to the end) once I downloaded it to my PC but it says "This app can't run on your PC" and doesn't let me run it. Anyone know why?

**Comment by yamortsa** [comment]
same issue

**Comment by zezekaka** [comment]
So, if byob use the pyintaller to generate the executable, the format/extension of the executable will depend on which operating system you used for compilation. For example, if you run the PyInstaller command on windows the executable file will be .exe. If you run it on Linux the extension will depend on the distribution you are using.

**Comment by jchernin4** [comment]
Ohh ok that sounds about right because I made it on Raspian Linux ty for the help, that makes so much more sense 😄

**Comment by MircoCagni** [comment]
> So, if byob use the pyintaller to generate the executable, the format/extension of the executable will depend on which operating system you used for compilation. For example, if you run the PyInstaller command on windows the executable file will be .exe. If you run it on Linux the extension will depend on the distribution you are using.


So how can generate .exe file from linux?

**Comment by zezekaka** [comment]
You can try build a docker with PyInstaller with Windows ( you'll find some tutorials on youtube about that), but you will have to do some changes on BYOB's compiler code. If you don't have this skill, you can just use another code, you can find one even here on GitHub but I do not guarantee that it will work as well.

**Comment by MircoCagni** [comment]
> You can try build a docker with PyInstaller with Windows ( you'll find some tutorials on youtube about that), but you will have to do some changes on BYOB's compiler code. If you don't have this skill, you can just use another code, you can find one even here on GitHub but I do not guarantee that it will work as well.

Sorry my english is realy bad, but i try to use in windows but it make so many error. But i have a question, the victim (in my case a vm windows 10) for execute payload (.exe) must have a python installed?

**Comment by debian-user-france1** [comment]
no, the victim doesn't need python.

**Comment by debian-user-france1** [comment]
> > So, if byob use the pyintaller to generate the executable, the format/extension of the executable will depend on which operating system you used for compilation. For example, if you run the PyInstaller command on windows the executable file will be .exe. If you run it on Linux the extension will depend on the distribution you are using.
> 
> So how can generate .exe file from linux?

I can't do it. But once it was working... Now it creates a python file but the other is missing. And it says, PyInstalller is missing, but that is installer (sudo pip3 install pyinstaller) and I didn't found pyinstaller in the client script. Only a comment

**Comment by debian-user-france1** [comment]
- Platform Independent
        compatible with PyInstaller and package is authored
        in Python, a platform agnostic language


only here is pyinstaller found in the script. Maybe pyinstaller is in a other generator script... Maybe the developer wrote PyInstaller instead of pyinstaller

**Comment by debian-user-france1** [comment]
FIXED:
You have to write python3 client.py ...
because there is no pyinstaller in python2 or normal python

**Comment by debian-user-france1** [comment]
OF COURSE YOU CAN CREATE EXE FILES. AT END YOU HAVE TO RENAME THEY TO .EXE... THERE IS A .PY AND A .SPEC, YOU HAVE TO RENAME THE .SPEC TO .EXE

**Comment by AmirTheHacker** [comment]
It wont load when I am creating a exe file

**Comment by mosqitoburito** [comment]
> So, if byob use the pyintaller to generate the executable, the format/extension of the executable will depend on which operating system you used for compilation. For example, if you run the PyInstaller command on windows the executable file will be .exe. If you run it on Linux the extension will depend on the distribution you are using.

so what command do you use to generate the EXE on windows because I couldnt find it in any tutorials

**Comment by jchernin4** [comment]
I have no idea I asked this 2 years ago

**Comment by Cheese999Jr** [comment]
If anyone could list a specific set of commands to create an executable exe file for windows on byob it would be greatly appreciated.
