### ISSUE TITLE
Make it compatible with a free hosting platform

### ISSUE THREAD

**Issue by steviebeenz** [malwaredllc/byob#155]
I am wanting to use this to test business security, but require the ability to use a free hosting platform like Firebase or Backendless

**Comment by d0n601** [comment]
Can't you afford $5 bucks a month to test business security?

**Comment by rotzbouf** [comment]
For testing purpose, you should consider to host it locally in an isolated environment rather than try to get it on a free hosting platform. Your plan does not sound well thought.
