### ISSUE TITLE
Client cannot connect directly if target is running a virtual machine

### ISSUE THREAD

**Issue by TheSeventhCode** [malwaredllc/byob#156]
I've just tested a bit around with the whole server and client and ran into the problem, that my client wasn't connecting to the server. So after a bit searching around i started the client with the --debug parameter and got the warning that I was running a virtual machine and if I wanted to abort. I declined and there was my client connecting to the server without a problem.
I don't know if this behaviour is wanted or so but it would be nice if it was documented somewhere.

**Comment by rotzbouf** [comment]
Read the docs. It is well stated that client shuts down when its detecting sandbox or VM mode.
