### ISSUE TITLE
Last Seen Online Timestamp not updating

### ISSUE THREAD

**Issue by rotzbouf** [malwaredllc/byob#158]
First of all, this is a great project. Great for educational use and security people.
After fiddling a bit around I saw that the last seen online timestamp of clients does not update correctly.
As seen below, both timestamps only differ some millliseconds. Thus this was taken around 22h50, thus it should have updated in the meantime.

  joined             2019-10-19 22:12:13.055517
  last_online        2019-10-19 22:12:13.056272

**Comment by malwaredllc** [comment]
I'm glad to hear you like the project.
The "last online" timestamp when a client connects or disconnects. I'm thinking name of the timestamp should be updated to something more accurate (perhaps "last login" or "last session").

**Comment by rotzbouf** [comment]
you could add another one and show "last seen online#" timestamp of a client and "last session on client" timestamp. would be useful to know when a client was last talking to the server, same with when you triggered last time a connection to it (or in this case asking connection from it)
