### ISSUE TITLE
Fatal Error! Failed to execute script byob_kc9

### ISSUE THREAD

**Issue by Infinium1** [malwaredllc/byob#161]
I compiled everything with no errors and got have server.py running but when I tried opening the exe I got the message:

Fatal Error! Failed to execute script byob_kc9

and I do not get anything in my terminal window that has server.py running. Anyone know why?

**Comment by jchernin4** [comment]
Running on Windows 10 by the way

**Comment by deifler90** [comment]
same error... I'm using this versions:

- Win 10
- python 2.7.15
- pip 9.0.3
- pyinstaller 3.3.1
- VC from: http://aka.ms/vcpython27

(I have tried different versions, but with more problems, and this versions works for me on ubuntu).

If I make the .py it works well, but the exe show the "Fatal Error! Failed to execute script"

**Comment by Infinium1** [comment]
Did you ever figure out the solute @deifler90 ?

**Comment by deifler90** [comment]
> 
> 
> Did you ever figure out the solution @deifler90 ?

No, I'm trying other similar program, because I have done a lot of tests with different versions (and operating systems) and nothing worked... It will be difficult to solve without an admin help...

**Comment by Infinium1** [comment]
@deifler90 have you gotten any other programs to work? If so, do you mind linking them? Thanks :)

**Comment by deifler90** [comment]
@Infinium1 I'm using this: 

https://github.com/n1nj4sec/pupy

I have it working on ubuntu, check the features, but I think that there are not big differences... and it can generate clients for different operating systems
