### ISSUE TITLE
Failed to execute script pyiboot01_bootstrap

### ISSUE THREAD

**Issue by xKeksbyte** [malwaredllc/byob#164]
title.

        Compiling executable...
 312 INFO: PyInstaller: 3.3.1
312 INFO: Python: 2.7.15
312 INFO: Platform: Windows-10-10.0.17763
328 INFO: UPX is not available.

**Comment by malwaredllc** [comment]
I believe there is an issue with PyInstaller (the library used to compile the python script into a binary executable) as this issue has popped up a few times recently. I will look into it and let you know what I find out.

**Comment by malweghorst** [comment]
Have there been any updates? I couldn't download it from the web either. I moved the file over with flash drive and it still cant be run.

**Comment by b0dstone** [comment]
same error here
-Python 3.8.2 on Win10 1909

**Comment by malwaredllc** [comment]
I just pushed a quick fix in #198 
Pull the changes and try again. Let me know if there are any issues.
