### ISSUE TITLE
How to use the miner.

### ISSUE THREAD

**Issue by xKeksbyte** [malwaredllc/byob#165]
title.

**Comment by malwaredllc** [comment]
Have you tried looking at the documentation for the miner module?

**Comment by malwaredllc** [comment]
After the client has successfully connected to the server and you have a shell open, the command is:
`miner <url> <username> <password`

Please note that this the URL of a **stratum** (pooled) Bitcoin mining server.

For example, you can sign up for a site like https://nicehash.com to get a server URL and credentials for this.
