### ISSUE TITLE
[idea] Local spreader module

### ISSUE THREAD

**Issue by Gouster4** [malwaredllc/byob#172]
Module that would infect executable files on clients machine. removable medias with highest priority.
original file can be packed with BYOB itself into some self extraction anchive, and enctypted to prevent being analyzed by antivirus. After runing new executable, that original executable would be run too, but also with BYOB which would spread again in another machine. Would be also cool to include some limits like hom much files to infect in minute, or maximum disk read/write speed, we dont want to overload clients hdd, to aviod getting found even by user itsel..
I think this seems to be better way than with emails. people getting more and more informed about not opening unknown attachments in emails. and most users are using web email clients instead of local ones like outlook.

**Comment by malwaredllc** [comment]
Interesting idea - feel free to submit a pull request for a local spreader module and I will review it and merge it.
