### ISSUE TITLE
Can't create a EXE file in Linux

### ISSUE THREAD

**Issue by Sm4k1na** [malwaredllc/byob#174]
Hello so basically I have my Kali laptop, and I installed byob in it and I tried to create an exe file but ofc --freeze doesn't create an exe cause I am on Linux and I can't use byob in Windows because it's full of problems like missing modules that doesn't exist and other things, is there something like --os ? Thanks

**Comment by malwaredllc** [comment]
Try the crosscomp script (see the directory /byob/crosscromp).

**Comment by Sm4k1na** [comment]
Yes I saw that and what file should I modify and with what? Thanks

**Comment by malwaredllc** [comment]
Oh to create an executable for Windows you need to do that on a Windows machine. Sorry, there's no way around that at the moment.
