### ISSUE TITLE
listening server ports

### ISSUE THREAD

**Issue by amsainfor** [malwaredllc/byob#177]
How many ports is needed open/redirect on firewall to run byob server? 

In my example with python 2.7, server.py open 4 listening ports and client script is creates with port number +1 from server port, ex: server port is 4445, and generated client port is 4446

Thank you

![Screenshot 2020-01-30 at 13 03 58](https://user-images.githubusercontent.com/6783521/73453897-e40bf180-4364-11ea-93bc-23e862a02e0d.png)
![Screenshot 2020-01-30 at 13 21 35](https://user-images.githubusercontent.com/6783521/73453906-e66e4b80-4364-11ea-8357-29ec64469f31.png)

**Comment by malwaredllc** [comment]
The server listens on 4 ports:

1. The main port: for incoming connections from clients (4445 in your screenshot)
2. Main port + 1: for serving BYOB modules, payloads, and stagers
3. Main port + 3: for serving third-party Python packages for clients to remotely import and use without installing them on the client machine
4. Main port + 4: for handling incoming HTTP POST requests containing file uploads from the clients
