### ISSUE TITLE
Some noob questions

### ISSUE THREAD

**Issue by Skeleton333** [malwaredllc/byob#181]
I'm using Kali Linux (2019.3 x64) after cloning the program from github I ran setup.py and then client.py.
My problem is that I don't know how to import the modules into the victim PC ... nor how to install the payload and run it remotely ... since even the broadcast does not work ...

**Comment by panpansh** [comment]
read the README inside the crosscomp folder, it helps a lot

**Comment by Skeleton333** [comment]
Ok thank you... but for the broadcast command how can I do??? (doesn't work yet...)

**Comment by panpansh** [comment]
Debian

**Comment by Skeleton333** [comment]
But Kali linux is Debian based...

**Comment by malwaredllc** [comment]
The first machine you must deliver the payload via your own methods. After that, you can use the "spread <url>" command to attempt to infect more client machines. Note: the "<url>" argument is the URL of text file (pastebin or similar) containing a list of email addresses to deliver payloads to.

**Comment by Skeleton333** [comment]
Thank you very much...
I would have one last noob question: to import a module into the paylod I have to perform `./client.py <ip><port><module-name.py>`??

**Comment by malwaredllc** [comment]
You don't need to include modules in the payload itself (i.e. when running the `client.py` payload generator script). Once a client has connected to the server and you start a shell with that client, simply running the command for the module you want to run will automatically remotely import that module and all of its dependencies. 
For example, running the `screenshot` command from the shell will automatically remotely import that module and all of its dependencies, run the screenshot module, and return the results.

**Comment by Skeleton333** [comment]
Thank you
