### ISSUE TITLE
Start of negotiation with python3

### ISSUE THREAD

**Issue by panpansh** [malwaredllc/byob#185]
Dear @malwaredllc ,
let's try to migrate to python3.

Here the build_environment.sh python3 ready : 
https://github.com/malwaredllc/byob/pull/183

Here the requirements.txt file updated : 
https://github.com/malwaredllc/byob/pull/184

Here remove an exception conversion from server.py : 
https://github.com/malwaredllc/byob/pull/186

![image](https://user-images.githubusercontent.com/790586/74619309-5e928a80-5135-11ea-94c0-4b989a46f554.png)

I will keep looking.
Are you present in a discussion group or a messaging service ?
Regards.

**Comment by malwaredllc** [comment]
Yeah I'm definitely down to collaborate on including support for Python 3. Thanks for submitting those pull requests, I will review/merge them today. 
I have been thinking about creating a Slack channel or something for this. In the meantime you can email me at security@malwared.com

**Comment by fu050409** [comment]
Hey, Dear my friend @panpansh .
It doesn't seems that it runs well on my Windows platform.
I don't know if it is a problem of my computer.
Can I contact you by email? This is my email address:
[fu050409@163.com](mailto:fu050409@163.com)
Thank you so much!

**Comment by panpansh** [comment]
Dear @malwaredllc Thanks.
Let me know for Slack or something like that.

Dear @fu050409 I'm too busy.
The changes made were made to match linux first.
Subsequently I am interested in Windows once BYOB works on linux.
You are welcome to participate in the evolution of this magnificent project, it would be a pleasure.

Regards

**Comment by malwaredllc** [comment]
@panpansh  I finished the python3 port in #191 let me know if you come across any issues.

**Comment by panpansh** [comment]
Oh nice @malwaredllc,
I will watch it very soon.
Best regards.
👍
