### ISSUE TITLE
Support for other languages.

### ISSUE THREAD

**Issue by fu050409** [malwaredllc/byob#190]
Dear @malwaredllc ,
I made an issue before to show my decode error.
After that, I had another tests on two machine both running CentOS and the default language is English. I succeed. It means that this project is not support other languages which not ascii.
Then, I add 
```python
import sys
reload(sys) if sys.version_info[0] > 2
sys.defaultencoding('utf8') if sys.version_info[0] > 2
```
at the top of the file server.py.
It doesn't throw me the decode error but a base64 error. I think you're probably not thinking about non-ascii encoding.
Hope this can help you.

**Comment by fu050409** [comment]
My English is poor, please tell me if you don't understand. @malwaredllc

**Comment by malwaredllc** [comment]
At the moment there isn't support for languages that use non-ascii characters. It would be nice to support other languages though, so if you want to submit a pull-request with these updates I will review/merge it.
