### ISSUE TITLE
problem in the client code

### ISSUE THREAD

**Issue by thepythonscript** [malwaredllc/byob#192]
can someone help with the code error, please?
**[>] Modules
	Adding modules...  -(3 modules added to client)

[>] Imports
	Adding imports...-(25 imports from 3 modules)

[>] Payload
Traceback (most recent call last):
  File "client.py", line 438, in <module>
    main()
  File "client.py", line 190, in main
    payload = _payload(options, var=var, key=key, modules=modules, imports=imports, hidden=hidden)
  File "client.py", line 285, in _payload
    loader  = '\n'.join((open('core/loader.py','r').read(), generators.loader(host=options.host, port=int(options.port)+2, packages=list(kwargs['hidden']))))
ValueError: invalid literal for int() with base 10: '-----------'**

**Comment by malwaredllc** [comment]
What command-line arguments did you use when running `client.py`?

**Comment by thepythonscript** [comment]
never mind I fixed it just some error with the arguments
