### ISSUE TITLE
is this normal

### ISSUE THREAD

**Issue by thepythonscript** [malwaredllc/byob#193]
I don't really know what I'm talking about but I would think that if a backdoor was running that the client.py program should keep running but when I run this "sudo python3 client.py host myip port 8081 --name testsub1", it gives me this

```
[>] Modules
	Adding modules...  -(3 modules added to client)

[>] Imports
	Adding imports... -(25 imports from 3 modules)
```

Is this normal or should it stay running?

**Comment by garsh1** [comment]
This is what it should say:

[>] Modules
        Adding modules...  -(3 modules added to client)

[>] Imports
        Adding imports... (26 imports from 3 modules)

[>] Payload
        Uploading payload...  (hosting payload at: http://port:80801///payloads/aCO.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://port:80801///stagers/aCO.py)

[>] Dropper
        Writing dropper...  (335 bytes written to Test.py)

**Comment by malwaredllc** [comment]
As indicated by @garsh1, client.py should finish generating your script fairly quickly.
