### ISSUE TITLE
Failed to execute script pyiboot01_bootstrap

### ISSUE THREAD

**Issue by Jozese** [malwaredllc/byob#196]
I believe It's pycharm faults but It seems to compile it correctly. Has anyone found this issue lately?
I'm using python 3.7.7 and I don't have pycryto installed
Using pyinstaller 3.6

**Comment by malwaredllc** [comment]
Are you running PyInstaller manually? Or using the --freeze option when running client.py?

**Comment by Jozese** [comment]
Im using --freeze yeah

**Comment by malwaredllc** [comment]
I just tested this on Windows 10 with Python 2.7 and it worked fine for me.

**Comment by malwaredllc** [comment]
Note: I have Visual Studio installed on the machine I was testing this on, and I suspect this may be related. Can you try installing Visual Studio then trying the `--freeze` command again and let me know if it works? If so, that will confirm my suspicion and I will add this to the documentation.

**Comment by Jozese** [comment]
Okay will try

**Comment by malwaredllc** [comment]
I just pushed a quick fix in #198 
Pull the changes and try again and it should work. Let me know if there are any issues.
