### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by Lowell-liu** [malwaredllc/byob#202]
I use python3.5.3, will report TypeError.  When I execute a client-generated file.
3.5 bytes type can not json.

**Comment by malwaredllc** [comment]
@Lowell-liu Technically only Python 2.7 and 3.7 are officially supported, but can you run the client-generated file in debug mode (`--debug`) and take a screenshot of your error or copy/paste the output?
