### ISSUE TITLE
Monero?

### ISSUE THREAD

**Issue by aloisberngardt** [malwaredllc/byob#206]
Hello, can you please create monero miner in botnet?

**Comment by malwaredllc** [comment]
I am currently working on this. Right now I'm thinking about integrating XMRig. If you or anyone else has any thoughts on this, please let me know.

**Comment by aloisberngardt** [comment]
Wow, thank you so much!

**Comment by aloisberngardt** [comment]
I have two ideas:
1. Download and unpack xmrig with python and execute it with args.
2. On github i found many python monero miners. Maybe you can use it?

**Comment by malwaredllc** [comment]
@aloisberngardt XMRig integration has been done in #214 
The command is `miner <cmd> [url] [wallet address]`
Possible commands are `run` and `stop` (the `stop` command requires no arguments).
Try it out with a fresh install and let m know if you have any issues.

**Comment by aloisberngardt** [comment]
Wow! Thank you!

**Comment by aloisberngardt** [comment]
Must i download xmrig on victim pc? Can i change cpu usage?

**Comment by malwaredllc** [comment]
@aloisberngardt You don't need to download XMRig. The BYOB server now has pre-compiled executable versions of XMRig for Windows x64, Linux i386, and Mac OS x64 (I still need to add Linux amd64 and more). The payload will automatically download and run the version for the platform it is running on.
Right now there isn't an option to change CPU usage, however, I can look into expanding the miner options in the future.
