### ISSUE TITLE
Help does not really work and one issue more

### ISSUE THREAD

**Issue by aloisberngardt** [malwaredllc/byob#208]
I have it if enter help:

**[ 0 @ C:\ ]>help persistence
            command <arg>                            description
 persistence <add/remove> [method]    establish persistence on client host machine

 [ 0 @ C:\ ]>help process
       command <arg>                          description
 process <block/monitor>    block process (e.g. antivirus) or monitor process**

But i don't know, which methods i can use. Do you have any tutorial?

 **[ 0 @ C:\ ]>process list
Unterminated string starting at: line 1 column 164 (char 163)**

This error i have in cmd -> tasklist and in shell -> process list too.

I have only python3 on my server.

**Comment by malwaredllc** [comment]
I will add more documentation/help for commands soon (see #207)

As far as the `process list` command, I will try to replicate this issue. What OS is the client payload running on?

**Comment by aloisberngardt** [comment]
Thank you.

Windows 10 1909.
