### ISSUE TITLE
Linux Ubuntu 14.04  dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by aloisberngardt** [malwaredllc/byob#209]
I have this error on Ubuntu 14.04:

 Error loading Python lib '/tmp/_MEI5J2FAM/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI5J2FAM/libpython3.7m.so.1.0)

with client (compiled with --freeze option on server Ubuntu 19.09).

But maybe it is pyinstaller error?

**Comment by malwaredllc** [comment]
That means the program was compiled against glibc version 2.29, and it requires that version to run, but your system has an older version installed. You will need to update glibc.

Try `apt-get update`. If that doesn't work, try `apt-get install libc6`.

**Comment by aloisberngardt** [comment]
Ah, ok. Thank you very much.
