### ISSUE TITLE
Adding a GUI for byob (feature request)

### ISSUE THREAD

**Issue by Defaltx** [malwaredllc/byob#210]
A GUI would come handy to use the program, especially for beginners, a simple user interface where to setup the botnet.

**Comment by malwaredllc** [comment]
@FabxBs Good news - I've been working hard on this for quite some time! Announcement coming soon...

**Comment by malwaredllc** [comment]
@Defaltx Just released the web gui, you can find it in the /byob/web-gui directory. Check out the Getting Started Guide on https://buildyourownbotnet.com/guide
