### ISSUE TITLE
Port issues

### ISSUE THREAD

**Issue by iii235** [malwaredllc/byob#213]
When I build a client with this command python3 client.py --name testbot.py --freeze (my ip) 4444, it later says on in the building process that it his hosting the stager and payload on https://my ip:444**5**. Does this mean that I have to run the server on port 4445, even though I told the client builder to build a client for port 4444?

**Comment by malwaredllc** [comment]
Nope, you still run the server on port 4444. The main C2 server runs on the port you specify, the payloads and stagers are hosted on port + 1 (4445), and Python packages for are hosted on port + 2 (4446).

**Comment by iii235** [comment]
Thx, I also ran into another issue. When I try to run the exe client on a Windows VM (transfered with Google Drive link) it refuses to run.

**Comment by malwaredllc** [comment]
To create a Windows executable you have to generate it on a Windows machine. If you generate it on a Linux machine, it will be a Linux executable.

**Comment by iii235** [comment]
But, I thou(by you said you just needed the --freeze tag to create Windows exe.

**Comment by malwaredllc** [comment]
The `--freeze` command will create an executable formatted for the current operating system.
Don't worry though, I am working on something that allows you to easily create an executable for any operating system you want.
