### ISSUE TITLE
Pip not installing pyhook

### ISSUE THREAD

**Issue by iii235** [malwaredllc/byob#217]
I am trying to install Byob on Windows 10, but when I run "pip3 install -r requirements.txt" everything goes smoothly until the cmd prompt says something like "Could not find a version that satisfies the requirement pyHook==1.5.1. No matching distribution found for pyHook==1.5.2." Can you help me out?

**Comment by malwaredllc** [comment]
Try downloading pyHook from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook
You'll need to select the version for your Python version, OS, etc. For example if you have Python 3.7 running on a 64 bit Windows machine you would download pyHook‑1.5.1‑cp37‑cp37m‑win_amd64.whl
