### ISSUE TITLE
client.py --encrypt error

### ISSUE THREAD

**Issue by aloisberngardt** [malwaredllc/byob#222]
Hello!
I have this error in Linux (Kali 2020) and Windows 10:

[>] Stager
Traceback (most recent call last):
  File "client.py", line 440, in <module>
    main()
  File "client.py", line 191, in main
    stager  = _stager (options, var=var, key=key, modules=modules, imports=imports, hidden=hidden, url=payload)
  File "client.py", line 353, in _stager
    stager = open('core/stagers.py', 'r').read() + generators.main('run', url=kwargs['url'], key=kwargs['key'])
  File "/home/alois/byob/byob/core/generators.py", line 174, in main
    options = ', '.join(args) + str(', '.join(str("{}={}".format(k, v) if bool(v.count('{') > 0 and v.count('}') > 0) else "{}='{}'".format(k,v)) for k,v in kwargs.items() if v != None) if len(kwargs) else '')
  File "/home/alois/byob/byob/core/generators.py", line 174, in <genexpr>
    options = ', '.join(args) + str(', '.join(str("{}={}".format(k, v) if bool(v.count('{') > 0 and v.count('}') > 0) else "{}='{}'".format(k,v)) for k,v in kwargs.items() if v != None) if len(kwargs) else '')
TypeError: argument should be integer or bytes-like object, not 'str'

if i use option --encrypt with python3 client.py.

**Comment by malwaredllc** [comment]
Good catch, there appears to be a bug in the client.py script when run with Python3. I will work on fixing it. 
For now you can use Python2 and it should work.

**Comment by windowshopr** [comment]
I'm also getting this error on Windows 10, Python 3.7.9 from this command:

`python client.py --name payloadone --encrypt --compress --freeze 123.123.123.13 8080`

IP address is fake obvi. Would be cool to get this fixed for Python 3 :)
