### ISSUE TITLE
Make a wiki / documentation 

### ISSUE THREAD

**Issue by a8underscore** [malwaredllc/byob#224]
this would be really helpful, thanks for this entire project btw! its really helpful and the source code is clean and not confusing and/or obfuscated

**Comment by malwaredllc** [comment]
Wiki has been added - special thanks to @akeithx for putting it together!
@a8underscore Let me know if there is any additional information you think would be helpful to include in it. I was thinking of adding a section on compiling executables, as that seems to trip people up pretty frequently.
