### ISSUE TITLE
Failed to execute script 

### ISSUE THREAD

**Issue by rei-sys** [malwaredllc/byob#225]
When I use the --freeze option it generates an exe file, when I open that file I get an error "Failed to execute script filename", if I open the python file that generates the exe I get a connection in the server

**Comment by malwaredllc** [comment]
Please generate the executable using the `--debug` option, run the executable and post the debugging output it provides here.

See step by step instructions for doing this here:
https://github.com/malwaredllc/byob/wiki/Compiling-Executable-Payloads
