### ISSUE TITLE
codec can't decode byte 0x9d in position 0: invalid start byte

### ISSUE THREAD

**Issue by xKeksbyte** [malwaredllc/byob#226]
[ 1 @ /root/nigz]>passive
Session init exception: 'utf-8' codec can't decode byte 0x9d in position 0: invalid start byte

-] Failed Connection: publicipxddddddddddddddddddddddd

^  doesnt matter what command, always the same error

**Comment by malwaredllc** [comment]
@xKeksbyte Which version of python are you using?

**Comment by xKeksbyte** [comment]
Python 3.6.9

**Comment by malwaredllc** [comment]
This project was written with Python 2.7, if you use it this bug will not appear.
However I will work on fixing this bug for Python 3 compatibility.
