### ISSUE TITLE
Help? 

### ISSUE THREAD

**Issue by novicered** [malwaredllc/byob#227]
Is there anyway to remove the virus from the victim machine also removing your miner off the machine?

**Comment by malwaredllc** [comment]
@novicered I'm not sure I understand your question - you can simply delete the files if you don't want to use the software anymore.

**Comment by malwaredllc** [comment]
If you want to run the software without the miner running in the background, simply comment out the line of code `self._init_dev_miner()` in the files `server.py` and `payloads.py`

**Comment by novicered** [comment]
Asking if I'm able to remove the malware from the victims computer

**Comment by malwaredllc** [comment]
@novicered If you want to remove BYOB from the target machine, you can do this easily by using the `abort` command. This will remove all persistence methods from the target machine, delete the payload, and exit.

**Comment by novicered** [comment]
Thank you
