### ISSUE TITLE
Client ID does not exist

### ISSUE THREAD

**Issue by ghost** [malwaredllc/byob#231]
I don't know why but after trying the botnet on 2 of my machines, they don't have an ID set.

When a client is added byob does give it an ID but it doesn't exist anymore in my clients and I can't shell it.

Clients list : 
![image](https://user-images.githubusercontent.com/58915214/83912059-7f76fe00-a76d-11ea-99d6-7e56af3c1e8a.png)

Can't connect to any shell
![image](https://user-images.githubusercontent.com/58915214/83912134-a2a1ad80-a76d-11ea-93f4-376a3b58586e.png)

**Comment by SpLayzDKG** [comment]
Anyone got a fix for this?

**Comment by pokarkishan** [comment]
Chill Men..! Understand Code Properly
