### ISSUE TITLE
web gui installtion error

### ISSUE THREAD

**Issue by iii235** [malwaredllc/byob#242]
When I run the .sh file on Windows 10, I get this issue: Running BYOB app startup...
Confirmed Python is installed.
Confirmed Docker is installed.
Installing Python packages...
startup.sh: line 31: /c/Users/jaybu/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
Building Docker images - this will take a while, please be patient...
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Users\jaybu\Desktop\byob-master\web-gui\docker-pyinstaller\Dockerfile-py3-amd64: The system cannot find the file specified.
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Users\jaybu\Desktop\byob-master\web-gui\docker-pyinstaller\Dockerfile-py3-i386: The system cannot find the file specified.
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Users\jaybu\Desktop\byob-master\web-gui\docker-pyinstaller\Dockerfile-py3-win32: The system cannot find the file specified.
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
startup.sh: line 43: /c/Users/jaybu/AppData/Local/Microsoft/WindowsApps/python3: Permission denied

I manually installed the requirements.txt earlier, so anything relating to python isn't an issue. (Still need to get freaking pyHook on; why in the world would you use a module that isn't compatible with the most recent version on python? It's pretty agrivating trying to find a working pyHook when you advertised this as "no-dependencies". Why not pyWinHook?) I just need to know why it isn't finding the files.

**Comment by malwaredllc** [comment]
I am making a video walkthrough of the installation/setup process now, I will post it tomorrow.

**Comment by malwaredllc** [comment]
Installation and Setup Video Walkthrough: https://www.youtube.com/watch?v=XA-S_FRz2ho

**Comment by mosquito-mosquito** [comment]
> Installation and Setup Video Walkthrough: https://www.youtube.com/watch?v=XA-S_FRz2ho

Hello. Video access is limited. What happened?

**Comment by 0Shark** [comment]
https://www.youtube.com/watch?v=uVyniPrTzuk
Here's the link
