### ISSUE TITLE
Nothing happens when I enter HTTP://0.0.0.0:5000

### ISSUE THREAD

**Issue by HK-BP-Octopus** [malwaredllc/byob#247]
Hi, I´m having some trouble with the installation, I did what your website told me; I installed Docker, and already had python, then with the cdm I executed the startup.sh, and it asked me with what to run it, I used docker, then when a notification told me that it was installed, i ran run.oy and then entered http://0.0.0.0:5000, but nothing happened, help, I'm not an advanced user, but did I miss something or do I need to install something else, I need your help, regards <3

**Comment by malwaredllc** [comment]
I am making a video walkthrough of the installation/setup process now, I will post it tomorrow.

**Comment by malwaredllc** [comment]
Installation and Setup Video Walkthrough: https://www.youtube.com/watch?v=XA-S_FRz2ho

**Comment by HK-BP-Octopus** [comment]
Oops, its private

**Comment by HK-BP-Octopus** [comment]
You shoul try uploading it in another place, ti avoid problems

**Comment by TheCrazyInsanity** [comment]
> Installation and Setup Video Walkthrough: https://www.youtube.com/watch?v=XA-S_FRz2ho

That video is private

**Comment by dontbanmeplz** [comment]
No http://

**Comment by bigredhub** [comment]
so this happened with me, did yall go into boyb-master then boyb folder and run setup? that fixed my problem

**Comment by Jarnek** [comment]
Are you running on Windows? On my windows box it worked navigating to 127.0.0.1:5000 instead of 0.0.0.0:5000
