### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by q8yas2** [malwaredllc/byob#248]
hi
when run.py
say
ModuleNotFoundError: No module named 'flask'
what problem plz

**Comment by Th0rGer** [comment]
same problem

**Comment by malwaredllc** [comment]
Installation and Setup Video Walkthrough: https://www.youtube.com/watch?v=XA-S_FRz2ho

**Comment by Th0rGer** [comment]
same error... 

`Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/root/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'`

**Comment by dontbanmeplz** [comment]
install with "pip3 install flask"
and run with "python3 run.py"

**Comment by HK-BP-Octopus** [comment]
> install with "pip3 install flask"
> and run with "python3 run.py"

still its not working, do I need to install something else?

**Comment by DebianFox** [comment]
run `pip3 install -r requirements.txt`, it will install all the modules is needed

**Comment by dontbanmeplz** [comment]
It works just flask isn’t installing for some people there is no problem with byob

**Comment by nickzsche** [comment]
> > "pip3 install flask" 
> > ile kurun ve "python3 run.py" ile çalıştırın
> 
> Hala çalışmıyor, başka bir şey yüklemem gerekiyor mu?

sudo python3 run.py

**Comment by xcapitan** [comment]
> Installation and Setup Video Walkthrough: https://www.youtube.com/watch?v=XA-S_FRz2ho

vedioved

**Comment by Donovanw645** [comment]
Is byob compatible with parrot security OS?

**Comment by supernous** [comment]
yes is compatible, for all problem to start byob, open run.py and change ip in 127.0.0.1

**Comment by nickzsche** [comment]
Thank u

6 Mar 2023 Pzt 20:00 tarihinde supernous ***@***.***> şunu
yazdı:

**Comment by neekerinpersekyrpa** [comment]
fucking idiot niggers kille yourselfes. You all cant fix this error.
