### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Quixel2017** [malwaredllc/byob#251]
C:\byob\byob>python client.py 192.168.0.51 8080 --freeze

88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'

[>] Modules
        Adding modules...  -(4 modules added to client)

[>] Imports
        Adding imports... (32 imports from 4 modules)

[>] Payload
        Uploading payload...  (hosting payload at: http://192.168.0.51:8081///payloads/dnU.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://192.168.0.51:8081///stagers/dnU.py)

[>] Dropper
        Writing dropper...  (343 bytes written to byob_dnU.py)
        Compiling executable...
 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
get this when i try to run the command, acts as if enter is constantly pressed after

**Comment by malwaredllc** [comment]
There is a space in between "C:\Progam" and "Files" (i.e. "C:\Program Files") which unfortunately the PyInstaller library does not have logic to handle properly.
