### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by K4Li11011** [malwaredllc/byob#252]
**i cant install requirements.txt in kali linux

plz help me**

byob/byob# pip install -r requirements.txt
/usr/share/python-wheels/pkg_resources-0.0.0-py3-none-any.whl/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Ignoring mss: markers 'python_version > "3"' don't match your environment
Ignoring WMI: markers 'python_version > "3"' don't match your environment
Ignoring numpy: markers 'python_version > "3"' don't match your environment
Ignoring pyxhook: markers 'python_version > "3"' don't match your environment
Ignoring twilio: markers 'python_version > "3"' don't match your environment
Ignoring colorama: markers 'python_version > "3"' don't match your environment
Ignoring requests: markers 'python_version > "3"' don't match your environment
Ignoring PyInstaller: markers 'python_version > "3"' don't match your environment
Ignoring pycryptodome: markers 'python_version > "3"' don't match your environment
Ignoring pycrypto: markers 'python_version > "3"' don't match your environment
Ignoring pyHook: markers 'sys_platform == "win32"' don't match your environment
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Collecting py-cryptonight>=0.2.4
  Using cached py_cryptonight-0.3.3.tar.gz (352 kB)
Collecting pyrx
  Cloning https://github.com/jtgrassie/pyrx.git to /tmp/pip-install-UXoOWS/pyrx
  Running command git clone -q https://github.com/jtgrassie/pyrx.git /tmp/pip-install-UXoOWS/pyrx
  Running command git submodule update --init --recursive -q
Collecting mss==3.3.0
  Using cached mss-3.3.0-py2.py3-none-any.whl (19 kB)
Collecting WMI==1.4.9
  Using cached WMI-1.4.9.zip (26 kB)
Collecting numpy==1.15.2
  Using cached numpy-1.15.2-cp27-cp27mu-manylinux1_x86_64.whl (13.8 MB)
Collecting pyxhook==1.0.0
  Using cached pyxhook-1.0.0.tar.gz (4.3 kB)
Collecting twilio==6.14.0
  Using cached twilio-6.14.0-py2.py3-none-any.whl (821 kB)
Collecting colorama==0.3.9
  Using cached colorama-0.3.9-py2.py3-none-any.whl (20 kB)
Collecting requests==2.20.0
  Using cached requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting PyInstaller==3.6
  Using cached PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpoOQfg2
       cwd: /tmp/pip-install-UXoOWS/PyInstaller
  Complete output (1 lines):
  /usr/bin/python: can't find '__main__' module in '/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpoOQfg2 Check the logs for full command output.

**Comment by th30c05** [comment]
Try to use:
pip3 install -r requirements.txt

**Comment by Krizsan0596** [comment]
it doesnt install most of it with pip3

**Comment by eyeseesea** [comment]
pip install each requirement

**Comment by Krizsan0596** [comment]
It says that the requirements were made for an other version but I can't install them through the older versions either

**Comment by th30c05** [comment]
Try to made a new python enviroment abd re-install

**Comment by Krizsan0596** [comment]
What do you mean by make a new python environment

**Comment by debian-user-france1** [comment]
In Ubuntu 20.04 with pip3 is no -r funktion. I had to install all seperate.

**Comment by Krizsan0596** [comment]
Use pip and not pip3

**Comment by debian-user-france1** [comment]
I was not able to use pip, sorry if I said smth wrong

**Comment by debian-user-france1** [comment]
Maybe I can install it

**Comment by Krizsan0596** [comment]
Use apt install python-pip
