### ISSUE TITLE
How to access one sessions on windows

### ISSUE THREAD

**Issue by ricko2991** [malwaredllc/byob#257]
Hi, can you help me. 
Well, when i execute the exe file into the target computer running windows machine, the window is always open and not stop until i stoped it in my server. And in my server the sessions is always open while the program open in the target computer. I want to acces the target machine but the sessions always open. In my case, i capture 30 sessions but i send it just for one machine. How can i get one session if i execute in target machine?

Note : I'm running windows machine & python3 to create server and client.

**Comment by malwaredllc** [comment]
I'm not sure if I understand your question, are you asking how to run the payload without the terminal (command prompt on Windows) staying open the whole time it's running? For a python payload, just change the file extension from .py to .pyw, or for a compiled executable there should be no window open by default.

**Comment by ricko2991** [comment]
I'm just fine if i run .py exstension. If i run executable .exe the sessions always come up and not stop. 
Maybe, i show you the screenshot from me:
![Screenshot (39)](https://user-images.githubusercontent.com/67855001/88270950-04f84280-cd09-11ea-9c52-45e12d6abd74.png)
![Screenshot (40)](https://user-images.githubusercontent.com/67855001/88271651-0e35df00-cd0a-11ea-988c-f2fbad757b9c.png)

Note: i'm using
Windows 10
Python 3.7
Microsoft visual studio c++ 2017

**Comment by ricko2991** [comment]
I'm just fine if i run .py exstension. If i run executable .exe the sessions always come up and not stop.
Maybe, i show you the screenshot from me:

![Screenshot_(39)](https://user-images.githubusercontent.com/67855001/88272179-e85d0a00-cd0a-11ea-951f-8259a7a2ec7f.png)
![Screenshot (40)](https://user-images.githubusercontent.com/67855001/88272197-f0b54500-cd0a-11ea-917b-f139ef734eb8.png)

Note: i'm using
Windows 10
Python 3.7
Microsoft visual studio c++ 2017
