### ISSUE TITLE
Web-Gui

### ISSUE THREAD

**Issue by AfroYousef** [malwaredllc/byob#258]
Can someone check if this is actually working because after many errors i looked at the code and the imports are very unusual they look like they should work however i have to move the file into the same directory in order for python to properly import it and it also looks like there is a missing db.py file so can someone please help with this?

**Comment by malwaredllc** [comment]
I helped you with this directly in the Discord Support channel so I am closing this issue.

**Comment by AfroYousef** [comment]
It didn't work.
