### ISSUE TITLE
Ngrok not working

### ISSUE THREAD

**Issue by JimmmerR** [malwaredllc/byob#260]
I've been trying to use this program with ngrok because I can't port forward. Is it even possible???

**Comment by malwaredllc** [comment]
It is not compatible with ngrok at this time, just the actual IP address. This would be a good feature though, if you want to implement it in your own fork and issue a pull request I will merge it.

**Comment by dontbanmeplz** [comment]
I made a ngrok thing in a pull
Check it out

**Comment by ricko2991** [comment]
Sorry, where?

**Comment by dontbanmeplz** [comment]
One sec

**Comment by dontbanmeplz** [comment]
https://github.com/dontbanmeplz/byob/tree/cb6f89825d73d259e488cda4da5f6ab34c70492b

**Comment by ricko2991** [comment]
Ok. and what about byob CLI ?. I also can't use ngrok on CLI.

**Comment by dontbanmeplz** [comment]
Wdym by you cant use ngrok on cli?

**Comment by ricko2991** [comment]
Sorry,  I just answered now because I slept last night. I mean under the picture i can't use ngrok.
![IMG_20200905_074737](https://user-images.githubusercontent.com/67855001/92291765-b1eeed80-ef4c-11ea-82c2-c85b31b32656.jpg)

**Comment by dontbanmeplz** [comment]
It’s in the web-GUI

**Comment by ricko2991** [comment]
Thank you, but it would be great if you added the ngrok feature in the cli (command line interface). Because I work with cli.

**Comment by dontbanmeplz** [comment]
Ill try
