### ISSUE TITLE
problem with coloroma 

### ISSUE THREAD

**Issue by raxou** [malwaredllc/byob#264]
hello i have a probleme when i run
the module coloroma is not find
i have installed colorama with the command
pip3 install colorama
![image](https://user-images.githubusercontent.com/40395422/88824104-3324c900-d1c6-11ea-9f5b-920ed9a13f11.png)

**Comment by malwaredllc** [comment]
Looks like you installed colorama with pip3 (Python3+) and launched the server with Python 2+.
