### ISSUE TITLE
Problem Install

### ISSUE THREAD

**Issue by diaverso** [malwaredllc/byob#269]
"Error" appears when installing

Command - python setup.py 
Error link:https://gist.github.com/diaverso/c89e2ff1b2b3560409d105cae63f8647

Command - sudo -H pip3 install -r requirements.txt
Error link: https://gist.github.com/diaverso/fa41d913c3c8b254867c654721ca9e87

**Comment by malwaredllc** [comment]
For this error, you can simply remove the "pyre" package from the requirements.txt file (it is not strictly necessary and is only used in 1 module).
