### ISSUE TITLE
Can you make a tutorial

### ISSUE THREAD

**Issue by gamingmastyer** [malwaredllc/byob#274]
There is only one clip on youtube with a tutorial and that is really old if you are able to make a clip or a readme file that would be great. The skids like me would appreciate it.

**Comment by mrsoms** [comment]
Please make a tutorial
It will really help 
Thanks

**Comment by mrsoms** [comment]
Are you on Telegram by the way?

**Comment by htkcodes** [comment]
no. tutorial stop being skids.

**Comment by Kaiziron** [comment]
there is already a tutorial out there by the creator 
https://www.youtube.com/watch?v=uVyniPrTzuk

**Comment by debian-user-france1** [comment]
I have done the turorial, but i like a Tutorial witch says how to USE this, because i have many issues... like connection problems and generation problems...
