### ISSUE TITLE
WE NEED A PROPER READ ME FILE OR A VIDEO WALK-THROUGH IN WINDOWS 

### ISSUE THREAD

**Issue by mrsoms** [malwaredllc/byob#275]
I keep on getting "Python int too large to convert to convert to C ssize_t" 
Also "no file or directory"

Please help yeah👍

**Comment by htkcodes** [comment]
stop being a skid. learn to read the code.

**Comment by bigredhub** [comment]
or dual boot Linux

**Comment by leyvatheam** [comment]
wsl if u love too much microshaft
