### ISSUE TITLE
I cannot create an executable windows x32 or linux amd64 etc.

### ISSUE THREAD

**Issue by MiChaelinzo** [malwaredllc/byob#279]
I'm using web-gui and can't create executable for windows and linux
but I can with Python easily 
this what appears in the console when i try to make one
<img width="52" alt="byob" src="https://user-images.githubusercontent.com/68110223/92173996-d1025800-ee44-11ea-82a8-6a95e74e3027.PNG">

**Comment by mrsoms** [comment]
Same here
Also python script keeps giving me connection timed out

**Comment by dontbanmeplz** [comment]
It doesn’t work 
If you can fix it then fix it
If you cant the too bad
Make your own exe and Linux executables

**Comment by ricko2991** [comment]
So what you mean is that after I create the payload in python format I have to compile it manually. For example when the python payload has been created i'm creating an executable file using the pyinstaller manually. like that?

**Comment by dontbanmeplz** [comment]
Yes

**Comment by MiChaelinzo** [comment]
> It doesn’t work
> If you can fix it then fix it
> If you cant the too bad
> Make your own exe and Linux executables

wtf is this ??, we are here in the issues section to get help

**Comment by dontbanmeplz** [comment]
I’m just trying to say that i cant fix it.
But i will make a page in the wiki telling you hoe @MiChaelinzo @ricko2991

**Comment by dontbanmeplz** [comment]
I’m sorry for being rude

**Comment by mrsoms** [comment]
Don't worry
Please tell us how we can compile it to executable

**Comment by dontbanmeplz** [comment]
On windows you can use WSL and pyinstaller to make Linux packages and https://www.py2exe.org/ to make exe files.
On Linux you can only make Linux executables unless you do some stuff with docker and wine https://github.com/cdrx/docker-pyinstaller

**Comment by mrsoms** [comment]
Thank you
Which do you recommend we use 
CLI or WEB-GUI?

**Comment by dontbanmeplz** [comment]
Web GUI is awesome so that

**Comment by mrsoms** [comment]
Okay thanks
I use Ubuntu on virtual box. 
When I send a python cli to my windows OS it gives me connection timed out

**Comment by dontbanmeplz** [comment]
Because your Ubuntu box is not connected to the internet

**Comment by mrsoms** [comment]
Windows susbstyem Linux
Okay
With that I will be able to connect to other pcs in my local network?

**Comment by dontbanmeplz** [comment]
Yes and the rest of the network as well. You are running a Linux box on your computer that is basically sharing the system resources

**Comment by mrsoms** [comment]
Man you are best
Thank You very much 🙏👍👍

**Comment by mrsoms** [comment]
What's your discord account so that I contact you if I have a problem

**Comment by dontbanmeplz** [comment]
Chis27#9412

**Comment by dontbanmeplz** [comment]
Sorry no 27

**Comment by ricko2991** [comment]
ok. i want to test it to run in windows machine. Can i run web-gui in windows machine?
If i use docker and modify the startup.sh to python code to install dependency. Thanks

**Comment by dontbanmeplz** [comment]
No docker will only work on linux i think or it would be some MAJOR changes to startup.sh and changing it to startup.exe ot startup.bat

**Comment by dontbanmeplz** [comment]
Maybe ill work on that when i get some time with @malwaredllc

**Comment by mrsoms** [comment]
I have sent you a request.
So with the WSL everything will work now

**Comment by dontbanmeplz** [comment]
Right now i am turning the startup.sh into startup.exe so no worrys

**Comment by MiChaelinzo** [comment]
**sorry i wasn't thorough this is the source of my errors etc...**
<img width="324" alt="byobs" src="https://user-images.githubusercontent.com/68110223/92293042-2adc4e00-ef29-11ea-87a5-ef3e8c213f0a.PNG">

**Comment by dontbanmeplz** [comment]
The docker flies don’t work

**Comment by Sanket-kumbhar** [comment]
> > The docker flies don’t work
> 
> yeah fixed it, thanks
hey can you explain me the fix

**Comment by MiChaelinzo** [comment]
> > > The docker flies don’t work
> > 
> > 
> > yeah fixed it, thanks
> > hey can you explain me the fix

run in root for docker or either change file permission if the folder/file

**Comment by MP3Martin** [comment]
> Okay thanks
> I use Ubuntu on virtual box.
> When I send a python cli to my windows OS it gives me connection timed out

Don't use VirtualMachine. I think Ubuntu for windows is better. Am using it. I doesnt solve your problem but it isn't emulating anythingso it uses less memory. [Download Ubuntu for windows](https://tinyurl.com/y9sdpyqu)

**Comment by Baca666** [comment]
> It doesn’t work If you can fix it then fix it If you cant the too bad Make your own exe and Linux executables

I bought new laptop, after some time I copied the byob folder from my old laptop to new one, installed docker, runned byob, tried to make .exe for windows x32 and it worked. It created the file. Idk why or how it worked, but it did. Its not bcs of update cause its and old file. I really dont know

**Comment by AaronRohrbacher** [comment]
If running WSL, docker desktop is easiest. The `b' '` thing you were seeing was the script trying to use docker but failing. I've gotten as far as the web-gui creating win32 executables, but they do not connect to any server, and I don't understand the underlying python- so agreed, probably best to just use the client.py/server.py to generate python, then compile...
