### ISSUE TITLE
Generate .exe Payload - VERY strange error in CMD (maybe?) in CMD 

### ISSUE THREAD

**Issue by peebeekay89** [malwaredllc/byob#285]
So I can build python payload very easy. But when I go to build .exe paypal It freezes and when i go to CMD this is being spammed over and over again. 

Compiling executable...
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''

It doesn't stop. Until I close CMD and therefore losing access to 127.0.0.1:5000. What Am i doing wrong here?

**Comment by dontbanmeplz** [comment]
Known problem
