### ISSUE TITLE
 Problem with the Payload generator 

### ISSUE THREAD

**Issue by nikhilhurule** [malwaredllc/byob#288]
The payload get generated but  when i try to install it in windows it says"Failed to execute script byob_win_x32_bla"
The Python one also does not works

**Comment by Darkstreet00** [comment]
Payload generator not working. I'm just want to create Windows payload but i get the Oops message.

<em>
ERROR:buildyourownbotnet:Exception on /api/payload/generate [POST]
Traceback (most recent call last):
  File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kriss/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kriss/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kriss/Asztal/byob/web-gui/buildyourownbotnet/api/payload/routes.py", line 37, in payload_generate
    if freeze and subprocess.check_call(['which','docker']) != 0:
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['which', 'docker']' returned non-zero exit status 1.
<em/>

**Comment by GetRektBoy724** [comment]
> Payload generator not working. I'm just want to create Windows payload but i get the Oops message.
> _ ERROR:buildyourownbotnet:Exception on /api/payload/generate [POST] Traceback (most recent call last): File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/kriss/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/home/kriss/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/kriss/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view return func(*args, **kwargs) File "/home/kriss/Asztal/byob/web-gui/buildyourownbotnet/api/payload/routes.py", line 37, in payload_generate if freeze and subprocess.check_call(['which','docker']) != 0: File "/usr/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['which', 'docker']' returned non-zero exit status 1. _

me too

**Comment by furankusama** [comment]
@GetRektBoy724 @nikhilhurule @Darkstreet00  So as the creator has mentioned, running the server behind a NAT might cause issues. I got the same error several times, even after port forwarding and trying other solutions. I can confirm that running the server on an external IP, directly on the internet, that is, did solve the "Fatal error" issue, and the payload ran successfully on the first attempt.

**Comment by GetRektBoy724** [comment]
> @GetRektBoy724 @nikhilhurule @Darkstreet00 So as the creator has mentioned, running the server behind a NAT might cause issues. I got the same error several times, even after port forwarding and trying other solutions. I can confirm that running the server on an external IP, directly on the internet, that is, did solve the "Fatal error" issue, and the payload ran successfully on the first attempt.

the payload not even created......lmao
you're saying something that didnt help this issue at all...
the issue in here was we had a problem WHILE CREATING THE PAYLOAD..

no offense :)

**Comment by GetRektBoy724** [comment]
> @GetRektBoy724 @nikhilhurule @Darkstreet00 So as the creator has mentioned, running the server behind a NAT might cause issues. I got the same error several times, even after port forwarding and trying other solutions. I can confirm that running the server on an external IP, directly on the internet, that is, did solve the "Fatal error" issue, and the payload ran successfully on the first attempt.

You are trying to fix a problem that is not this problem...
got it??

**Comment by GetRektBoy724** [comment]
> @GetRektBoy724 @nikhilhurule @Darkstreet00 So as the creator has mentioned, running the server behind a NAT might cause issues. I got the same error several times, even after port forwarding and trying other solutions. I can confirm that running the server on an external IP, directly on the internet, that is, did solve the "Fatal error" issue, and the payload ran successfully on the first attempt.

if you trying to fix @nikhilhurule problem then dont tag the others.....cause my problem and @Darkstreet00 was different
