### ISSUE TITLE
Executables winx32, nixi386, nixamd64 are not appearing in web-gui

### ISSUE THREAD

**Issue by MiChaelinzo** [malwaredllc/byob#290]
Executables winx32, nixi386, nixamd64 are not appearing only python created payloads are:

<img width="570" alt="byob" src="https://user-images.githubusercontent.com/68110223/95091972-c4b53780-072f-11eb-93c9-c5c0302419f4.PNG">

I have to manually locate it and make it executable from it's original extension of python .py or .spec rpm

**Comment by dontbanmeplz** [comment]
This is a known problem

**Comment by Sanket-kumbhar** [comment]
hey can you tell me how to mannually locate and make it executable

**Comment by MiChaelinzo** [comment]
go to /src of your /payloads etc. change the .py python file extension of created winx32 or nixi386, nixamd64 into .exe windows executable or .deb or .amd linux executables etc.

**Comment by Sanket-kumbhar** [comment]
Bro do we have make change in the scr/ in the userfile in BYOB module .
