### ISSUE TITLE
Windows/linux payload executable error

### ISSUE THREAD

**Issue by xxlimit** [malwaredllc/byob#293]
How do you fix this when I tell the payload creator to make a windows payload after some time it says this.
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
Exception in api.routes.payload.payload_generate: Timeout or out of memory
INFO:werkzeug:127.0.0.1 - - [07/Oct/2020 14:07:49] "POST /api/payload/generate HTTP/1.1" 302 -

Also has a problem with Linux executable too!

b'9598 INFO: Looking for ctypes DLLs'
b'Traceback (most recent call last):'
b'  File "/root/.pyenv/versions/3.7.5/bin/pyinstaller", line 8, in <module>'
b'    sys.exit(run())'
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run'
b'    run_build(pyi_config, spec_file, **vars(args))'
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build'
b'    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)'
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main'
b"    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))"
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 681, in build'
b'    exec(code, spec_namespace)'
b'  File "byob_nix_amd64_c13.spec", line 13, in <module>'
b'    cipher=block_cipher)'
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__'
b'    self.__postinit__()'
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__'
b'    self.assemble()'
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 436, in assemble'
b"    ctypes_code_objs = self.graph.get_co_using_ctypes()  # dict like:  {'module1': code_obj, 'module2': code_obj}"
b'  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 674, in get_co_using_ctypes'
b'    r_ident =  r.identifier'
b"AttributeError: 'NoneType' object has no attribute 'identifier'"

**Comment by furankusama** [comment]
Restart the server machine and run the payload generator again.
