### ISSUE TITLE
New problem with payload generator with byob

### ISSUE THREAD

**Issue by Ace0fFate** [malwaredllc/byob#295]
Compiling executable...

b'0044:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\\\\\.\\\\DISPLAY1".'
b'0044:err:ole:start_rpcss Failed to start RpcSs service'
b'0094:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\\\Registry\\\\Machine\\\\System\\\\CurrentControlSet\\\\Services\\\\wineusb": c0000142'

it's writing this and I don't know what to do

**Comment by ricko2991** [comment]
Use python2 and install all dependencies on requirements.txt

**Comment by Ace0fFate** [comment]
> Use python2 and install all dependencies on requirements.txt
> If all dependencies succesfully install try running again

i have already installed requirements.txt, except one  that it couldn't download it pyrx , that doesn't get installed. I used python3

**Comment by debian-user-france1** [comment]
I have the same issue. I installed ALL requirements with pip3.   Python script generating works, Linux is working now, but on install I was not able to create executeble files, now only Windows is the problem:

usr/bin/docker
(343 bytes written to output/france1/src/byob_win_x32_o84.py)
	Compiling executable...

b'docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.'
b"See 'docker run --help'."

OH! This is another problem, the wine problem is fixed. Try to delete wine (sudo apt purge wine), I does this and I MAYBE RESTARTED THE COMPUTER. I hope this log was helpful - oh, the invite link for Discord is not working. not existing or, dont know in english, "running out"

**Comment by debian-user-france1** [comment]
-I installed Docker
