### ISSUE TITLE
Issue with Dockered Daemon

### ISSUE THREAD

**Issue by ElonKerman** [malwaredllc/byob#296]
bablin@DESKTOP-MJQR7KT:~/byob/web-gui$ sudo ./startup.sh
[sudo] password for bablin:
Running BYOB app startup...
Confirmed Python is installed.
Confirmed Docker is installed.
Installing Python packages...
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring pyHook: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: flask in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: flask_session in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (0.3.2)
Requirement already satisfied: flask_wtf in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (0.14.3)
Requirement already satisfied: Flask_SQLAlchemy in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (2.4.4)
Requirement already satisfied: Flask_Login in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (0.5.0)
Requirement already satisfied: Flask_Bcrypt in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (0.7.1)
Requirement already satisfied: flask_mail in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (0.9.1)
Requirement already satisfied: wtforms in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (2.3.3)
Requirement already satisfied: mss==3.3.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 9)) (3.3.0)
Requirement already satisfied: WMI==1.4.9 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 10)) (1.4.9)
Requirement already satisfied: numpy==1.15.2 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 11)) (1.15.2)
Requirement already satisfied: pyxhook==1.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 12)) (1.0.0)
Requirement already satisfied: twilio==6.14.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 13)) (6.14.0)
Requirement already satisfied: colorama==0.3.9 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 14)) (0.3.9)
Requirement already satisfied: requests==2.20.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 15)) (2.20.0)
Requirement already satisfied: pycryptodomex==3.8.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 16)) (3.8.1)
Requirement already satisfied: py-cryptonight>=0.2.4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 17)) (0.3.3)
Requirement already satisfied: pyrx from git+https://github.com/jtgrassie/pyrx.git#egg=pyrx in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 18)) (0.0.4)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 19)) (4.4.0.44)
Requirement already satisfied: cachelib in /usr/local/lib/python3.8/dist-packages (from flask_session->-r requirements.txt (line 2)) (0.1.1)
Requirement already satisfied: itsdangerous in /usr/lib/python3/dist-packages (from flask_wtf->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: SQLAlchemy>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from Flask_SQLAlchemy->-r requirements.txt (line 4)) (1.3.19)
Requirement already satisfied: bcrypt in /usr/local/lib/python3.8/dist-packages (from Flask_Bcrypt->-r requirements.txt (line 6)) (3.2.0)
Requirement already satisfied: blinker in /usr/lib/python3/dist-packages (from flask_mail->-r requirements.txt (line 7)) (1.4)
Requirement already satisfied: MarkupSafe in /usr/lib/python3/dist-packages (from wtforms->-r requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: python-xlib in /usr/local/lib/python3.8/dist-packages (from pyxhook==1.0.0->-r requirements.txt (line 12)) (0.28)
Requirement already satisfied: pysocks; python_version >= "3.0" in /usr/local/lib/python3.8/dist-packages (from twilio==6.14.0->-r requirements.txt (line 13)) (1.7.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from twilio==6.14.0->-r requirements.txt (line 13)) (1.14.0)
Requirement already satisfied: PyJWT>=1.4.2 in /usr/lib/python3/dist-packages (from twilio==6.14.0->-r requirements.txt (line 13)) (1.7.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from twilio==6.14.0->-r requirements.txt (line 13)) (2020.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 15)) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests==2.20.0->-r requirements.txt (line 15)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests==2.20.0->-r requirements.txt (line 15)) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 15)) (2019.11.28)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt->Flask_Bcrypt->-r requirements.txt (line 6)) (1.14.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt->Flask_Bcrypt->-r requirements.txt (line 6)) (2.20)
Building Docker images - this will take a while, please be patient...
Sending build context to Docker daemon  31.74kB
Step 1/12 : FROM ubuntu:12.04
12.04: Pulling from library/ubuntu
d8868e50ac4c: Pull complete
83251ac64627: Pull complete
589bba2f1b36: Pull complete
d62ecaceda39: Pull complete
6d93b41cfc6b: Pull complete
Digest: sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005
Status: Downloaded newer image for ubuntu:12.04
 ---> 5b117edd0b76
Step 2/12 : SHELL ["/bin/bash", "-i", "-c"]
 ---> Running in 801758a4446e
Removing intermediate container 801758a4446e
 ---> 74ae00ddace3
Step 3/12 : ARG PYTHON_VERSION=3.7.5
 ---> Running in 4bd6a21abc91
Removing intermediate container 4bd6a21abc91
 ---> 9fd31a10e956
Step 4/12 : ARG PYINSTALLER_VERSION=3.6
 ---> Running in 2be6e924b2ec
Removing intermediate container 2be6e924b2ec
 ---> 7d550b1f5249
Step 5/12 : ENV PYPI_URL=https://pypi.python.org/
 ---> Running in c9daaf4a6062
Removing intermediate container c9daaf4a6062
 ---> ab93c7f86dd2
Step 6/12 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Running in 970fe529b75e
Removing intermediate container 970fe529b75e
 ---> 1b8a87db93c8
Step 7/12 : ENV PYENV_VERSION=${PYTHON_VERSION}
 ---> Running in fa54a5ba2ac1
Removing intermediate container fa54a5ba2ac1
 ---> 47a636069317
Step 8/12 : COPY entrypoint-linux.sh /entrypoint.sh
 ---> c962b4da9438
Step 9/12 : RUN     set -x     && apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         curl         wget         git         libbz2-dev         libreadline-dev         libsqlite3-dev         libssl-dev         zlib1g-dev         libffi-dev         libgdbm-dev         libgdbm3         uuid-dev         upx     && mkdir openssl     && cd openssl     && wget https://www.openssl.org/source/openssl-1.0.2u.tar.gz     && tar -xzvf openssl-1.0.2u.tar.gz     && cd openssl-1.0.2u     && ./config --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib     && make     && make install     && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc     && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc     && source ~/.bashrc     && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash     && echo 'eval "$(pyenv init -)"' >> ~/.bashrc     && source ~/.bashrc     && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION     && pyenv global $PYTHON_VERSION     && pip install --upgrade pip     && pip install pyinstaller==$PYINSTALLER_VERSION     && mkdir /src/     && chmod +x /entrypoint.sh
 ---> Running in 263752550fd7
cgroups: cannot find cgroup mount destination: unknown
Sending build context to Docker daemon  31.74kB
Step 1/12 : FROM i386/ubuntu:12.04
12.04: Pulling from i386/ubuntu
8caa11ecf275: Pull complete
da6eb0da9f97: Pull complete
3a1eb8dc7691: Pull complete
46c520ae5cba: Pull complete
67359710ccd1: Pull complete
Digest: sha256:6a0436f77316aeb6be5d1ff5ace2404d379b0bd7cfdb6e315b7d2f5a630c149b
Status: Downloaded newer image for i386/ubuntu:12.04
 ---> 31a710ebb956
Step 2/12 : SHELL ["/bin/bash", "-i", "-c"]
 ---> Running in 33d035e26fd7
Removing intermediate container 33d035e26fd7
 ---> 3f59881d81ed
Step 3/12 : ARG PYTHON_VERSION=3.7.5
 ---> Running in 2a2caadaea0b
Removing intermediate container 2a2caadaea0b
 ---> c86226d5c5a4
Step 4/12 : ARG PYINSTALLER_VERSION=3.6
 ---> Running in 9932d136a7e7
Removing intermediate container 9932d136a7e7
 ---> d5293e26cb09
Step 5/12 : ENV PYPI_URL=https://pypi.python.org/
 ---> Running in b62adc3c60cd
Removing intermediate container b62adc3c60cd
 ---> 8d4cb751afca
Step 6/12 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Running in 7bbcc3b2cc08
Removing intermediate container 7bbcc3b2cc08
 ---> b91e605258d8
Step 7/12 : ENV PYENV_VERSION=${PYTHON_VERSION}
 ---> Running in 99c57e1fb3a3
Removing intermediate container 99c57e1fb3a3
 ---> 29e40d9819c9
Step 8/12 : COPY entrypoint-linux.sh /entrypoint.sh
 ---> 2b9cd1b2be2f
Step 9/12 : RUN     set -x     && apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         curl         wget         git         libbz2-dev         libreadline-dev         libsqlite3-dev         libssl-dev         zlib1g-dev         libffi-dev         libgdbm-dev         libgdbm3         uuid-dev         upx     && mkdir openssl     && cd openssl     && wget https://www.openssl.org/source/openssl-1.0.2u.tar.gz     && tar -xzvf openssl-1.0.2u.tar.gz     && cd openssl-1.0.2u     && ./Configure linux-generic32 --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib     && make     && make install     && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc     && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc     && source ~/.bashrc     && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash     && echo 'eval "$(pyenv init -)"' >> ~/.bashrc     && source ~/.bashrc     && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION     && pyenv global $PYTHON_VERSION     && pip install --upgrade pip     && pip install pyinstaller==$PYINSTALLER_VERSION     && mkdir /src/     && chmod +x /entrypoint.sh
 ---> Running in 107ebfc481fa
cgroups: cannot find cgroup mount destination: unknown
Sending build context to Docker daemon  31.74kB
Step 1/25 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
4f53fa4d2cf0: Pull complete
6af7c939e38e: Pull complete
903d0ffd64f6: Pull complete
04feeed388b7: Pull complete
Digest: sha256:185fec2d6dbe9165f35e4a1136b4cf09363b328d4f850695393ca191aa1475fd
Status: Downloaded newer image for ubuntu:16.04
 ---> 096efd74bb89
Step 2/25 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 1d8158b3bdd7
Removing intermediate container 1d8158b3bdd7
 ---> 64e23250ce9f
Step 3/25 : ARG WINE_VERSION=winehq-staging
 ---> Running in 6ea5e278f4fe
Removing intermediate container 6ea5e278f4fe
 ---> dfb55789da64
Step 4/25 : ARG PYTHON_VERSION=3.7.5
 ---> Running in 3f27932dbb10
Removing intermediate container 3f27932dbb10
 ---> 386e1781b071
Step 5/25 : ARG PYINSTALLER_VERSION=3.6
 ---> Running in e010ea8f758d
Removing intermediate container e010ea8f758d
 ---> 34e5e6fb1431
Step 6/25 : RUN set -x     && dpkg --add-architecture i386     && apt-get update -qy     && apt-get install --no-install-recommends -qfy apt-transport-https software-properties-common wget     && wget -nv https://dl.winehq.org/wine-builds/winehq.key     && apt-key add winehq.key     && add-apt-repository 'https://dl.winehq.org/wine-builds/ubuntu/'     && apt-get update -qy     && apt-get install --no-install-recommends -qfy $WINE_VERSION winbind cabextract     && apt-get clean     && wget -nv https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks     && chmod +x winetricks     && mv winetricks /usr/local/bin
 ---> Running in cd4820e2353c
cgroups: cannot find cgroup mount destination: unknown
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Serving Python packages from /usr/local/lib/python3.8/dist-packages on port 1339...
Serving BYOB modules from /home/bablin/byob/web-gui/buildyourownbotnet/modules on port 1338...
 * Serving Flask app "buildyourownbotnet" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [12/Oct/2020 09:48:02] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Oct/2020 09:48:04] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Oct/2020 09:48:06] "POST /login HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [12/Oct/2020 09:48:06] "GET /sessions HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Oct/2020 09:48:08] "GET /payloads HTTP/1.1" 200 -
/usr/bin/docker
(347 bytes written to output/Bablin1901/src/byob_win_x32_uoU.py)
        Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b"See 'docker run --help'."
b''
b''
b''

What is my issue? I am using Ubuntu linux sub system for Windows.

Thanks

**Comment by dontbanmeplz** [comment]
Known problem the docker stuff doesn’t work

**Comment by dontbanmeplz** [comment]
I’m working on a fix

**Comment by MP3Martin** [comment]
Funfact: you can just start BYOB by doing: `sudo python3 run.py`
