### ISSUE TITLE
  Install is stuck on "Running setup.py bdist_wheel for opencv-python"

### ISSUE THREAD

**Issue by pashfido** [malwaredllc/byob#297]
Install is stuck on "Running setup.py bdist_wheel for opencv-python" It has been like this for 2 hours now, none of the other packages before took this long.

**Comment by Jarnek** [comment]
I have a similar issue, my installation is stuck on "install pyinstaller" when setting up the docker win32 container. I have this issue on kali linux 2020.3 and Blackarch linux. Longest waiting time was about 5 hours before cancelling

**Comment by ricko2991** [comment]
Use ubuntu

**Comment by ricko2991** [comment]
https://youtu.be/uVyniPrTzuk

**Comment by Jarnek** [comment]
I just tried it and ran into the same issue. The installation gets stuck at setup dependencies of pyinstaller in win32

**Comment by ricko2991** [comment]
Try to install pyinstaller manually. pip install PyInstaller==3.6. after succes pip install opencv-python==3.4.3.18. And see what error appears.

This is byob right, not web gui?

**Comment by drnhzn** [comment]
@ricko2991 I get the same error. Installing web gui on Ubuntu 20.04.

**Comment by Jarnek** [comment]
i am trying to get web gui too. Could it be an issue wit pyinstaller itself?

**Comment by ricko2991** [comment]
Install one by one first. Sometimes there are packages that need each other, but it will appear in the terminal if we want to create a package. 

OK. Try installing pyinsyaller from here: 
pip3 install https://github.com/pyinstaller/pyinstaller/archive/v3.6.zip 

One more pyinstaller is not really needed, it will only make byob executable in exe form. If you want to make it in executable, run it manually using pyinstaller, you can install it on another operating system that can download pyinstaller. So delete it in the requirements.txt and run **pip3 install -r requirements**. It will install all packages without error.

**Comment by drnhzn** [comment]
@ricko2991 Installed pysintaller using the command you gave me. Can't see pyinstaller in the requirements.txt. Running startup.sh now. Will get back to you when something comes up. Thanks!

**Comment by drnhzn** [comment]
Issue still exist. Here is the whole error.

![Screenshot from 2020-10-16 09-44-28](https://user-images.githubusercontent.com/19513536/96203531-b7504680-0f94-11eb-905b-353d318e63fe.png)

**Comment by ricko2991** [comment]
Hi, open folder docker-pyinstaller1, and edit all the docker image code:

![Screenshot (183)](https://user-images.githubusercontent.com/67855001/96204636-668e1d00-0f97-11eb-898a-2a299e92d60c.png)

![Screenshot (184)](https://user-images.githubusercontent.com/67855001/96204736-9d643300-0f97-11eb-869b-d37801ef8ee0.png)

![Screenshot (185)](https://user-images.githubusercontent.com/67855001/96204840-e4522880-0f97-11eb-801a-151ac95503e5.png)

**Comment by drnhzn** [comment]
@ricko2991 Will try it right now.

**Comment by drnhzn** [comment]
@ricko2991 Solved my problem! Thank youuu! Will close the other ticket. :)

**Comment by ricko2991** [comment]
my pleasure
Go forth and Hack the Planet

**Comment by Alexhomier** [comment]
@ricko2991 I can't find the # install pyinstaller where is it located?

**Comment by ricko2991** [comment]
the location is in the docker-pyinstaller1 folder

Pada tanggal Jum, 16 Okt 2020 pukul 14.19 Alexhomier <
notifications@github.com> menulis:

**Comment by Alexhomier** [comment]
@ricko2991 Yeah found it i'm waiting to see if it works

**Comment by mabyee** [comment]
> Hi, open folder docker-pyinstaller1, and edit all the docker image code:
> 
> ![Screenshot (183)](https://user-images.githubusercontent.com/67855001/96204636-668e1d00-0f97-11eb-898a-2a299e92d60c.png)
> 
> ![Screenshot (184)](https://user-images.githubusercontent.com/67855001/96204736-9d643300-0f97-11eb-869b-d37801ef8ee0.png)
> 
> ![Screenshot (185)](https://user-images.githubusercontent.com/67855001/96204840-e4522880-0f97-11eb-801a-151ac95503e5.png)

I've done this, but now the script just crashes.

**Comment by ricko2991** [comment]
can you show it?

**Comment by mabyee** [comment]
> can you show it?
 Yes. I've added a video showing the problem and pictures of how I edited the files.
https://www.youtube.com/watch?v=wfulNIVUmGE&feature=youtu.be
![help1](https://user-images.githubusercontent.com/54164636/96261461-65211c80-0fb8-11eb-8aab-96066a193256.JPG)
![help2](https://user-images.githubusercontent.com/54164636/96261467-67837680-0fb8-11eb-8425-7b6bbe03cd22.JPG)

**Comment by ricko2991** [comment]
Run as root first. and also the video isn't clear

**Comment by mabyee** [comment]
> Run as root first. and also the video isn't clear

I've tried that, and the video was just to show that it crashes. I've just installed it on a rpi4 running Raspbian now and it runs great.  Thank you for the help either way!

**Comment by Jarnek** [comment]
I just cant get it to work... I still get stuck at the same point...

**Comment by Jarnek** [comment]
when i change the forward slash in line 70 to a backslash, i still get stuck at the same point.
when i leave the slash, i get the error that docker can´t parse the command PIP...

**Comment by ricko2991** [comment]
Hei, Don't create an image for win32 just yet. Just comment or delete win32 image on startup.sh. Maybe that is one of the bugs that needs fixing.

![IMG_20201017_101753](https://user-images.githubusercontent.com/67855001/96326316-395a7100-1062-11eb-84cf-ee6dbc51d191.jpg)

**Comment by ricko2991** [comment]
Before you create. Move images that contains nix-amd64, nix-386, win-x32. 
Eg: docker image rm [ ID]


And also edit the code that you edited in the path docker-pyinstaller1 back to its original state.

**Comment by pashfido** [comment]
> Hi, open folder docker-pyinstaller1, and edit all the docker image code:
> 
> ![Screenshot (183)](https://user-images.githubusercontent.com/67855001/96204636-668e1d00-0f97-11eb-898a-2a299e92d60c.png)
> 
> ![Screenshot (184)](https://user-images.githubusercontent.com/67855001/96204736-9d643300-0f97-11eb-869b-d37801ef8ee0.png)
> 
> ![Screenshot (185)](https://user-images.githubusercontent.com/67855001/96204840-e4522880-0f97-11eb-801a-151ac95503e5.png)

i did this and now I get this error at the end 
![image](https://user-images.githubusercontent.com/57356815/96339537-61969f80-1063-11eb-8fbc-9e61ec03e82f.png)

**Comment by ricko2991** [comment]
Run on ubuntu v. 20.04 . it will allow it to install properly

**Comment by Jarnek** [comment]
For me it now works on Arch and Ubuntu 20.04. 
Great work, keep it on

**Comment by pashfido** [comment]
yeah same, thanks a ton. It works on ubuntu 20.04 now keep up the great work!
