### ISSUE TITLE
byob windows installation issue

### ISSUE THREAD

**Issue by jamesmiller9048** [malwaredllc/byob#298]
tried to run the run.py 
error shown :-
C:\Users\Friends\Downloads\byob-master\byob-master\web-gui>python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "C:\Users\Friends\Downloads\byob-master\byob-master\web-gui\buildyourownbotnet\__init__.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by Chr0m0s0m3s** [comment]
```pip install flask```

**Comment by Jarnek** [comment]
it works when you install the missing modules manually. Some have to be downloaded from pypi.org

**Comment by jamesmiller9048** [comment]
yes tried installation of pip install flask but its returning error again
of course this time its different

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "C:\Users\Friends\Downloads\byob-master\byob-master\web-gui\buildyourownbotnet\__init__.py", line 3, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'

**Comment by jamesmiller9048** [comment]
> it works when you install the missing modules manually. Some have to be downloaded from pypi.org

can I please know what are those modules

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.
