### ISSUE TITLE
CI Build Status

### ISSUE THREAD

**Issue by erayaydin** [malwaredllc/byob#3]
First of all, thank you for this amazing open source project :+1: 

I think, a build tester would be awesome for new developers (etc TravisCI). With this way, new developers can thing "is it true about buildable?".

Another issue is creating tags and version :smile_cat:  (of course w/ better commit messages :paintbrush: )

**Comment by colental** [comment]
All good ideas - thanks for the feedback!
I will start working on:

- TravisCl build tester 
- Tags
- Version
- Better commit messages

Any feedback is always appreciated!
