### ISSUE TITLE
Web Gui Installation stuck on "The installation gets stuck at setup dependencies of pyinstaller" 

### ISSUE THREAD

**Issue by drnhzn** [malwaredllc/byob#300]
I am on ubuntu 20.04 and the installation is stuck on "The installation gets stuck at setup dependencies of pyinstaller"

**Comment by Chr0m0s0m3s** [comment]
^Same here

**Comment by Haxxxoor** [comment]
+1

**Comment by mabyee** [comment]
+1

**Comment by ricko2991** [comment]
pip3 install https://github.com/pyinstaller/pyinstaller/archive/v3.6.zip

**Comment by drnhzn** [comment]
@ricko2991 Still the same

**Comment by ricko2991** [comment]
#297

**Comment by drnhzn** [comment]
Solved by using @ricko2991 tutorial on #297
