### ISSUE TITLE
web-gui stuck on installing python "3.7.5" in ubuntu 20.04 even though I have 3.7.5

### ISSUE THREAD

**Issue by pashfido** [malwaredllc/byob#301]
web-gui stuck on installing python "3.7.5" in a ubuntu 20.04 VM even though I already have python 3.7.5 and I have no idea why. I followed everything the video walkthrough said and it's still not working.

**Comment by ricko2991** [comment]
Install all requirements first. And then install docker

**Comment by pashfido** [comment]
> Install all requirements first. And then install docker
> 
> One thing python 3.7.5 only install for docker not for your operating system. So, whatever type of python3 in the operating system you use will not affect the containers you create, python will only help in creating the necessary containers and put in docker, and only containers containing python 3.7.5 will be executed in docker. And it will not affect the system if you update python to the latest version, for example python 3.8

I did that but I still get this error 
![image](https://user-images.githubusercontent.com/57356815/96349594-a11eb500-107e-11eb-9ef9-3b54925adc3c.png)

**Comment by pashfido** [comment]
i got it working nevermind, thank you!

**Comment by sixtii-ninee** [comment]
> i got it working nevermind, thank you!

how did you get it working am also stuck at this and also getting flask error even tho i instaaled flask
