### ISSUE TITLE
Screenshot saving location

### ISSUE THREAD

**Issue by naaax123** [malwaredllc/byob#304]
I succesfully took a screenshot but now cant find its location.

**Comment by ricko2991** [comment]
If you use byob, then the storage location is in the output folder.

**Comment by ricko2991** [comment]
![Screenshot (191)](https://user-images.githubusercontent.com/67855001/96327876-45e5c600-1070-11eb-9dfb-7b99f0c12681.png)

it will create an output folder automatically when you are done taking screenshot.

**Comment by kadeeq** [comment]
Ty for the answer sadly there is no file in there although it said that the screenshot was completed. But i tested the program on the same pc (so server and "victim" on the same ip) which might have been the issue. Gonna test it soon on another pc.
