### ISSUE TITLE
Setup.py throws error "arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-maes’; did you mean ‘-mapcs’?"

### ISSUE THREAD

**Issue by ElectronHippo** [malwaredllc/byob#310]
Installed BYOB onto a raspberry pi zero. installed dependencies yet this error persists.

 arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNO_JIT=1 -I. -Isrc/ -Isrc/cryptonight -I/usr/include/python3.7m -c src/cryptonight/aesb.c -o build/temp.linux-armv6l-3.7/src/cryptonight/aesb.o -std=gnu11 -maes

    arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-maes’; did you mean ‘-mapcs’?

    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by debian-user-france1** [comment]
I have the same issue, but BYOB works without, you just can run run.py
But a module might not work
PS: How did you installed it on a raspi? Zero has only 512 MB RAM
I did a swap
