### ISSUE TITLE
Build dependancies

### ISSUE THREAD

**Issue by SadlyBlank** [malwaredllc/byob#315]
ran ./setup.sh and it has been installing build dependencies for over an hour now

**Comment by lesmo** [comment]
I've had this happen to me too, it's stuck building dependencies for `Dockerfile-py3-win32`. I've even left it sitting there for almost 8hrs to no avail.

Seems related to #243

**Comment by alhazmy13** [comment]
if you are in linux, just edit [startup.sh](https://github.com/malwaredllc/byob/blob/master/web-gui/startup.sh) and comment `Dockerfile-py3-amd64` and `Dockerfile-py3-win32 `
```
#docker build -f Dockerfile-py3-amd64 -t nix-amd64 .
docker build -f Dockerfile-py3-i386 -t nix-i386 .
#docker build -f Dockerfile-py3-win32 -t win-x32 .
```

**Comment by alhazmy13** [comment]
This PR fixes this issue 
https://github.com/malwaredllc/byob/pull/322

**Comment by lesmo** [comment]
> This PR fixes this issue 
> https://github.com/malwaredllc/byob/pull/323

It definetely does! I haven't tried to create a payload yet, but it properly builds the containers and boots the web server now

**Comment by admiralyt** [comment]
ran ./setup.sh and it has been installing build dependencies for over 10hours now

**Comment by alhazmy13** [comment]
> ran ./setup.sh and it has been installing build dependencies for over 10hours now

Did you try #323?

**Comment by admiralyt** [comment]
> > ran ./setup.sh and it has been installing build dependencies for over 10hours now
> 
> Did you try #323?

Whats that
