### ISSUE TITLE
Failed to execute script I2L

### ISSUE THREAD

**Issue by QuertinXXX** [malwaredllc/byob#316]
So i have generated an exe file with (python client.py IPv4 port) and when I start it this shows up.
![FAILEDTOEXECUTE](https://user-images.githubusercontent.com/73408568/97095172-72937200-165c-11eb-87dd-ff9cda4ee59f.PNG)

**Comment by Oscaramr** [comment]
I have the same problem did you figure it out?

**Comment by QuertinXXX** [comment]
No i am making my own rat now

W dniu pon., 9.11.2020 o 16:13 Oscaramr <notifications@github.com>
napisał(a):

**Comment by Oscaramr** [comment]
Oh ok
