### ISSUE TITLE
Error web-gui ./startup.sh

### ISSUE THREAD

**Issue by hyped-777** [malwaredllc/byob#324]
Hi! While following your youtube tutorial, i was trying to setup byob web-gui on ubuntu 20, but i found the web-gui  ./startup.sh stuck for hours on the following error:

**Collecting pyinstaller==3.6                                                                                                                                                                  
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies: started**

Another error i found right on begining of  web-gui ./startup.sh

**Running setup.py clean for pyrx
Failed to build pyrx
Installing collected packages: pyrx
    Running setup.py install for pyrx ... error
    ERROR: Command errored out with exit status 1:**
**Building wheels for collected packages: pyrx
  Building wheel for pyrx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pyllx1nt/pyrx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pyllx1nt/pyrx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q_dc8215**   

i'm around this for hours, following tutorials all over and i don't find any solution.
Thank you so much!

**Comment by hyped-777** [comment]
i was testing now on kali, and just got the same issue

**Comment by garsh1** [comment]
These are both common issues. Pyrx is a broken module, ignore that error. Regarding the Installing build dependencies, this can take a while but it will work eventually. Pyinstaller and Docker just don’t play nice I guess.

**Comment by hyped-777** [comment]
Thanks for your quick answer, well in almost 24hours both kali and ubuntu are stuck on this:
Collecting pyinstaller==3.6
Downloading PyInstaller-3.6.tar.gz (3.5 MB)
Installing build dependencies: started

**Comment by hyped-777** [comment]
> These are both common issues. Pyrx is a broken module, ignore that error. Regarding the Installing build dependencies, this can take a while but it will work eventually. Pyinstaller and Docker just don’t play nice I guess.

Really good, and easy fix, we just need to change the txt files there to: ARG PYTHON_VERSION=4.0

but about the pyrx, is there any fix? thanks

**Comment by hyped-777** [comment]
wine: created the configuration directory '/wine'
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".                                                                 
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002                                                                                            
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002                                                          
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002                                                                                                              
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.                                                                      
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.                                                               
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.                                                                      
0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.                                                               
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0                                                                                                   
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0                                                                                                   
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007                                                                                               
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x800736b7                                                                                            
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800736b7                                                          
0050:err:ole:apartment_get_local_server_stream Failed: 0x800736b7                                                                                                              
0050:err:ole:start_rpcss Failed to open RpcSs service                                                                                                                          
0040:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.                                                                      
0040:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.                                                               
0060:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.                                                                      
0060:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.                                                               
0068:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.                                                                      
0068:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.                                                               
Could not find Wine Gecko. HTML rendering will be disabled.                                                                                                                    
00b0:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142                                          
002c:err:setupapi:SetupDiInstallDevice Failed to start service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1114.                                                       
wine: configuration in L"/wine" has been updated.                                                                                                                              
Using winetricks 20200412-next - sha256sum: 8e180b094e9cde430a89ee98ca63855bfacf3479b030b9bd4fe24bbd261ee04a with wine-5.19 (Staging) and WINEARCH=win32                       
Executing w_do_call win7
Executing mkdir -p /
Executing load_win7 
Executing wine winecfg -v win7
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/wine terminate
------------------------------------------------------
+ echo core dev exe lib path pip tcltk tools
+ wget -nv https://www.python.org/ftp/python/4.0/win32/core.msi                                                                                                                
https://www.python.org/ftp/python/4.0/win32/core.msi:                                                                                                                          
2020-11-11 18:47:25 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i core.msi /qb TARGETDIR=C:/Python37                                                                                                                           
0044:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".                                                                 
0098:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142                                          
+ rm core.msi                                                                                                                                                                  
rm: cannot remove 'core.msi': No such file or directory                                                                                                                        
+ wget -nv https://www.python.org/ftp/python/4.0/win32/dev.msi                                                                                                                 
https://www.python.org/ftp/python/4.0/win32/dev.msi:                                                                                                                           
2020-11-11 18:47:28 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i dev.msi /qb TARGETDIR=C:/Python37                                                                                                                            
+ rm dev.msi                                                                                                                                                                   
rm: cannot remove 'dev.msi': No such file or directory                                                                                                                         
+ wget -nv https://www.python.org/ftp/python/4.0/win32/exe.msi                                                                                                                 
https://www.python.org/ftp/python/4.0/win32/exe.msi:                                                                                                                           
2020-11-11 18:47:29 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i exe.msi /qb TARGETDIR=C:/Python37                                                                                                                            
+ rm exe.msi                                                                                                                                                                   
rm: cannot remove 'exe.msi': No such file or directory                                                                                                                         
+ wget -nv https://www.python.org/ftp/python/4.0/win32/lib.msi                                                                                                                 
https://www.python.org/ftp/python/4.0/win32/lib.msi:                                                                                                                           
2020-11-11 18:47:29 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i lib.msi /qb TARGETDIR=C:/Python37                                                                                                                            
+ rm lib.msi                                                                                                                                                                   
rm: cannot remove 'lib.msi': No such file or directory                                                                                                                         
+ wget -nv https://www.python.org/ftp/python/4.0/win32/path.msi                                                                                                                
https://www.python.org/ftp/python/4.0/win32/path.msi:                                                                                                                          
2020-11-11 18:47:30 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i path.msi /qb TARGETDIR=C:/Python37                                                                                                                           
+ rm path.msi                                                                                                                                                                  
rm: cannot remove 'path.msi': No such file or directory                                                                                                                        
+ wget -nv https://www.python.org/ftp/python/4.0/win32/pip.msi                                                                                                                 
https://www.python.org/ftp/python/4.0/win32/pip.msi:                                                                                                                           
2020-11-11 18:47:31 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i pip.msi /qb TARGETDIR=C:/Python37                                                                                                                            
+ rm pip.msi                                                                                                                                                                   
rm: cannot remove 'pip.msi': No such file or directory                                                                                                                         
+ wget -nv https://www.python.org/ftp/python/4.0/win32/tcltk.msi                                                                                                               
https://www.python.org/ftp/python/4.0/win32/tcltk.msi:                                                                                                                         
2020-11-11 18:47:32 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i tcltk.msi /qb TARGETDIR=C:/Python37                                                                                                                          
+ rm tcltk.msi                                                                                                                                                                 
rm: cannot remove 'tcltk.msi': No such file or directory                                                                                                                       
+ wget -nv https://www.python.org/ftp/python/4.0/win32/tools.msi                                                                                                               
https://www.python.org/ftp/python/4.0/win32/tools.msi:                                                                                                                         
2020-11-11 18:47:33 ERROR 404: Not Found.                                                                                                                                      
+ wine msiexec /i tools.msi /qb TARGETDIR=C:/Python37                                                                                                                          
+ rm tools.msi                                                                                                                                                                 
rm: cannot remove 'tools.msi': No such file or directory                                                                                                                       
The command '/bin/sh -c set -x     && winetricks win7     && for msifile in `echo core dev exe lib path pip tcltk tools`; do         wget -nv "https://www.python.org/ftp/python/$PYTHON_VERSION/win32/${msifile}.msi";         wine msiexec /i "${msifile}.msi" /qb TARGETDIR=C:/Python37;         rm ${msifile}.msi;     done     && cd /wine/drive_c/Python37     && echo 'wine '\''C:\Python37\python.exe'\'' "$@"' > /usr/bin/python     && echo 'wine '\''C:\Python37\Scripts\easy_install.exe'\'' "$@"' > /usr/bin/easy_install     && echo 'wine '\''C:\Python37\Scripts\pip.exe'\'' "$@"' > /usr/bin/pip     && echo 'wine '\''C:\Python37\Scripts\pyinstaller.exe'\'' "$@"' > /usr/bin/pyinstaller     && echo 'wine '\''C:\Python37\Scripts\pyupdater.exe'\'' "$@"' > /usr/bin/pyupdater     && echo 'assoc .py=PythonScript' | wine cmd     && echo 'ftype PythonScript=c:\Python37\python.exe "%1" %*' | wine cmd     && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done     && chmod +x /usr/bin/python /usr/bin/easy_install /usr/bin/pip /usr/bin/pyinstaller /usr/bin/pyupdater     && (pip install -U pip || true)     && rm -rf /tmp/.wine-*' returned a non-zero code: 1
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/kali/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    db = SQLAlchemy(app)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 716, in __init__
    self.Model = self.make_declarative_base(model_class, metadata)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 798, in make_declarative_base
    model.query_class = self.Query
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
    _add_attribute(cls, key, value)
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/base.py", line 802, in _add_attribute
    type.__setattr__(cls, key, value)
TypeError: can't apply this __setattr__ to DefaultMeta object

**Comment by alhazmy13** [comment]
Try this PR https://github.com/malwaredllc/byob/issues/325
