### ISSUE TITLE
don't install pyinstaller in startup.sh

### ISSUE THREAD

**Issue by esiquiel** [malwaredllc/byob#325]
Hi, I'm trying to start the web-gui and when I run: 
sudo ./startup.sh
everything runs correctly until I try to install pyinstaller, when in fact it is already installed. When trying to install this package it never really installs I've been waiting for more than 30 minutes for just this package to be "installed". The last thing he showed me is this and since there he does nothing else:

```
Step 18/25 : RUN /usr/bin/pip install pyinstaller==$PYINSTALLER_VERSION
 ---> Running in 01293fa7a713
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0098:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
Collecting pyinstaller==3.6
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies: started
```
From this moment it does nothing. I'm using Linux Mint, I have Docker installed and working properly, my Python version is Python 3.6.9 I already did sudo apt update && apt upgrade, and installed the new versions of python3 ...

Some help?
Thanks.

**Comment by Csicso64a** [comment]
I have this issue too. And i let the program run for 6,5 hours and nothing happened.

**Comment by alhazmy13** [comment]
Try this PR #323

**Comment by fireFerry** [comment]
dont use sudo though, just normal ./startup.sh
