### ISSUE TITLE
BYOB terminal app

### ISSUE THREAD

**Issue by Xsnipe** [malwaredllc/byob#326]
Recently I have been having issues with installing and using the web-gui but the terminal application seems to work fine. But I have a couple noob questions.
Is there a way to check the amount of bots connected to your server in the terminal app?
How do I generate a payload for Linux devices that when ran will add them to by botnet?
Say I wanted to install the miner module on every bot in my botnet would I use the command `broadcast miner -url -usr -pass`?

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.
