### ISSUE TITLE
Web gui not showing

### ISSUE THREAD

**Issue by Zvampen04** [malwaredllc/byob#328]
Hi, I followed along to your setup tutorial, but when I open the http://0.0.0.0:5000/ I only get to your home side. Do you know what this is/what am I doing wrong? 
I'm also getting a "warning: This is a development server. Do not use it in production deployment." Does that have anything to do with it?

**Comment by Zvampen04** [comment]
![Uploading C80DBE22-3240-45BE-961F-1A263C084813.jpeg…]()

**Comment by Zvampen04** [comment]
![Uploading B1E69D90-3F3B-48C4-B591-CEF3BC33734D.jpeg…]()

**Comment by Zvampen04** [comment]
![IMG_1454](https://user-images.githubusercontent.com/36170366/99432837-9fa60e00-2904-11eb-9da8-3964847e3e96.jpg)

**Comment by Zvampen04** [comment]
![IMG_1453](https://user-images.githubusercontent.com/36170366/99432874-aaf93980-2904-11eb-9cc7-21f9a14d22c9.jpg)

**Comment by onlinejudge95** [comment]
You need to register and login as an authenticated user.

Also, the message you are seeing on the terminal is an indication that the flask server is up and running in production mode. NOt to be worried about it if you are running your C2 server locally on your system.

**Comment by Zvampen04** [comment]
okej, so I managed to get it working, but when trying to get the script setup an another machine the setup just stops at step 12/12 18/25. Been waiting for this for 2 hours, so maybe its a problem with by computer? 
I'm sorry for asking these noob questions, but i just started EH'ing and barely even know how to use linux yet

**Comment by Zvampen04** [comment]
![IMG_1458](https://user-images.githubusercontent.com/36170366/99910137-4f53f500-2ce4-11eb-9606-87ac3294ee82.jpg)

**Comment by deeshirazi** [comment]
dude at least you came so long as i see in the pictures! I am stuck at the begining at /boyb/web-gui and i dont really know what to do! My system can´t navigate to the /byob file...
I hope someone takes his/her time and explain for a noob like me! hahaha Good luck to you too bro

**Comment by fireFerry** [comment]
You can join the Discord server for some support, @Zvampen04 you need to clone a new version of byob.
