### ISSUE TITLE
After trying to use a kaylogger, the connection drops

### ISSUE THREAD

**Issue by softd1sk** [malwaredllc/byob#332]
[ 3 @ C:\Users\39340\Desktop ]>keylogger run
Session init exception: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte

[-] Failed Connection: <PUBBLIC IP>

None Session 3 disconnected

**Comment by LandetCoronet82** [comment]
i have it too but with miner stop then all conection drops and miner is still working 
abort not show utf-8 error but task is still runinng
