### ISSUE TITLE
uninstall byob?

### ISSUE THREAD

**Issue by S3Cd3d** [malwaredllc/byob#334]
anyone know how to uninstall byob because i made a mistake when installing everything as i had no space on my storage left.

**Comment by 11TStudio** [comment]
I guess you use Linux. 
If so run this command: `rm -fr the/path/to/byob`
If you would also uninstall python: 
(debian)`sudo apt purge python`
(ym) `yum remove python`
and this should already wipe the most of the space free.

**Comment by S3Cd3d** [comment]
thanks this helped :D
