### ISSUE TITLE
Can't Create Executables

### ISSUE THREAD

**Issue by dpogreba** [malwaredllc/byob#335]
I religiously followed (a few) youtube videos and successfully got BYOB Web gui running. I can create a python payload, but I noticed that when creating an executable, it either times out or never creates. On my Pi, I found this error on the terminal output--

![Untitled](https://user-images.githubusercontent.com/59986662/101298978-9ca88a00-37ed-11eb-8bd5-a937384f8915.png)

**Comment by AustinLeath** [comment]
getting this error as well

**Comment by fireFerry** [comment]
compile the payload with pyinstaller manually

**Comment by dpogreba** [comment]
> compile the payload with pyinstaller manually

Ok so I'm going to play the "Freshman" card


... how would I do that?

**Comment by fireFerry** [comment]
You can read the wiki here: https://pyinstaller.readthedocs.io,
or join the Discord server, we're there to happily support you!

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.

**Comment by AustinLeath** [comment]
This issue was created because it is a bug

**Comment by dpogreba** [comment]
> This issue was created because it is a bug

A major one too, since it seemed very common even in the discord channel

**Comment by fireFerry** [comment]
It's mostly because people install docker with `apt-get install docker.io`, which is outdated and will most likely not work.

**Comment by ItzTazzaYT** [comment]
@fireFerry So what should people install to fix this? instead of apt-get install docker.io

**Comment by fireFerry** [comment]
> @fireFerry So what should people install to fix this? instead of apt-get install docker.io

@ItzTazzaYT https://docs.docker.com/engine/install

**Comment by ItzTazzaYT** [comment]
LEGEND! ill try that tomorrow I don't have time rn to install.
