### ISSUE TITLE
exe error

### ISSUE THREAD

**Issue by RadicHUB** [malwaredllc/byob#336]
C:\Documents\byob-master\byob>python client.py IP PORT --freeze

88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'

[>] Modules
        Adding modules...  (4 modules added to client)

[>] Imports
        Adding imports... (32 imports from 4 modules)

[>] Payload
        Uploading payload...  (hosting payload at: http://IP:PORT///payloads/mVy.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://IP:PORT///stagers/mVy.py)

[>] Dropper
        Writing dropper...  (347 bytes written to byob_mVy.py)
        Compiling executable...
 128 INFO: PyInstaller: 4.1
128 INFO: Python: 3.7.9
128 INFO: Platform: Windows-10-10.0.19041-SP0
131 INFO: wrote C:\Documents\byob-master\byob\mVy.spec
137 INFO: UPX is not available.
139 INFO: Extending PYTHONPATH with paths
['C:\\Documents\\byob-master\\byob\\modules\\payloads',
 'C:\\Documents\\byob-master\\byob']
157 INFO: checking Analysis
157 INFO: Building Analysis because Analysis-00.toc is non existent
158 INFO: Initializing module dependency graph...
166 INFO: Caching module graph hooks...
202 INFO: Analyzing base_library.zip ...
2623 INFO: Processing pre-find module path hook distutils from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2624 INFO: distutils: retargeting to non-venv dir 'C:\\Documents\\byob-master\\byob\\lib'
4007 INFO: Caching module dependency graph...
4213 INFO: running Analysis Analysis-00.toc
4217 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Documents\byob-master\byob\python.exe
4346 INFO: Analyzing C:\Documents\byob-master\byob\modules\payloads\mVy.py
6423 INFO: Analyzing hidden import 'pkg_resources.py2_warn'
6556 INFO: Processing module hooks...
6556 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
6558 INFO: Excluding import of doctest from module difflib
6558 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
6560 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
6561 INFO: Excluding import of lib2to3.refactor from module distutils.util
6561 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
6806 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
6808 INFO: Excluding import of doctest from module heapq
6808 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
7223 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
7225 INFO: Excluding import of test.support from module multiprocessing.util
7225 INFO: Excluding import of test from module multiprocessing.util
7225 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
7226 INFO: Excluding import of argparse from module pickle
7226 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
7848 INFO: Processing pre-safe import module hook win32com from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
8125 WARNING: Hidden import "pkg_resources.markers" not found!
8126 INFO: Excluding import of __main__ from module pkg_resources
8126 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
8128 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
8129 INFO: Loading module hook 'hook-xml.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
8195 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks'...
8500 INFO: checking Tree
8500 INFO: Building Tree because Tree-00.toc is non existent
8500 INFO: Building Tree Tree-00.toc
8642 INFO: checking Tree
8642 INFO: Building Tree because Tree-01.toc is non existent
8642 INFO: Building Tree Tree-01.toc
8826 INFO: checking Tree
8826 INFO: Building Tree because Tree-02.toc is non existent
8826 INFO: Building Tree Tree-02.toc
8835 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9326 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9815 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10240 INFO: Looking for ctypes DLLs
10366 INFO: Analyzing run-time hooks ...
10370 INFO: Including run-time hook 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
10373 INFO: Including run-time hook 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
10374 INFO: Including run-time hook 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
10376 INFO: Including run-time hook 'C:\\Documents\\byob-master\\byob\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
10385 INFO: Looking for dynamic libraries
11079 INFO: Looking for eggs
11079 INFO: Using Python library C:\Documents\byob-master\byob\python37.dll
11079 INFO: Found binding redirects:
[]
11085 INFO: Warnings written to C:\Documents\byob-master\byob\build\mVy\warn-mVy.txt
11150 INFO: Graph cross-reference written to C:\Documents\byob-master\byob\build\mVy\xref-mVy.html
11164 INFO: checking PYZ
11164 INFO: Building PYZ because PYZ-00.toc is non existent
11164 INFO: Building PYZ (ZlibArchive) C:\Documents\byob-master\byob\build\mVy\PYZ-00.pyz
12010 INFO: Building PYZ (ZlibArchive) C:\Documents\byob-master\byob\build\mVy\PYZ-00.pyz completed successfully.
12024 INFO: checking PKG
12025 INFO: Building PKG because PKG-00.toc is non existent
12025 INFO: Building PKG (CArchive) PKG-00.pkg
14660 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
14664 INFO: Bootloader C:\Documents\byob-master\byob\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw.exe
14664 INFO: checking EXE
14664 INFO: Building EXE because EXE-00.toc is non existent
14664 INFO: Building EXE from EXE-00.toc
14669 INFO: Updating manifest in C:\Documents\byob-master\byob\build\mVy\runw.exe.6h_yh9ma
14670 INFO: Updating resource type 24 name 1 language 0
14680 INFO: Appending archive to EXE C:\Documents\byob-master\byob\dist\mVy.exe
14703 INFO: Building EXE from EXE-00.toc completed successfully.
(8,955,583 bytes saved to file: /Documents/byob-master/byob\dist\mVy.exe)

**Comment by fireFerry** [comment]
You will have to replace IP and PORT by your actual ip and port...
