### ISSUE TITLE
Can't execute Python on victim machine

### ISSUE THREAD

**Issue by dpogreba** [malwaredllc/byob#338]
Trying to execute a python payload on a Kali Linux "Lab" environment that I have, generated from my BYOB Web Gui control panel, and I'm presented with this error (regardless if root or not) 

![image](https://user-images.githubusercontent.com/59986662/101847586-cbd23a80-3b10-11eb-8fa8-0262bb743487.png)

**Comment by projectintel-anon** [comment]
I have the same issue here. Not sure why it won't work :/

**Comment by garsh1** [comment]
Have you port forwarded? You need to forward ports 1337 - 1339.

**Comment by DrunkenMoose** [comment]
> Have you port forwarded? You need to forward ports 1337 - 1339.

I get the same error and I tried to open the ports. I have a main router (I live in a shared house) and my own router. I can access both. I tried to open 1337-1339 on both routers, but still got the same error. Could you maybe explain how you did it? I can see that it is listening on these ports, but I don't know if they are open. Maybe I'm using the wrong IP adress or something.
Thanks!

**Comment by JudeHoog** [comment]
First off the Kali firewall will probably be blocking those ports. And the remote machine may not have updated python. (Also remember to close these ports when ur done its a HUGE security risk)
