### ISSUE TITLE
Can't generate an .exe payload (GUI Kali Linux)

### ISSUE THREAD

**Issue by Bobert2732** [malwaredllc/byob#339]
Hi, I did everything I had to do, everything works fine, but, there is a problem, when I go to create an .exe payload for windows (GUI) it seems to work but I waited for like an hour and nothing happend, I refreshed the page and nothing. I am kinda new with this platform and I don't know what can cause this problem, can someone help me out?

**Comment by wrddes** [comment]
i have the same problem and I too cant find a solution

**Comment by wrddes** [comment]
but in the terminal it say it cant find the win32 image locally i hope this helps someone to farther troubleshoot 
PS: I was using docker

**Comment by Bobert2732** [comment]
I can only generate from terminal but only .py, and I can't move it to GUI, in GUI I can't even generate .py payloads.

**Comment by fireFerry** [comment]
You should join the Discord for support.

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.
