### ISSUE TITLE
C:\Program' is not recognized as an internal or external command, operable program or batch file Error

### ISSUE THREAD

**Issue by samjoe46** [malwaredllc/byob#342]
I keep getting this error when it compiles the executable in client.py if there is a fix I would love to know it. 
![Screenshot 2020-12-18 163231](https://user-images.githubusercontent.com/74482948/102663369-b8e1ea80-414e-11eb-9415-14364d935885.png)

**Comment by TechproTaz** [comment]
you should try to run it in kali linux

**Comment by fireFerry** [comment]
Yeah byob isn't supported on Windows

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.
