### ISSUE TITLE
Cant connect to web gui

### ISSUE THREAD

**Issue by s1lo11** [malwaredllc/byob#343]
It says it is running fine but when I enter the address it says it refused to connect or has moved. It is running on a vps and I am tryna connect on my main machine may be why but I only have ssh for the vps? help>

**Comment by fireFerry** [comment]
Are all the the ports open?

**Comment by s1lo11** [comment]
yeah

**Comment by fireFerry** [comment]
which address are you putting in? and are the ports open on portcheckers.com?

**Comment by KhorneDevilsWare** [comment]
I have the same problem. I edited the files to my public IP and the new port and still cannot connect

**Comment by JudeHoog** [comment]
Make sure it's running on the machine use `top` to see what is running and make sure you have correct ip routing

**Comment by garsh1** [comment]
Use portcheckers.com, if it says closed it’s a networking issue. If it says open it’s a software issue.

**Comment by KhorneDevilsWare** [comment]
The XMR miner is broken as well

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by fireFerry** [comment]
> The XMR miner is broken as well

@KhorneDevilsWare you will need to have cmake installed for the xmr miner to work.
`sudo apt install cmake`

**Comment by malwaredllc** [comment]
`cmake` install is now included in `startup.sh` per #384 which fixes this issue
