### ISSUE TITLE
Miner not starting

### ISSUE THREAD

**Issue by shizdev** [malwaredllc/byob#344]
I am running byob on a vps, made a new python payload, executed it on my pc to try it and tried starting the miner and it's saying new process started in the top right but on my pc nothing's happening. antivirus is off, firewall is off too but it's just not starting.

**Comment by clint259** [comment]
> I am running byob on a vps, made a new python payload, executed it on my pc to try it and tried starting the miner and it's saying new process started in the top right but on my pc nothing's happening. antivirus is off, firewall is off too but it's just not starting.

do you know of any other good c/c apps ?

**Comment by shizdev** [comment]
> I am running byob on a vps, made a new python payload, executed it on my pc to try it and tried starting the miner and it's saying new process started in the top right but on my pc nothing's happening. antivirus is off, firewall is off too but it's just not starting.

ok i got the miner to start but it's not mining. just using 0% cpu and gpu and wont show up on the pool
