### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by dopuke** [malwaredllc/byob#345]
I tried to register like 200 times with random username like "OTg3NjU0MzIx" or "MTIzNDU2Nzg5" and still cannot register, I get this message error every time. please help me
![image](https://user-images.githubusercontent.com/63050953/103178049-e251f300-487f-11eb-9233-cd4c41def06e.png)

**Comment by fireFerry** [comment]
Delete database.db file

**Comment by dopuke** [comment]
I get error 500 so i refresh the page, go to register again, put a random name and still same error
![image](https://user-images.githubusercontent.com/63050953/103577949-00e66880-4ed6-11eb-9868-04e96dc49928.png)

**Comment by fireFerry** [comment]
turn off server, delete database.db, run `sudo ./startup.sh`

**Comment by dopuke** [comment]
IT WORKKKED!!!!, when I register I get the 500 error but it actually work, idk why thx so much !!!
