### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by MP3Martin** [malwaredllc/byob#347]
When i click create payload for windows (executable), it starts spamming errors in console

I have windows 10, am using Ubuntu for windows

![image](https://user-images.githubusercontent.com/60501493/103529247-9d344f00-4e85-11eb-8f47-e07948c88fb5.png)

**Comment by MP3Martin** [comment]
I think its copy of #339 but i need help

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.
