### ISSUE TITLE
Some what fix for pyrx 

### ISSUE THREAD

**Issue by Getters219** [malwaredllc/byob#348]
I have had some luck with running it on kali linux by using command

CD byob
CD byob 
Nano requirements. Txt 
Edit out 
Git+https://github.com/jtgrassie/pyrx.git#egg=pyrx
Save changes
And then run
To use the web-gui
Again 
CD byob
CD Web-gui
Nano requirements. Txt
Edit out git+https://github.com/jtgrassie/pyrx.git#egg=pryx
Exit
Then run using ./startup.sh

Hope this helps

**Comment by garsh1** [comment]
Uhhh what?

**Comment by Jamieplayz29** [comment]
he literally explained this in his tutorial video: https://www.youtube.com/watch?v=uVyniPrTzuk
