### ISSUE TITLE
Exception in api.routes.payload.payload_generate: Timeout or out of memory

### ISSUE THREAD

**Issue by yajat124** [malwaredllc/byob#353]
can someone help me when i try to generate a payload it shows.
Exception in api.routes.payload.payload_generate: Timeout or out of memory

**Comment by callowaysutton** [comment]
I'm having the same issue by running through WSL, I think it might be because Windows binaries can only be made when the server is running on Windows

**Comment by sleezeh** [comment]
ho lo stesso problema quanso provo a fare la payload windows

**Comment by sleezeh** [comment]
i have the same problem when i try to do the windows payload

**Comment by StiliyanKushev** [comment]
Same issue.

**Comment by nikoli0218** [comment]
How is this issue closed with no response or fix????
