### ISSUE TITLE
DOS/DDOS Attack From BYOB

### ISSUE THREAD

**Issue by RocketNinja15** [malwaredllc/byob#357]
Allows you to preform DDOS/DOS attacks from your botnet, helping people detect outgoing DDOS attacks on their network. Would support:
ICMP
UDP 
TCP
SYN
DNS
Get/Post
POD

**Comment by garsh1** [comment]
You realize that there’s a reason this was never added to begin with, right?

**Comment by malwaredllc** [comment]
No, this project is for educational purposes only, I don't intend to weaponize it.

**Comment by RocketNinja15** [comment]
@malwaredllc this wasn't meant to become weaponised... i just thought is was a good idea, as you could detect if your network was compromised
