### ISSUE TITLE
Failed to build a wheel for numpy

### ISSUE THREAD

**Issue by debian-user-france1** [malwaredllc/byob#360]
pip fails by building a wheel for numpy. There is a error message that is tooo long to post here.

Here a piece:
  error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DCYTHON_SMALL_CODE= -Inumpy/core/include -Ibuild/src.linux-x86_64-3.9/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.9 -Ibuild/src.linux-x86_64-3.9/numpy/core/src/private -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.9/numpy/core/src/private -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.9/numpy/core/src/private -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.9/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.9/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for numpy
  Running setup.py clean for numpy
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jt12km6a/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jt12km6a/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-jt12km6a/numpy
  Complete output (10 lines):
  Running from numpy source directory.
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  ----------------------------------------
  ERROR: Failed cleaning build dir for numpy

I think that the whole error message x100 longer is. But that is the actual error that exited with 1

I tried with a Raspberry Pi (Ubuntu for IoT) and Parrot Security Systems. Both failed

using following command:
sudo ./startup.sh   or
sudo pip3 install -r requirements.txt

fails also with root
It looks that it failed with compiling from C to code

**Comment by debian-user-france1** [comment]
Sorry, I didn't wrote bold or something else. GitHub interpreted two start as *bold*

**Comment by debian-user-france1** [comment]
or _
cursive_
two underlines bold, two stars cursive. Thats a rule

**Comment by debian-user-france1** [comment]
_bold_

**Comment by debian-user-france1** [comment]
*bold*

doesn't works, sh of

**Comment by debian-user-france1** [comment]
─[✗]─[root@parrot]─[/home/france1/byob/web-gui]
└──╼ #pip install numpy
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.4)
┌─[root@parrot]─[/home/france1/byob/web-gui]
└──╼ #




already installed?!




┌─[✗]─[root@parrot]─[/home/france1/byob/web-gui]
└──╼ #pip uninstall numpy
Found existing installation: numpy 1.19.4
Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'numpy'. No files were found to uninstall.



bad installation

another time failed
cleaning pycache:

git clean -xdf
Lösche .log
Lösche buildyourownbotnet/__pycache__/
Lösche buildyourownbotnet/api/__pycache__/
Lösche buildyourownbotnet/api/files/__pycache__/
Lösche buildyourownbotnet/api/payload/__pycache__/
Lösche buildyourownbotnet/api/session/__pycache__/
Lösche buildyourownbotnet/core/__pycache__/
Lösche buildyourownbotnet/database.db
Lösche buildyourownbotnet/errors/__pycache__/
Lösche buildyourownbotnet/main/__pycache__/
Lösche buildyourownbotnet/modules/__pycache__/
Lösche buildyourownbotnet/users/__pycache__/



another time failed

**Comment by malwaredllc** [comment]
This issue is related to the numpy library and your current machine/environment, not BYOB. Sorry, I would recommend googling the error message and going from there.
