### ISSUE TITLE
Error [Errno 2] generating .exe payload

### ISSUE THREAD

**Issue by thisisme-url** [malwaredllc/byob#362]
The terminal shows these two lines and does nothing after that: 

b'29634 INFO: Building EXE from EXE-00.toc completed successfully.'
Exception in api.routes.payload.payload_generate: [Errno 2] No such file or directory: '/home/username/byob/web-gui/buildyourownbotnet/output/vitalyklitschko/src/dist/windows/byob_win_x32_iFy.exe'

I have searched everywhere and not found anything about this error linked to byob.

Generating a python payload works though.

**Comment by artilate** [comment]
The best thing to do is by downloading the python payload first, then using pyinstaller to build the executable either on a windows machine or linux machine.

**Comment by malwaredllc** [comment]
Windows exe generation has been fixed in #384
