### ISSUE TITLE
after installing or starting the ./startup.sh I get this ideas?

### ISSUE THREAD

**Issue by PixelsDE** [malwaredllc/byob#366]
Running BYOB app startup...
Confirmed Python is installed.
Confirmed Docker is installed.
Installing Python packages...
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/packaging/markers.py", line 299, in __init__
    self._markers = _coerce_parse_result(MARKER.parseString(marker))
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found 's'  (at char 21), (line:1, col:22)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/commands/install.py", line 287, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 361, in get_requirements
    req_to_add = install_req_from_parsed_requirement(
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/req/constructors.py", line 458, in install_req_from_parsed_requirement
    req = install_req_from_line(
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/req/constructors.py", line 391, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/req/constructors.py", line 296, in parse_req_from_line
    markers = Marker(markers_as_string)
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/packaging/markers.py", line 304, in __init__
    raise InvalidMarker(err_str)
pip._vendor.packaging.markers.InvalidMarker: Invalid marker: "sys.platform=='win32's", parse error at 's'
Building Docker images - this will take a while, please be patient...
Sending build context to Docker daemon  35.33kB
Step 1/12 : FROM ubuntu:20.04
 ---> f63181f19b2f
Step 2/12 : SHELL ["/bin/bash", "-i", "-c"]
 ---> Using cache
 ---> 736fc2b360e0
Step 3/12 : ARG PYTHON_VERSION=3.7.9
 ---> Using cache
 ---> 37ee4df81f84
Step 4/12 : ARG PYINSTALLER_VERSION=3.6
 ---> Using cache
 ---> a7f4be430363
Step 5/12 : ENV PYPI_URL=https://pypi.python.org/
 ---> Using cache
 ---> 7f92869c9b31
Step 6/12 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Using cache
 ---> e64c9150b0e0
Step 7/12 : ENV PYENV_VERSION=${PYTHON_VERSION}
 ---> Using cache
 ---> 796da0eb8034
Step 8/12 : COPY entrypoint-linux.sh /entrypoint.sh
 ---> Using cache
 ---> 538e05b3cde5
Step 9/12 : RUN     set -x     && apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         curl         wget         git         libbz2-dev         libreadline-dev         libsqlite3-dev         libssl-dev         zlib1g-dev         libffi-dev         libgdbm-dev         uuid-dev         upx     && mkdir openssl     && cd openssl     && wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz     && tar -xzvf openssl-1.1.1h.tar.gz     && cd openssl-1.1.1h     && ./config --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib     && make     && make install     && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc     && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc     && source ~/.bashrc     && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash     && echo 'eval "$(pyenv init -)"' >> ~/.bashrc     && source ~/.bashrc     && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION     && pyenv global $PYTHON_VERSION     && pip install --upgrade pip     && pip install pyinstaller==$PYINSTALLER_VERSION     && mkdir /src/     && chmod +x /entrypoint.sh
 ---> Using cache
 ---> 3b1d7de14c40
Step 10/12 : VOLUME /src/
 ---> Using cache
 ---> 3ff22bc1c0d9
Step 11/12 : WORKDIR /src/
 ---> Using cache
 ---> dcd30426196d
Step 12/12 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 64c8b38151aa
Successfully built 64c8b38151aa
Successfully tagged nix-amd64:latest
Sending build context to Docker daemon  35.33kB
Step 1/12 : FROM i386/ubuntu:18.04
 ---> 066d80ca67f9
Step 2/12 : SHELL ["/bin/bash", "-i", "-c"]
 ---> Using cache
 ---> eb2a0b16112c
Step 3/12 : ARG PYTHON_VERSION=3.7.9
 ---> Using cache
 ---> 6f23fab960b9
Step 4/12 : ARG PYINSTALLER_VERSION=3.6
 ---> Using cache
 ---> aa643808593f
Step 5/12 : ENV PYPI_URL=https://pypi.python.org/
 ---> Using cache
 ---> b966301ad967
Step 6/12 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Using cache
 ---> 6135ada8540d
Step 7/12 : ENV PYENV_VERSION=${PYTHON_VERSION}
 ---> Using cache
 ---> ff90335e2add
Step 8/12 : COPY entrypoint-linux.sh /entrypoint.sh
 ---> Using cache
 ---> da7703f635cf
Step 9/12 : RUN     set -x     && apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         curl         wget         git         libbz2-dev         libreadline-dev         libsqlite3-dev         libssl-dev         zlib1g-dev         libffi-dev         libgdbm-dev         uuid-dev         upx     && mkdir openssl     && cd openssl     && wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz     && tar -xzvf openssl-1.1.1h.tar.gz     && cd openssl-1.1.1h     && ./Configure linux-generic32 --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib     && make     && make install     && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc     && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc     && source ~/.bashrc     && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash     && echo 'eval "$(pyenv init -)"' >> ~/.bashrc     && source ~/.bashrc     && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION     && pyenv global $PYTHON_VERSION     && pip install --upgrade pip     && pip install pyinstaller==$PYINSTALLER_VERSION     && mkdir /src/     && chmod +x /entrypoint.sh
 ---> Using cache
 ---> 3ba58b37403f
Step 10/12 : VOLUME /src/
 ---> Using cache
 ---> 11a39fa7bda2
Step 11/12 : WORKDIR /src/
 ---> Using cache
 ---> 2c88cb91a4d5
Step 12/12 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 3cbda6a10985
Successfully built 3cbda6a10985
Successfully tagged nix-i386:latest
Sending build context to Docker daemon  35.33kB
Step 1/30 : FROM ubuntu:20.04
 ---> f63181f19b2f
Step 2/30 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 47a3967368ef
Step 3/30 : ARG WINE_VERSION=winehq-stable
 ---> Using cache
 ---> 32cbfa0a46db
Step 4/30 : ARG PYTHON_VERSION=3.7.9
 ---> Using cache
 ---> 2f3994e2eb05
Step 5/30 : ARG PYINSTALLER_VERSION=3.6
 ---> Using cache
 ---> 07f579b998e5
Step 6/30 : RUN set -x     && dpkg --add-architecture i386     && apt-get update -qy     && apt-get install --no-install-recommends -qfy gpg-agent rename apt-transport-https software-properties-common winbind cabextract wget curl zip unzip xvfb xdotool x11-utils xterm     && wget -nv https://dl.winehq.org/wine-builds/winehq.key     && apt-key add winehq.key     && add-apt-repository 'https://dl.winehq.org/wine-builds/ubuntu/'     && apt-get update -qy     && apt-get install --install-recommends -qfy $WINE_VERSION     && apt-get clean     && rm -rf /var/lib/apt/lists/*     && wget -nv https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks     && chmod +x winetricks     && mv winetricks /usr/local/bin
 ---> Using cache
 ---> 8bdff778ffd4
Step 7/30 : RUN mkdir -p /usr/share/wine/gecko
 ---> Using cache
 ---> 47aa46a89716
Step 8/30 : RUN curl -o /usr/share/wine/gecko/wine_gecko-2.47-x86.msi http://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86.msi
 ---> Using cache
 ---> 9ebc59748381
Step 9/30 : ENV WINEARCH win32
 ---> Using cache
 ---> 69c792f3ba0c
Step 10/30 : ENV WINEDEBUG fixme-all
 ---> Using cache
 ---> dbaef1bd71ab
Step 11/30 : ENV WINEPREFIX /wine
 ---> Using cache
 ---> 122683be1bdd
Step 12/30 : ENV DISPLAY :0
 ---> Using cache
 ---> 183d60db3497
Step 13/30 : RUN set -x     && echo 'Xvfb $DISPLAY -screen 0 1024x768x24 &' >> /root/.bashrc
 ---> Using cache
 ---> 7ca0a34884ca
Step 14/30 : RUN set -x     && winetricks -q win10
 ---> Using cache
 ---> 7ead1f4118e3
Step 15/30 : ENV PYPI_URL=https://pypi.python.org/
 ---> Using cache
 ---> 0fc6c6279634
Step 16/30 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Using cache
 ---> 69814a711885
Step 17/30 : RUN set -x     && for msifile in `echo core dev exe lib path pip tcltk tools`; do         wget -nv "https://www.python.org/ftp/python/$PYTHON_VERSION/win32/${msifile}.msi";         wine msiexec /i "${msifile}.msi" /qb TARGETDIR=C:/Python37;         rm ${msifile}.msi;     done     && cd /wine/drive_c/Python37     && echo 'wine '\''C:\Python37\python.exe'\'' "$@"' > /usr/bin/python     && echo 'wine '\''C:\Python37\Scripts\easy_install.exe'\'' "$@"' > /usr/bin/easy_install     && echo 'wine '\''C:\Python37\Scripts\pip.exe'\'' "$@"' > /usr/bin/pip     && echo 'wine '\''C:\Python37\Scripts\pyinstaller.exe'\'' "$@"' > /usr/bin/pyinstaller     && echo 'wine '\''C:\Python37\Scripts\pyupdater.exe'\'' "$@"' > /usr/bin/pyupdater     && echo 'assoc .py=PythonScript' | wine cmd     && echo 'ftype PythonScript=c:\Python37\python.exe "%1" %*' | wine cmd     && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done     && chmod +x /usr/bin/python /usr/bin/easy_install /usr/bin/pip /usr/bin/pyinstaller /usr/bin/pyupdater     && (pip install -U pip || true)     && rm -rf /tmp/.wine-*
 ---> Using cache
 ---> b260131e92ad
Step 18/30 : ENV W_DRIVE_C=/wine/drive_c
 ---> Using cache
 ---> f846aafc9569
Step 19/30 : ENV W_WINDIR_UNIX="$W_DRIVE_C/windows"
 ---> Using cache
 ---> e58a237b2c6c
Step 20/30 : ENV W_SYSTEM_DLLS="$W_WINDIR_UNIX/system32"
 ---> Using cache
 ---> a912b4513e98
Step 21/30 : ENV W_TMP="$W_DRIVE_C/windows/temp/_$0"
 ---> Using cache
 ---> 7ce6ff122ddd
Step 22/30 : RUN set -x     && rm -f "$W_TMP"/*     && wget -P "$W_TMP" https://aka.ms/vs/16/release/vc_redist.x86.exe     && cabextract -q --directory="$W_TMP" "$W_TMP"/vc_redist.x86.exe     && cabextract -q --directory="$W_TMP" "$W_TMP/a10"     && cabextract -q --directory="$W_TMP" "$W_TMP/a11"     && cd "$W_TMP"     && rename 's/_/\-/g' *.dll     && cp "$W_TMP"/*.dll "$W_SYSTEM_DLLS"/
 ---> Using cache
 ---> 05d6efc4a888
Step 23/30 : RUN /usr/bin/pip install pyinstaller==$PYINSTALLER_VERSION
 ---> Using cache
 ---> 3d1ef813f32c
Step 24/30 : RUN mkdir /src/ && ln -s /src /wine/drive_c/src
 ---> Using cache
 ---> 9bd17b109f51
Step 25/30 : VOLUME /src/
 ---> Using cache
 ---> 9730fdb476f8
Step 26/30 : WORKDIR /wine/drive_c/src/
 ---> Using cache
 ---> b3513aa4c106
Step 27/30 : RUN mkdir -p /wine/drive_c/tmp
 ---> Using cache
 ---> 09b2fcf7a797
Step 28/30 : COPY entrypoint-windows.sh /entrypoint.sh
 ---> Using cache
 ---> 6a7099820a64
Step 29/30 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 5e5bb85cf817
Step 30/30 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> f549fd093f5c
Successfully built f549fd093f5c
Successfully tagged win-x32:latest
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "/root/Schreibtisch/Tools/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/root/Schreibtisch/Tools/byob/web-gui/buildyourownbotnet/__init__.py", line 4, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by PixelsDE** [comment]
any ideas how to fix it?

**Comment by JudeHoog** [comment]
What OS are you running and do have both python 3 and python installed?

**Comment by garsh1** [comment]
Python -m pip install flask_bcrypt

**Comment by JudeHoog** [comment]
or just `pip install Flask-Bcrypt` (didn't see that)

**Comment by PixelsDE** [comment]
> What OS are you running and do have both python 3 and python installed?

yeah got both python 2.7.18 and 3.9...

**Comment by PixelsDE** [comment]
> or just `pip install Flask-Bcrypt` (didn't see that)

im tying to do this now

**Comment by PixelsDE** [comment]
> Python -m pip install flask_bcrypt

trying this thx
