### ISSUE TITLE
Tried for many hours, but can't install, please help.

### ISSUE THREAD

**Issue by Vendelin05** [malwaredllc/byob#376]
Hello, first of all, I tried to install this on a google compute engine vm, I tried Debian, 3 different versions of Ubuntu, but just can't get it to work. First, it was getting stuck on building wheel for eighter numpy or opencv, but that started working somehow, but now pyenv tries to install python 3.7.9 and gets stuck on `installing python 3.7.9....` I also tried installing python 3.7.9 myself, but it tries to install it on its own anyway. I spent really long time on this and I really want to get it to work, so if anyone could help me, or just recommend a distro this would run immediately on without troubleshooting, I'll be glad. Thanks

**Comment by Vendelin05** [comment]
Neverming, sorry guys, it was just on the same spot for almost an hour, so I though it broke. I'm not closing this yet, I'll close it as soon as I see it works....

**Comment by Vendelin05** [comment]
Okay, still not working, I got this at the end ```
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/denismasek05/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```and I don't know if it works or not, because if I just open the port 5000 over ngrok and open the given adress on my pc, it just says that it cant be reached. There were also a lot of errors with wine (something like: `wine: cannot find L"C:\\Python37\\Scripts\\pip.exe"`). Please someone help me....

**Comment by Vendelin05** [comment]
Update: I installed all the missing flask things, so now the message and at the `http://127.0.0.1:5000 and set up your user to get started.`, but nothing actually happens...

**Comment by SomeRandom-Dev** [comment]
you need to install flask (pip3 install flask)

**Comment by malwaredllc** [comment]
@Vendelin05 byob does not support ngrok at this time.
