### ISSUE TITLE
Windows Payload Not Working "Unable to find image 'win-x32:latest' locally"

### ISSUE THREAD

**Issue by ItzTazzaYT** [malwaredllc/byob#380]
So I've set up a virtual machine running Ubuntu (Latest Version) on VMware Workstation Pro 16. I've followed the install guide by malwaredllc but every time I go to create a payload for windows x32, nothing happens and I see this message in the terminal:

/usr/bin/docker
(343 bytes written to output/ItzTazza/src/byob_win_x32_qr6.py)
	Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b"See 'docker run --help'."

After this, I get an endless strip of " b'' " in the terminal on a new line. I've seen some similar issues on this problem but I haven't found any that have actually fixed this issue. If there is anything I've missed please let me know!

**Comment by uyeet** [comment]
try reinstalling using git clone or reinstall requirements. sudo ./startup.sh

**Comment by WaspEma** [comment]
same problem for me, in executable for linux and windows

**Comment by malwaredllc** [comment]
This should be fixed in #411

**Comment by slevi123** [comment]
I have the same issue, except my file toncompile is called "byob_win_x32_rdc.py".

**Comment by fireFerry** [comment]
That just means you haven't installed the docker images.

**Comment by SomeUserWith** [comment]
> That just means you haven't installed the docker images.

and how do i install the docker images

**Comment by fireFerry** [comment]
You build them with docker, they're located in the docker-pyinstaller folder.

**Comment by JustRedTTG** [comment]
> You build them with docker, they're located in the docker-pyinstaller folder.

How do I build with docker?

**Comment by fireFerry** [comment]
with the `docker build` command

**Comment by putinshairline** [comment]
> with the `docker build` command

could you please just paste the specific command into here?
I cant for the life of me understand anything ppl online are saying abt this
