### ISSUE TITLE
Android payload (.apk)

### ISSUE THREAD

**Issue by xLinkOut** [malwaredllc/byob#382]
Currently BYOB can generate dropper/stager/payload for Windows, macOS and Linux systems, with Docker, Wine and a bit of dark magic (as you said, and for which I totally agree!). But it can also generate a pure Python payload, with .py extension, which requires the Python interpreter to be installed on the client machine. I did a lot of research and seems possible to execute Python script on Android OS, even without root privileges. Do you think it would potentially be possible to implement, in BYOB, a packaging mechanism to create a standalone .apk file that can be executed on Android device, without install anything else? (Just for reference, [pupy](https://github.com/n1nj4sec/pupy) offers this feature, although I have not thoroughly analyzed how it works).

**Comment by malwaredllc** [comment]
Yes builder (https://buildozer.readthedocs.io/en/latest/) can accomplish this but I haven't had time to integrate it yet. Going to mark this issue as "help wanted" and "new feature" since I think it would definitely be cool.
