### ISSUE TITLE
On the problem of mirror image

### ISSUE THREAD

**Issue by Cjwpython** [malwaredllc/byob#385]
Can you provide the image file
- amd64
- nix-i386
- win-x32
When I build the win-x32 image, I always report an error in the PIP position, which causes my program to tell me that the image does not exist when exporting binary files. In fact, the three images built in the startsh script are all < none > images
Thanks

**Comment by garsh1** [comment]
What operating system are you trying to run it on? If it’s not Ubuntu 20.0.4 LTS, please use that.
