### ISSUE TITLE
Can't build win32 payload

### ISSUE THREAD

**Issue by GroosL** [malwaredllc/byob#391]
`b'21320 INFO: Looking for ctypes DLLs'
b'Traceback (most recent call last):'
b'  File "c:\\Python37\\lib\\runpy.py", line 193, in _run_module_as_main'
b'    "__main__", mod_spec)'
b'  File "c:\\Python37\\lib\\runpy.py", line 85, in _run_code'
b'    exec(code, run_globals)'
b'  File "C:\\Python37\\Scripts\\pyinstaller.exe\\__main__.py", line 7, in <module>'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\__main__.py", line 114, in run'
b'    run_build(pyi_config, spec_file, **vars(args))'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\__main__.py", line 65, in run_build'
b'    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 734, in main'
b"    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))"
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 681, in build'
b'    exec(code, spec_namespace)'
b'  File "byob_win_x32_eYf.spec", line 13, in <module>'
b'    cipher=block_cipher)'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 244, in __init__'
b'    self.__postinit__()'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\datastruct.py", line 160, in __postinit__'
b'    self.assemble()'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 436, in assemble'
b"    ctypes_code_objs = self.graph.get_co_using_ctypes()  # dict like:  {'module1': code_obj, 'module2': code_obj}"
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\depend\\analysis.py", line 674, in get_co_using_ctypes'
b'    r_ident =  r.identifier'
b"AttributeError: 'NoneType' object has no attribute 'identifier'"
b''
b''
b''
b''
b''
b''
b''
b''`

**Comment by uyeet** [comment]
sudo ./startup.sh
