### ISSUE TITLE
Can't generate payload

### ISSUE THREAD

**Issue by GroosL** [malwaredllc/byob#392]
Exception in api.routes.payload.payload_generate: [Errno 2] No such file or directory: '/home/user/byob/web-gui/buildyourownbotnet/output/byobuser/src/dist/windows/byob_win_x32_g4v.exe

**Comment by malwaredllc** [comment]
Looks like your user directory didn't get created properly when you registered in the web-guy. Try doing a fresh install and running it with sudo to ensure it has permissions to create the directories. If you need further help please go to the Discord Support server (link in README).

**Comment by iLaurian** [comment]
Sorry I bother you after all this time but what to fresh install and what to run with sudo 
the discord is not availabe anymore??
