### ISSUE TITLE
Python 3 treats TabErrors as syntax errors

### ISSUE THREAD

**Issue by cclauss** [malwaredllc/byob#40]
Indentation should be all tabs or all spaces but not a mix of the two in Python 3.

[flake8](http://flake8.pycqa.org) testing of https://github.com/malwaredllc/byob on Python 3.7.0

$ __flake8 . --count --show-source --statistics --select=E901,E999__
* https://travis-ci.com/malwaredllc/byob/jobs/149558264#L560

**Comment by malwaredllc** [comment]
This issue should now be fixed, but let me know if it pops up again.

**Comment by cclauss** [comment]
Travis CI will let us know if it ever pops up again.
