### ISSUE TITLE
Wine cannot find Pip while building win-x32

### ISSUE THREAD

**Issue by xLinkOut** [malwaredllc/byob#400]
**Describe the bug**
Docker fail to build the `Dockerfile-py3-win32` image because Wine cannot find Pip.exe under `C:\\Python37\\Scripts\\pip.exe`.

**To Reproduce**
```bash
cd web-gui/docker-pyinstaller/
docker build -f Dockerfile-py3-win32 -t win-x32 .
```

**Screenshots**
![docker](https://user-images.githubusercontent.com/14892153/109425672-a9520e00-79e9-11eb-945d-088b531c1d2e.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2
 - Python 3.9.1
 - Docker version 20.10.2, build 2291f61

**Additional context**
Already tried a fresh clone-install.

**Comment by garsh1** [comment]
The recommended method of running Byob is in Ubuntu 20.0.4 LTS. If you do not have a physical machine, you can run it in a virtual machine. If you want it to run on MacOS you should run the CLI version.

**Comment by xLinkOut** [comment]
Okey, totally right, I'm currenty not using a Linux distro, even less a Debian-based. But it seems to be an error inside the container, that are system-independent by definition, and not releated to the host os?

**Comment by garsh1** [comment]
I think you’d be right but it seems everyone who is using Ubuntu 20.0.4 isn’t having that issue so I’d give it a go.

**Comment by lifeisbroken** [comment]
i have the same issue right now, i saw that i dont have wine installed and now im installing it, ill let you know if i fixed it and post the solution

**Comment by Herobrine31956** [comment]
> i have the same issue right now, i saw that i dont have wine installed and now im installing it, ill let you know if i fixed it and post the solution

Did you find a solution?

**Comment by VerstreuteSeele** [comment]
having the same issue with ubuntu 20.04
