### ISSUE TITLE
cannot register because of taken username

### ISSUE THREAD

**Issue by DaigoJoestar** [malwaredllc/byob#401]
after installing and running ./startup.sh it takes me to the web server for registration, where whatever username i use it is always taken by someone in the server,
I even used a 15 letter randomly generated name to check if could register but no luck
Is this a known issue or am i doing something wrong ?

**Comment by malwaredllc** [comment]
Delete the file database.db and then restart the server. The 1 user per instance restriction is a security measure since this is an externally facing server and you don't want someone else creating an account and fiddling around.

**Comment by DaigoJoestar** [comment]
Changes i made:
I removed the database.db file from the 'buildyourownbotnet' folder  (with
sudo rm)
and i just ran ./startup.sh (sudo) again

Now it show oops you broke something..(500), after i enter the credentials

now when i check the folder the database.db is recreated
should i make any changes to the .db file or am i restarting the server in
a wrong way?

And also i am unable to join the discord

**Comment by garsh1** [comment]
The error screen is something I noticed too after you sign up but you should be able to log into the new account anyways (I was able to). Also, why are you unable to join the discord?

**Comment by DaigoJoestar** [comment]
Oh nice that just worked and i am in the control panel, thanks btw

About discord, it just redirects me to an empty discord without any text
channels or such, i ran it on my browser FYI

**Comment by garsh1** [comment]
No problem. In regards to the discord, nobody else is having that issue as far as I know. It could be a bug with discord.

**Comment by DaigoJoestar** [comment]
i get a timeout error when i run the python payload (using python3) on my
linux computer
is there any specific command i should use?

**Comment by DaigoJoestar** [comment]
I get a timeout error when i run the python payload (using python3) in my
linux computer
I emailed the payload from the computer where i have access to byob to the
other linux computer stated earlier
so i downloaded the payload from the drive link and i get the above error
should i wired transfer the payload or is it something else

**Comment by DaigoJoestar** [comment]
Also is there no x64 architecture for the windows executable payload?

**Comment by garsh1** [comment]
Please join the discord for help with the payloads. There’s no purpose to having an x64 architecture because x32 works on x64 systems but x64 does not work on x32 systems.

**Comment by DaigoJoestar** [comment]
How do I do that?
I click the discord link and it just redirects me to an empty discord

**Comment by garsh1** [comment]
Try using this link https://discord.gg/wfjatqWj

**Comment by DaigoJoestar** [comment]
It says the link is invalid
what to do

**Comment by garsh1** [comment]
Sorry, had the wrong link settings. This shouldn’t expire https://discord.gg/kh3xBt6y
