### ISSUE TITLE
payload not executing

### ISSUE THREAD

**Issue by DaigoJoestar** [malwaredllc/byob#414]
I keep getting the message "failed to execute script byob_win_x32_biv.py" when i run it on windows and

and when i run the python file in linux i get "urllib.error.URLError :<url open error [Error 110] <Connection timed out>

can someone help with this

**Comment by garsh1** [comment]
Most likely this is because you haven’t port forwarded, join the discord server for help.

**Comment by Jamieplayz29** [comment]
how do I join the discord server, I tried to use the link on the website but it just linked me to the text channel even though im not in the server, I need an invite link.

**Comment by garsh1** [comment]
It’s literally right under the code, in the readme.

**Comment by Jamieplayz29** [comment]
oh my days, I'm blind, thanks.
