### ISSUE TITLE
Can Not Generate payloads in the web-gui 

### ISSUE THREAD

**Issue by Cyberguardians101** [malwaredllc/byob#420]
![SCREEN](https://user-images.githubusercontent.com/74994103/110603884-55a79900-813c-11eb-850a-a39ec33b31d6.png)

Can not generate payloads only python formats...
What could the reason be>>>????
Not Allowing Executable Formats....just loads for over an hour now.

**Comment by Cyberguardians101** [comment]
GET /payloads HTTP/1.1" 200 -
/usr/bin/docker
(343 bytes written to output/cyberguardian/src/byob_win_x32_g40.py)
	Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b"See 'docker run --help'."
b''
b''

**Comment by uyeet** [comment]
you dumbass this is what the discord is for.

**Comment by uyeet** [comment]
JOIN THE DAMN DISCORD
it's in faq
also ./startup.sh

**Comment by Cyberguardians101** [comment]
What's the discord server link?

**Comment by fireFerry** [comment]
https://discord.gg/8FsSrw7
