### ISSUE TITLE
ImportError: cannot import name 'Flask'

### ISSUE THREAD

**Issue by NareshChoudhary-rikki** [malwaredllc/byob#435]
even though i have flask already installed, and activated i am still getting this error. please help.
![Screenshot from 2021-03-25 21-54-49](https://user-images.githubusercontent.com/75428349/112462077-a9de8a00-8d86-11eb-9004-39e669c1cb65.png)

**Comment by onelilspecofapop** [comment]
use python3

**Comment by NareshChoudhary-rikki** [comment]
i just resolve the flask import error problem.but now when i try to create an windows .exe payload.. it just stuck at generating payload. but when i check my terminal i am getting display problem error...(see the last line in the terminal )
![Screenshot from 2021-03-28 03-50-13](https://user-images.githubusercontent.com/75428349/112727986-1609eb00-8f4b-11eb-9ad0-b5a3cdb15a94.png)
