### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by madoximxet** [malwaredllc/byob#439]
Please provide us which exactly the version of python we need to install.
Also it gives some errors on Ubuntu 20.04 LTS when trying to install the requirements.txt:

Ignoring mss: markers 'python_version < "3"' don't match your environment
Ignoring WMI: markers 'python_version < "3"' don't match your environment
Ignoring numpy: markers 'python_version < "3"' don't match your environment
Ignoring pyxhook: markers 'python_version < "3"' don't match your environment
Ignoring twilio: markers 'python_version < "3"' don't match your environment
Ignoring colorama: markers 'python_version < "3"' don't match your environment
Ignoring requests: markers 'python_version < "3"' don't match your environment
Ignoring PyInstaller: markers 'python_version < "3"' don't match your environment
Ignoring pycryptodomex: markers 'python_version < "3"' don't match your environment
Ignoring opencv-python: markers 'python_version < "3"' don't match your environment
Ignoring pyHook: markers 'sys_platform == "win32"' don't match your environment
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment

Thank you

**Comment by malwaredllc** [comment]
Those aren't errors, it's just not installing packages that are used by either Windows or Python 2.7
