### ISSUE TITLE
web-gui - cannot execute any operation

### ISSUE THREAD

**Issue by madoximxet** [malwaredllc/byob#442]
Hello,

1- I've followed every step from scratch on how to setup the web-gui until generation windows .exe payload.
2- Everything works fine for now, I have executed the payload on my other machine (the victim's machine let's say)
3- I see the machine in the control panel list
4.a- I literally cannot execute any operation on it (remote shell return nothing when i try to 'ping/ls/pwd/etc...').
4.b- Cannot take screenshot of the target machine (not even a notification will appear)
4.c- Basically I cannot do anything with the target machine, it's just there in the list for nothing

Did I miss something, is it that I did something wrong during the installation process? or is it a bug?

The steps I've followed to install byob web-gui:
1- I granted myself root access
2- pwd and git cloned the repo under /root (/root/byob/web-gui)
3- chmod +x * (for all files in the web-gui directory)
4- I ran .startup.sh and didn't get any error during the installation
5- The web-gui has started and I can login/generate .exe payloads/view the target 'victim' machine

Any help?
![Capture](https://user-images.githubusercontent.com/55803676/113318606-86788980-9308-11eb-9bf3-b10f4ead3020.JPG)

**Comment by malwaredllc** [comment]
@madoximxet Can you run both the server and the payload with the `--debug` flag, try to execute a shell command like `pwd` and copy/paste the debugging output in the console for me to see?

**Comment by madoximxet** [comment]
> @madoximxet Can you run both the server and the payload with the `--debug` flag, try to execute a shell command like `pwd` and copy/paste the debugging output in the console for me to see?

Hello again,
I've ran this command (not from the web-gui forlder): server.py python server.py --host iphere --port 8080 --debug
as you told me and i got this log:

root@deathbot:/root/byob/byob# python3 server.py --host someiphere --port 8080 --debug


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[?]  Hint: show usage information with the 'help' command

parent=main , child=run , args={'self': <__main__.C2 object at 0x7efed7e12310>}
[root @ /root/byob/byob]>clients
parent=run , child=client_list , args={'self': <__main__.C2 object at 0x7efed7e12310>, 'verbose': True}


[root @ /root/byob/byob]>Session init exception: [Errno 104] Connection reset by peer


[-] Failed Connection: someiphere

[root @ /root/byob/byob]>  Session init exception: initialization vector must be 16 bytes


[-] Failed Connection: someiphere

[root @ /root/byob/byob]>  Session init exception: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte


[-] Failed Connection: someiphere

[root @ /root/byob/byob]>

for the client part:

root@deathbot:/root/byob/byob# python3 client.py iphere 8080 --freeze --debug


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[>] Modules
        Adding modules...  -(4 modules added to client)

[>] Imports
        Adding imports...-(31 imports from 4 modules)

[>] Payload
        Uploading payload...  -(hosting payload at: http://iphere:8081/clients/payloads/d82.py)

[>] Stager
        Uploading stager... -(hosting stager at: http://iphere:8081/clients/stagers/d82.py)

[>] Dropper
        Writing dropper...  (351 bytes written to /modules/clients/droppers/byob_d82.py)
        Compiling executable...
/usr/bin/python3: No module named PyInstaller



EMPTY LINES APPEAR HERE SO I HAD TO CTRL+C to stop it (basically nothing happens for 30 minutes) then i get the following:


^CTraceback (most recent call last):
  File "client.py", line 486, in <module>
    main()
  File "client.py", line 198, in main
    dropper = _dropper(options, var=var, key=key, modules=modules, imports=imports, hidden=hidden, url=stager)
  File "client.py", line 468, in _dropper
    name = generators.freeze('modules/clients/payloads/' + kwargs['var'] + '.py', icon=options.icon, hidden=kwargs['hidden'], debug=options.debug)
  File "/root/byob/byob/core/generators.py", line 253, in freeze
    time.sleep(0.25)
KeyboardInterrupt

root@ip-172-26-10-245:/root/byob/byob#

it seems like the client.py has problems generating payload/executing for me, I thought that running the web-gui would install the modules that are needed for this byob folder but seems like not, or did i miss something?
Regards

**Comment by madoximxet** [comment]
> @madoximxet Can you run both the server and the payload with the `--debug` flag, try to execute a shell command like `pwd` and copy/paste the debugging output in the console for me to see?

Hello again,
I've ran this command (not from the web-gui forlder): server.py python server.py --host iphere --port 8080 --debug
as you told me and i got this log:

root@deathbot:/root/byob/byob# python3 server.py --host someiphere --port 8080 --debug


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[?]  Hint: show usage information with the 'help' command

parent=main , child=run , args={'self': <__main__.C2 object at 0x7efed7e12310>}
[root @ /root/byob/byob]>clients
parent=run , child=client_list , args={'self': <__main__.C2 object at 0x7efed7e12310>, 'verbose': True}


[root @ /root/byob/byob]>Session init exception: [Errno 104] Connection reset by peer


[-] Failed Connection: someiphere

[root @ /root/byob/byob]>  Session init exception: initialization vector must be 16 bytes


[-] Failed Connection: someiphere

[root @ /root/byob/byob]>  Session init exception: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte


[-] Failed Connection: someiphere

[root @ /root/byob/byob]>

for the client part:

root@deathbot:/root/byob/byob# python3 client.py iphere 8080 --freeze --debug


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[>] Modules
        Adding modules...  -(4 modules added to client)

[>] Imports
        Adding imports...-(31 imports from 4 modules)

[>] Payload
        Uploading payload...  -(hosting payload at: http://iphere:8081/clients/payloads/d82.py)

[>] Stager
        Uploading stager... -(hosting stager at: http://iphere:8081/clients/stagers/d82.py)

[>] Dropper
        Writing dropper...  (351 bytes written to /modules/clients/droppers/byob_d82.py)
        Compiling executable...
/usr/bin/python3: No module named PyInstaller



EMPTY LINES APPEAR HERE SO I HAD TO CTRL+C to stop it (basically nothing happens for 30 minutes) then i get the following:


^CTraceback (most recent call last):
  File "client.py", line 486, in <module>
    main()
  File "client.py", line 198, in main
    dropper = _dropper(options, var=var, key=key, modules=modules, imports=imports, hidden=hidden, url=stager)
  File "client.py", line 468, in _dropper
    name = generators.freeze('modules/clients/payloads/' + kwargs['var'] + '.py', icon=options.icon, hidden=kwargs['hidden'], debug=options.debug)
  File "/root/byob/byob/core/generators.py", line 253, in freeze
    time.sleep(0.25)
KeyboardInterrupt

root@deathbot:/root/byob/byob#

it seems like the client.py has problems generating payload/executing for me, I thought that running the web-gui would install the modules that are needed for this byob folder but seems like not, or did i miss something?
Regards

**Comment by madoximxet** [comment]
> @madoximxet Can you run both the server and the payload with the `--debug` flag, try to execute a shell command like `pwd` and copy/paste the debugging output in the console for me to see?

I will also give you the web-gui log just in case:
root@deathbot:/root/byob/web-gui# ./startup.sh
WARNING: This script will install docker AND add it as an apt source.

If you do not want this, please press ctrl + C to cancel the script.

The script will start in 10 seconds.
Running BYOB app setup...
Confirmed Python is installed.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Confirmed Docker is installed.
If you run into issues generating a Windows payload, please uninstall docker and rerun this script
Installing Python packages...
Requirement already satisfied: CMake==3.18.4 in /usr/local/lib/python3.8/dist-packages (3.18.4)
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring pyHook: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: SQLAlchemy==1.3.23 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.3.23)
Requirement already satisfied: flask in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (1.1.2)
Requirement already satisfied: flask_session in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (0.3.2)
Requirement already satisfied: flask_wtf in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (0.14.3)
Requirement already satisfied: Flask_SQLAlchemy in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (2.5.1)
Requirement already satisfied: Flask_Login in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (0.5.0)
Requirement already satisfied: Flask_Bcrypt in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (0.7.1)
Requirement already satisfied: flask_mail in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (0.9.1)
Requirement already satisfied: wtforms in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 9)) (2.3.3)
Requirement already satisfied: mss==3.3.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 10)) (3.3.0)
Requirement already satisfied: WMI==1.4.9 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 11)) (1.4.9)
Requirement already satisfied: numpy==1.17.3 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 12)) (1.17.3)
Requirement already satisfied: pyxhook==1.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: twilio==6.14.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 14)) (6.14.0)
Requirement already satisfied: colorama==0.3.9 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 15)) (0.3.9)
Requirement already satisfied: requests==2.20.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 16)) (2.20.0)
Requirement already satisfied: pycryptodomex==3.8.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 17)) (3.8.1)
Requirement already satisfied: py-cryptonight>=0.2.4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 18)) (0.3.3)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 19)) (4.5.1.48)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/lib/python3/dist-packages (from flask->-r requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.8/dist-packages (from flask->-r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: click>=5.1 in /usr/lib/python3/dist-packages (from flask->-r requirements.txt (line 2)) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.8/dist-packages (from flask->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: cachelib in /usr/local/lib/python3.8/dist-packages (from flask_session->-r requirements.txt (line 3)) (0.1.1)
Requirement already satisfied: bcrypt in /usr/local/lib/python3.8/dist-packages (from Flask_Bcrypt->-r requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: blinker in /usr/lib/python3/dist-packages (from flask_mail->-r requirements.txt (line 8)) (1.4)
Requirement already satisfied: MarkupSafe in /usr/lib/python3/dist-packages (from wtforms->-r requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: python-xlib in /usr/local/lib/python3.8/dist-packages (from pyxhook==1.0.0->-r requirements.txt (line 13)) (0.29)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from twilio==6.14.0->-r requirements.txt (line 14)) (1.14.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from twilio==6.14.0->-r requirements.txt (line 14)) (2021.1)
Requirement already satisfied: pysocks; python_version >= "3.0" in /usr/local/lib/python3.8/dist-packages (from twilio==6.14.0->-r requirements.txt (line 14)) (1.7.1)
Requirement already satisfied: PyJWT>=1.4.2 in /usr/lib/python3/dist-packages (from twilio==6.14.0->-r requirements.txt (line 14)) (1.7.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 16)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 16)) (2019.11.28)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests==2.20.0->-r requirements.txt (line 16)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests==2.20.0->-r requirements.txt (line 16)) (1.24.3)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt->Flask_Bcrypt->-r requirements.txt (line 7)) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt->Flask_Bcrypt->-r requirements.txt (line 7)) (2.20)
Building Docker images - this will take a while, please be patient...
Sending build context to Docker daemon  35.33kB
Step 1/12 : FROM ubuntu:20.04
 ---> 8e428cff54c8
Step 2/12 : SHELL ["/bin/bash", "-i", "-c"]
 ---> Using cache
 ---> 584f016497db
Step 3/12 : ARG PYTHON_VERSION=3.7.9
 ---> Using cache
 ---> a4b774021fff
Step 4/12 : ARG PYINSTALLER_VERSION=3.6
 ---> Using cache
 ---> 82b916283ba4
Step 5/12 : ENV PYPI_URL=https://pypi.python.org/
 ---> Using cache
 ---> 6ddc9d5dc762
Step 6/12 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Using cache
 ---> 306123f97e85
Step 7/12 : ENV PYENV_VERSION=${PYTHON_VERSION}
 ---> Using cache
 ---> 4c99b4a1d9d5
Step 8/12 : COPY entrypoint-linux.sh /entrypoint.sh
 ---> Using cache
 ---> eb8d57215829
Step 9/12 : RUN     set -x     && apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         curl         wget         git         libbz2-dev         libreadline-dev         libsqlite3-dev         libssl-dev         zlib1g-dev         libffi-dev         libgdbm-dev         uuid-dev         upx     && mkdir openssl     && cd openssl     && wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz     && tar -xzvf openssl-1.1.1h.tar.gz     && cd openssl-1.1.1h     && ./config --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib     && make     && make install     && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc     && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc     && source ~/.bashrc     && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash     && echo 'eval "$(pyenv init -)"' >> ~/.bashrc     && source ~/.bashrc     && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION     && pyenv global $PYTHON_VERSION     && pip install --upgrade pip     && pip install pyinstaller==$PYINSTALLER_VERSION     && mkdir /src/     && chmod +x /entrypoint.sh
 ---> Using cache
 ---> 0c0ad9da57f2
Step 10/12 : VOLUME /src/
 ---> Using cache
 ---> cffe877b13b5
Step 11/12 : WORKDIR /src/
 ---> Using cache
 ---> 2ce90e98b801
Step 12/12 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> d73eb0fa70f1
Successfully built d73eb0fa70f1
Successfully tagged nix-amd64:latest
Sending build context to Docker daemon  35.33kB
Step 1/12 : FROM i386/ubuntu:18.04
 ---> 72db655ab8da
Step 2/12 : SHELL ["/bin/bash", "-i", "-c"]
 ---> Using cache
 ---> 9d2ba7234560
Step 3/12 : ARG PYTHON_VERSION=3.7.9
 ---> Using cache
 ---> 53c6ca944238
Step 4/12 : ARG PYINSTALLER_VERSION=3.6
 ---> Using cache
 ---> 373f7e91b1b5
Step 5/12 : ENV PYPI_URL=https://pypi.python.org/
 ---> Using cache
 ---> fb62604318d5
Step 6/12 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Using cache
 ---> 0feb57869390
Step 7/12 : ENV PYENV_VERSION=${PYTHON_VERSION}
 ---> Using cache
 ---> d086e7fdc260
Step 8/12 : COPY entrypoint-linux.sh /entrypoint.sh
 ---> Using cache
 ---> b5b675976192
Step 9/12 : RUN     set -x     && apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         curl         wget         git         libbz2-dev         libreadline-dev         libsqlite3-dev         libssl-dev         zlib1g-dev         libffi-dev         libgdbm-dev         uuid-dev         upx     && mkdir openssl     && cd openssl     && wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz     && tar -xzvf openssl-1.1.1h.tar.gz     && cd openssl-1.1.1h     && ./Configure linux-generic32 --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib     && make     && make install     && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc     && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc     && source ~/.bashrc     && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash     && echo 'eval "$(pyenv init -)"' >> ~/.bashrc     && source ~/.bashrc     && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION     && pyenv global $PYTHON_VERSION     && pip install --upgrade pip     && pip install pyinstaller==$PYINSTALLER_VERSION     && mkdir /src/     && chmod +x /entrypoint.sh
 ---> Using cache
 ---> dea465626109
Step 10/12 : VOLUME /src/
 ---> Using cache
 ---> ebbeac312518
Step 11/12 : WORKDIR /src/
 ---> Using cache
 ---> 2b88c0996ccd
Step 12/12 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 54c406e894e5
Successfully built 54c406e894e5
Successfully tagged nix-i386:latest
Sending build context to Docker daemon  35.33kB
Step 1/30 : FROM ubuntu:20.04
 ---> 8e428cff54c8
Step 2/30 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 233c4feee0d2
Step 3/30 : ARG WINE_VERSION=winehq-stable
 ---> Using cache
 ---> 3f1c032b7664
Step 4/30 : ARG PYTHON_VERSION=3.7.9
 ---> Using cache
 ---> 779e00f7806d
Step 5/30 : ARG PYINSTALLER_VERSION=3.6
 ---> Using cache
 ---> 736e9b5395ef
Step 6/30 : RUN set -x     && dpkg --add-architecture i386     && apt-get update -qy     && apt-get install --no-install-recommends -qfy gpg-agent rename apt-transport-https software-properties-common winbind cabextract wget curl zip unzip xvfb xdotool x11-utils xterm     && wget -nv https://dl.winehq.org/wine-builds/winehq.key     && apt-key add winehq.key     && add-apt-repository 'https://dl.winehq.org/wine-builds/ubuntu/'     && apt-get update -qy     && apt-get install --install-recommends -qfy $WINE_VERSION     && apt-get clean     && rm -rf /var/lib/apt/lists/*     && wget -nv https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks     && chmod +x winetricks     && mv winetricks /usr/local/bin
 ---> Using cache
 ---> 87857b4e3c53
Step 7/30 : RUN mkdir -p /usr/share/wine/gecko
 ---> Using cache
 ---> 42bb4f9dca90
Step 8/30 : RUN curl -o /usr/share/wine/gecko/wine_gecko-2.47-x86.msi http://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86.msi
 ---> Using cache
 ---> 0f369d67a5f6
Step 9/30 : ENV WINEARCH win32
 ---> Using cache
 ---> 3482c99051e7
Step 10/30 : ENV WINEDEBUG fixme-all
 ---> Using cache
 ---> 8a7e265ac14f
Step 11/30 : ENV WINEPREFIX /wine
 ---> Using cache
 ---> 2eb74510a96e
Step 12/30 : ENV DISPLAY :0
 ---> Using cache
 ---> 07a344edb9a2
Step 13/30 : RUN set -x     && echo 'Xvfb $DISPLAY -screen 0 1024x768x24 &' >> /root/.bashrc
 ---> Using cache
 ---> 6e3f01ccf81a
Step 14/30 : RUN set -x     && winetricks -q win10
 ---> Using cache
 ---> a396ac9fc7ef
Step 15/30 : ENV PYPI_URL=https://pypi.python.org/
 ---> Using cache
 ---> 534eeb67cae3
Step 16/30 : ENV PYPI_INDEX_URL=https://pypi.python.org/simple
 ---> Using cache
 ---> a3efe7336084
Step 17/30 : RUN set -x     && for msifile in `echo core dev exe lib path pip tcltk tools`; do         wget -nv "https://www.python.org/ftp/python/$PYTHON_VERSION/win32/${msifile}.msi";         wine msiexec /i "${msifile}.msi" /qb TARGETDIR=C:/Python37;         rm ${msifile}.msi;     done     && cd /wine/drive_c/Python37     && echo 'wine '\''C:\Python37\python.exe'\'' "$@"' > /usr/bin/python     && echo 'wine '\''C:\Python37\Scripts\easy_install.exe'\'' "$@"' > /usr/bin/easy_install     && echo 'wine '\''C:\Python37\Scripts\pip.exe'\'' "$@"' > /usr/bin/pip     && echo 'wine '\''C:\Python37\Scripts\pyinstaller.exe'\'' "$@"' > /usr/bin/pyinstaller     && echo 'wine '\''C:\Python37\Scripts\pyupdater.exe'\'' "$@"' > /usr/bin/pyupdater     && echo 'assoc .py=PythonScript' | wine cmd     && echo 'ftype PythonScript=c:\Python37\python.exe "%1" %*' | wine cmd     && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done     && chmod +x /usr/bin/python /usr/bin/easy_install /usr/bin/pip /usr/bin/pyinstaller /usr/bin/pyupdater     && (pip install -U pip || true)     && rm -rf /tmp/.wine-*
 ---> Using cache
 ---> 620d0915c6e7
Step 18/30 : ENV W_DRIVE_C=/wine/drive_c
 ---> Using cache
 ---> e0f9831d1d27
Step 19/30 : ENV W_WINDIR_UNIX="$W_DRIVE_C/windows"
 ---> Using cache
 ---> f37a6991feb7
Step 20/30 : ENV W_SYSTEM_DLLS="$W_WINDIR_UNIX/system32"
 ---> Using cache
 ---> 224e0894991f
Step 21/30 : ENV W_TMP="$W_DRIVE_C/windows/temp/_$0"
 ---> Using cache
 ---> 8d4fbc3b47f1
Step 22/30 : RUN set -x     && rm -f "$W_TMP"/*     && wget -P "$W_TMP" https://aka.ms/vs/16/release/vc_redist.x86.exe     && cabextract -q --directory="$W_TMP" "$W_TMP"/vc_redist.x86.exe     && cabextract -q --directory="$W_TMP" "$W_TMP/a10"     && cabextract -q --directory="$W_TMP" "$W_TMP/a11"     && cd "$W_TMP"     && rename 's/_/\-/g' *.dll     && cp "$W_TMP"/*.dll "$W_SYSTEM_DLLS"/
 ---> Using cache
 ---> 58a5c173bf72
Step 23/30 : RUN /usr/bin/pip install pyinstaller==$PYINSTALLER_VERSION
 ---> Using cache
 ---> a69f994f0de7
Step 24/30 : RUN mkdir /src/ && ln -s /src /wine/drive_c/src
 ---> Using cache
 ---> 2a0608a9cee4
Step 25/30 : VOLUME /src/
 ---> Using cache
 ---> 61a440bc509b
Step 26/30 : WORKDIR /wine/drive_c/src/
 ---> Using cache
 ---> 93074ccb674a
Step 27/30 : RUN mkdir -p /wine/drive_c/tmp
 ---> Using cache
 ---> 51f18846a706
Step 28/30 : COPY entrypoint-windows.sh /entrypoint.sh
 ---> Using cache
 ---> c54ea8dd5c53
Step 29/30 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 9e6c36397cfb
Step 30/30 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 9c72c844a436
Successfully built 9c72c844a436
Successfully tagged win-x32:latest
To use some Byob features, you must reboot your system. If this is not your first time running this script, please answer no. Reboot now? [Y/n]: n
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
 * Serving Flask app "buildyourownbotnet" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**Comment by malwaredllc** [comment]
@madoximxet I think this is because you are using Python 3.8+. Right now only Python 3.7 is supported (I just tested using 3.7.0 and it works as expected).
