### ISSUE TITLE
TypeError:can't apply this __setatr__ to DefultMeta object

### ISSUE THREAD

**Issue by flaryx32** [malwaredllc/byob#445]
Im running this on kali on oracle VM virtualbox
![Error](https://user-images.githubusercontent.com/77863658/113635975-e73df400-9671-11eb-8a03-b6bf21423cf5.png)

**Comment by malwaredllc** [comment]
It looks like this was a bug introduced in Python 3.8.4 (https://stackoverflow.com/questions/62917535/typeerror-cant-apply-this-setattr-to-defaultmeta-object-flask-app-pyth) so you will need to downgrade to 3.7 (which is the latest supported version for BYOB).

**Comment by flaryx32** [comment]
How do i do to downgrade?

**Comment by malwaredllc** [comment]
You can join the Discord support server (link in the README) and someone can help you.
