### ISSUE TITLE
requests and urllib[2] library both used

### ISSUE THREAD

**Issue by joren485** [malwaredllc/byob#45]
The `requests`, `urllib` and `urllib2` libraries are all used. As they serve the same purpose, it would be better for consistency and readability to only use one of them.

My personal preference goes out to `requests` because it is much easier to understand and use.

**Comment by malwaredllc** [comment]
1. Clients remotely import third-party libraries not included in the Python standard library (such as `requests`) from the C2 server, which requires either `urllib` or `urrlib2`.
2. Making HTTP POST requests without the `requests` library requires both `urllib` and `urllib2`.

**Comment by joren485** [comment]
Python 3 does not have `urllib2`:
```
$ python                                                                                                                                                                                            
Python 3.7.0 (default, Sep 15 2018, 19:13:07) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'urllib2'
```

**Comment by malwaredllc** [comment]
Okay, so `urllib2` will be removed, `urllib` will be used for remote imports, and then `requests` will be used for everything thereafter

**Comment by TheBrokenWasp** [comment]
when will this happen?

**Comment by malwaredllc** [comment]
Python3 support has been completed in #191 
The issue of Python3 not having `urllib2` is addressed in the following way:

```
if sys.version_info[0] < 3:
    from urllib import urlretrieve
    from urllib2 import urlopen, urlparse
else:
    from urllib import parse as urlparse
    from urllib.request import urlopen, urlretrieve
```
I have kept the use of `urllib` for redundancy's sake, in case the `requests` module is not able to be remotely imported (or embedded in the executable by PyIntaller with the `--freeze` option).
