### ISSUE TITLE
Payloads not working

### ISSUE THREAD

**Issue by umegbewe** [malwaredllc/byob#451]
I think everything has been done correctly, setup the Python payload and ran it on my PC (same PC byob is running). Checked processes and i could see the script running, but I don't see any bots on the web-gui.

**Comment by Shazelz** [comment]
Have you port forwarded ports 1337-1339 even if it is on the same device it still needs to be port forwarded the same problem happened to me

**Comment by umegbewe** [comment]
> Have you port forwarded ports 1337-1339 even if it is on the same device it still needs to be port forwarded

How do i port forward those on a virtual machine?

**Comment by fireFerry** [comment]
You will need to bridge the vm, just google how to port forward on a vm. Also you can't run the payload on the same machine as you're hosting on. If you're hosting on a vm, you **can** execute it on your main os, but not on that same vm.

**Comment by 1NEGROUP** [comment]
I think I might be having the same problem. Though i am trying to put a payload on my samsung a71 (android) and my Mac (Mac OS X). On my android i am getting error 111 and on my Mac i am getting error 61 both say connection refused.

**Comment by fireFerry** [comment]
> 
> 
> I think I might be having the same problem. Though i am trying to put a payload on my samsung a71 (android) and my Mac (Mac OS X). On my android i am getting error 111 and on my Mac i am getting error 61 both say connection refused.

Python is not officially for android, android isn't a supported os. And are you hosting the web-gui on osx? The web-gui can only be hosted on Linux, not osx.

**Comment by 1NEGROUP** [comment]
I am Hosting the gui on Linux

**Comment by 1NEGROUP** [comment]
and I would forward ports via the settings on my router right?

**Comment by fireFerry** [comment]
Yes

**Comment by 1NEGROUP** [comment]
Ok so i keep getting this error
[>]Payload
	Uploading payload...  -Traceback (most recent call last):
  File "client.py", line 452, in <module>
    main()
  File "client.py", line 196, in main
    payload = _payload(options, var=var, key=key, modules=modules, imports=imports, hidden=hidden)
  File "client.py", line 345, in _payload
    with open(path, 'w') as fp:
PermissionError: [Errno 13] Permission denied: '/home/thejames/byob/byob/aDs.py

**Comment by 1NEGROUP** [comment]
Never mind i think i got it to work

**Comment by AIITV** [comment]
is it port 1337 to 1339 or 1337 and 1339

**Comment by Jammstheshreklord** [comment]
> Have you port forwarded ports 1337-1339 even if it is on the same device it still needs to be port forwarded

Do i have to do both ports? cuz portmap.io only gives you one

**Comment by Jammstheshreklord** [comment]
> is it port 1337 to 1339 or 1337 and 1339

Bro its just port 1337 and 1339

**Comment by Jammstheshreklord** [comment]
> Is it possible to bypass the portforwarding somehow?

Guys is it possible to take a shower but with out the water somhow?

just kidding use telebit download it from there official website `https://telebit.cloud/` then just follow the steps to do so if you get 

any problems just ask

**Comment by xsa00** [comment]
Can someone help? i got my discord user is nofames or can someone tell me how do i port fortward vm with kali linux im hosting webgui on my kali and i ran the payload on my main os but i wont get anything so i think its the portforwarding i really dont know pelase help and ty

**Comment by Jammstheshreklord** [comment]
I aint the guy to tell this nigga :skull:
