### ISSUE TITLE
Forgotten Password

### ISSUE THREAD

**Issue by umegbewe** [malwaredllc/byob#452]
I think there has to be a forgotten password mechanism for the project.

A special key should be generated and downloaded after every sign up. You use that key file to reset your password instead of deleting the .db file

**Comment by fireFerry** [comment]
There is only 1 account allowed, and deleting the db file is so easy, it really isn't that hard

**Comment by umegbewe** [comment]
Exactly I think it's way too easy for an account to be destroyed by just deleting a db file.

**Comment by fireFerry** [comment]
What do you mean? It's your task to keep your server secure from others, and you won't accidentally delete the database file.

**Comment by umegbewe** [comment]
In as much as it's our responsibility to secure our servers, i still think it's way too easy for an account to be destroyed.

The 'Forgotten password" is just a handy feature.

**Comment by fireFerry** [comment]
Well even if such a thing gets added, the account would still be deletable by deleting the db file. If you really can't secure your server from others deleting the db file idk if you're ready for byob. It's not that hard to keep yourself secure.

**Comment by umegbewe** [comment]
I have no problems on my side I'm just concerned why it is so easy.

Can the file be hidden at least?

**Comment by fireFerry** [comment]
You can change the database location yourself, just in config.py
