### ISSUE TITLE
first time run of startup.sh is stuck at "Building wheel for opencv-python (PEP 517)"

### ISSUE THREAD

**Issue by Artemis-Arrow** [malwaredllc/byob#454]
**Describe the bug**
I am using the default ova file of parrot sec os if that helps, I had run setup.py already, now when I run startup.sh for the first time it is just stuck at Building wheel for opencv-python (PEP 517), if needed I can provide a video of the issue

**To Reproduce**
no idea tbh, I wrote everything I know above
**Expected behavior**
it should be done with that step quickly

**Screenshots**
https://prnt.sc/12md0pe

**Desktop (please complete the following information):**
 - OS: parrot security os
 - Python version latest, I update it frequently

**Comment by Artemis-Arrow** [comment]
note: the last line just stays, it is stuck there

**Comment by Artemis-Arrow** [comment]
well, it finally worked
I did nothing tbh just waited, now its on

**Comment by jaykali** [comment]
I also got same issue because I'm using pip version 19, opencv_python can't be installed using this version we need to upgrade pip by using `sudo pip3 install --upgrade pip` command. It solves my problems.

Now you can close this issue.

**Comment by fireFerry** [comment]
Opencv can take some time too, make sure your pip is updated as jaykali said and you'll be fine
