### ISSUE TITLE
(question) is byob designed to disconnect the connection between the host computer and the infected when the host is turned off

### ISSUE THREAD

**Issue by Artemis-Arrow** [malwaredllc/byob#459]
I am currently studying botnets for a big ed project, though when I turn off my pc the connection between host and infected is disconnected, is byob designed this way.
if so how can I overcome that since I need the connection to stay
if not how can I fix the issue
thx in advance

**Comment by fireFerry** [comment]
If you use the persistence module the bots will be there even after a reboot

**Comment by Artemis-Arrow** [comment]
Thx m8

**Comment by fireFerry** [comment]
@malwaredllc Ready to be closed.

**Comment by nikoli0218** [comment]
You say use the persistence module yet the modules do not work at all. This would be such a great botnet if it actually worked, or if it had real support because the discord is absolutely worthless.
