### ISSUE TITLE
Cant do Exe payload

### ISSUE THREAD

**Issue by nexusdayz** [malwaredllc/byob#462]
i write here so i cant write on discord , more then 6 hours and no member role so i open an issue here

so i cant make a exe payload.

usr/bin/docker

        Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b"See 'docker run --help'."

i try with docker login and the login success , but dont work ......

**Comment by nexusdayz** [comment]
Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b"See 'docker run --help'."

**Comment by AJANILOY** [comment]
to me it is showing that you broke something. it works good with python payloads
what to do.?anyone?

**Comment by fireFerry** [comment]
You should join the Discord server for support, it's really handy: https://discord.gg/8FsSrw7

In the error from @nexusdayz It seems like the docker images didn't build correctly. If you have trouble joining the Discord server, you can always DM me (fireFerry#2313) to get it sorted. You should receive the member role after completing the membership screening.

@AJANILOY If you have any error, it would be great to post it here or in the Discord server.
