### ISSUE TITLE
 it is not working at all 

### ISSUE THREAD

**Issue by samrit0001** [malwaredllc/byob#463]
not able to generate payloads for operating systems and python script is not working

**Comment by NotCoolKiwi** [comment]
i've had this same problem

**Comment by garsh1** [comment]
Join the discord server for help, likely you have not port forwarded.

**Comment by andrewfishy** [comment]
> Join the discord server for help, likely you have not port forwarded.

can you send me an invite link please?

**Comment by fireFerry** [comment]
@andrewfishy https://discord.gg/8FsSrw7
