### ISSUE TITLE
./startup.sh not working

### ISSUE THREAD

**Issue by TwinxNYC** [malwaredllc/byob#464]
"Building wheel for opencv-python (PEP 517) ... |  "

Is in an endless loop

**Comment by bodhibd13** [comment]
im having the same issue. I'm on kali linux and has been saying for about an hour, "Building wheel for opencv-python"

**Comment by uyeet** [comment]
takes time also join the byob discord

**Comment by TwinxNYC** [comment]
Yeah, I solved it... just wait and then open the run.py file
