### ISSUE TITLE
Exe Payload

### ISSUE THREAD

**Issue by SunnyAim** [malwaredllc/byob#468]
When i want to create a exe payload its just spamming in ![Screenshot_320](https://user-
![Screen](https://user-images.githubusercontent.com/75436909/120074528-8b09b600-c09d-11eb-9cbc-47762b3c54a3.png)

b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '
b ' '

Please Help, thx for help in advance :)

**Comment by uyeet** [comment]
Join the Byob discord server for support.

**Comment by neviosng** [comment]
Can you send a Discord invite?

**Comment by Nycz-lab** [comment]
try starting the py file via sudo

**Comment by fireFerry** [comment]
1. Discord server invite link: https://discord.gg/8FsSrw7
2. Did you install docker with `apt install docker.io`? If so, this is an outdated method and won't work. You should uninstall docker and reinstall from their official docs and build the images again.
