### ISSUE TITLE
Unable to Connect to BYOB

### ISSUE THREAD

**Issue by pokemonguy1** [malwaredllc/byob#471]
I am using Linux on VirtualBox, and I had this issue when I tried to connect to my BYOB. 
![image](https://user-images.githubusercontent.com/68086629/120893933-9037a980-c637-11eb-8495-100452ecb083.png)
Can someone help to solve this problem?

**Comment by fireFerry** [comment]
You did Ctrl + C, that kills the server.

**Comment by TormentedSoul666** [comment]
Smh, some people should really not play with stuff they don't understand...
