### ISSUE TITLE
Add ability to set host server;s ip in web-gui, and ability to set icon for the exe

### ISSUE THREAD

**Issue by lecatos** [malwaredllc/byob#472]
Currently you cannot set a host server's ip for a payload in the web-gui version.
This feature can be handy for testing on LAN
The next feature is to set the icon for the generated exe.
please add this basic feature

**Comment by garsh1** [comment]
Hi @lecatos, both of these are good features  that may be added in the future. They currently exist in the command line version but definitely should have a place in the web gui.
