### ISSUE TITLE
: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: 

### ISSUE THREAD

**Issue by RecoX** [malwaredllc/byob#476]
When I try to create an exe for windows it throws this error:

'docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.'
b"See 'docker run --help'."

I'm in ubuntu, any idea?

**Comment by fireFerry** [comment]
Did you install docker using `apt install docker.io`?

If so, this is an outdated method and won't work. You'll need to uninstall docker and reinstall using their official documentation.

**Comment by RecoX** [comment]
I followed this guide:

https://docs.docker.com/engine/install/ubuntu/

And idk if this is related but after rebooting the computer now I can't use it anymore. It stuck meanwhile it boots in
`/deb/sda2: clean xxxxx/xxxxx files, xxxxx/xxxx blocks` now I'm trying to fix the O.S.

**Comment by garsh1** [comment]
Saying you installed from that guide does not help us much as there is 3 ways listed. You need to use a convenience script which can be found further down in the guide, one is also provided in the main web-gui directory called “get-docker.sh”. 

Byob is not known to cause operating systems to stop working and this hasn’t been reported by any other users (to my knowledge), it is likely something else you were doing with the machine or your virtualization software (if applicable).

**Comment by RecoX** [comment]
Thanks for the reply guys, ill try soon again if I got better luck.

**Comment by p0syd0n** [comment]
I have this issue, did anyone find the solution?
