### ISSUE TITLE
Web-gui not work

### ISSUE THREAD

**Issue by emulator41** [malwaredllc/byob#479]
hello, i have a big problem when i generate a payload for windows of the web-gui the file is created correctly but when i start it on windows it gives me errors and it doesn't work and then i wanted to know how does the program select the port and the ip and if it selects the public one or the local one?

**Comment by hackerist** [comment]
Can u check it local ports and ip.  If u configrations using another ip Block thats giving eror.

**Comment by fireFerry** [comment]
The payload uses ports 1337, 1338, 1339 and connect using your public ip so port forwarding is required
