### ISSUE TITLE
Web Gui Cannot Be Used A Second Time

### ISSUE THREAD

**Issue by Ugroon** [malwaredllc/byob#481]
![byob](https://user-images.githubusercontent.com/77273551/123850319-8cd7cb00-d922-11eb-8c84-e79f9c3624e9.png)

**Comment by Ugroon** [comment]
You should an option --restart --reload --stop etc.

**Comment by fireFerry** [comment]
you can make the web-gui run in a screen, then you can always access it.

**Comment by garsh1** [comment]
The error itself is likely due to use of an unsupported Linux distro, have you tried rebooting your operating system? Please join the discord for support.
