### ISSUE TITLE
Byob plugin No Client ID

### ISSUE THREAD

**Issue by Nezarov** [malwaredllc/byob#484]
Hello, I've created a payload and run it on my PC, I got a new client connection but without an ID! which means that I cant run shell cmd.. I am using Kaly linux, wsl2.
Any solution? Thanks.
![Image 2021-07-11 at 07 36 40 AM](https://user-images.githubusercontent.com/13366282/125182010-60258c80-e21b-11eb-9770-04ca68c2da7d.jpg)

**Comment by sinaj2889** [comment]
Got this fixed?
