### ISSUE TITLE
Incorrect padding when i run the python server and try to connect to the web-gui.

### ISSUE THREAD

**Issue by Krypt0c** [malwaredllc/byob#485]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
When I run the server and go to the default web-gui it tells me 'Session init exception: Incorrect padding' 

**To Reproduce**
1. Go to 'byob/byob'
2. type 'python3 server.py'
3. visit the web-gui at 0.0.0.0:1337

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.9

**Comment by TimyIsCool** [comment]
try going to the /byob/web-gui then do ./setup.sh then do python3 run.py (press tab on stuff i dont know it that is all the right file names)

**Comment by Krypt0c** [comment]
That worked, thanks so much
