### ISSUE TITLE
unable to locate directory containing user-installed packages

### ISSUE THREAD

**Issue by ArchLinc** [malwaredllc/byob#500]
i cant seem to run the run.py file i keep getting 
unable to locate directory containing user-installed packages

**Comment by ImBerkayKaplan** [comment]
I'm getting the same error, please help

**Comment by fireFerry** [comment]
Which os are you using?

**Comment by Dedusik312YT** [comment]
please help, no working unable to locate directory containing user-installed packages

**Comment by fireFerry** [comment]
1. This is not a byob issue
2. Without telling your os and python version we cannot help you.

**Comment by Dedusik312YT** [comment]
And what kind of OC is needed?

**Comment by fireFerry** [comment]
What do you mean by OC?

**Comment by RumenNumeral** [comment]
Hello. If this is still up. My OS is Debian and I am having the same issue. It has specifically occured after I finished installing all the missing flask modules that weren't installed in the startup.sh

**Comment by z6il** [comment]
I have same problem with 
python 3.9.7
OS linux kali 5.10.0 
On VMbox
When i run "Python3 run.py" output like:
"unable to locate directory containing user-installed packages"
Also sudo didn't work

**Comment by fireFerry** [comment]
Again this isn't an issue with byob, this is an issue that the path to the python modules isn't set correctly. This error occurs frequently on Kali Linux, that's why we recommend to use Ubuntu 20.04 lts instead.

**Comment by z6il** [comment]
What the correct path for this mudules so?

**Comment by fireFerry** [comment]
That depends on your system, we cannot help you with this.

**Comment by windowshopr** [comment]
I'm also getting this error on Windows 10, Python 3.7.9. To say this isn't a BYOB issue isn't helpful. Perhaps a little more elaboration on the WHY we're getting this error would be helpful. You most certainly can help us with this as you'll know more about it than we do.

My site packages for the modules I pip install get put in the default directory of `~\AppData\Roaming\Python\Python37\site-packages` (or Lib\site-packages, I can't remember off the top of my head lol). Is this what you're referring to? And if so, how can we "set the path to the python modules"?

**Comment by windowshopr** [comment]
I got it working on my machine by navigating into the `byob > web-gui > buildyourownbotnet > server.py` file and changing the line

`site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_) if 'mss' in os.listdir(_)]`

...to....

`site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_) ]#if 'mss' in os.listdir(_)]`

Not sure what we're looking for in the 'mss' there, but magically the site_packages populated... Hope that helps!

**Comment by MrTutoOff** [comment]
Many of the scripts dont work
