### ISSUE TITLE
miner not working

### ISSUE THREAD

**Issue by Minecon724** [malwaredllc/byob#501]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
miner doesnt work, webgui says that it started successfully but it didnt
0 cpu usage, no connection to the pool

**To Reproduce**
1. activate miner

**Expected behavior**
miner working? i guess

**Screenshots**

**Desktop (please complete the following information):**
 - OS windows 10
 - Python version 2.7

**Additional context**

**Comment by fireFerry** [comment]
For the web-gui you need Python 3.7+ and Linux, Windows isn't supported.

**Comment by Minecon724** [comment]
i use web gui on ubuntu and python 3.9

**Comment by fireFerry** [comment]
Are you using a vm? or bare metal, dualboot, etc.

**Comment by Minecon724** [comment]
a vps

**Comment by fireFerry** [comment]
Vpses can cause issues, it's recommended to use a local vm instead, it works better.
