### ISSUE TITLE
Can't figuer out how to generate EXE

### ISSUE THREAD

**Issue by mosqitoburito** [malwaredllc/byob#503]
I cant figure out how to generate the EXE i know you have to run a certain command but idk what it is so can someone please tell me

**Comment by fireFerry** [comment]
Using the web-gui or cli version of byob?

**Comment by mosqitoburito** [comment]
> Using the web-gui or cli version of byob?

im using the windows version its not the web but idk what it is

**Comment by fireFerry** [comment]
Then either use the `--freeze` argument or use pyinstaller to compile the python payload.
