### ISSUE TITLE
Ports and payload not working

### ISSUE THREAD

**Issue by Bipedalperry** [malwaredllc/byob#513]
having trouble executing payloads on machines on linux machines and windows machines not sure if it is an issue with ports or what

**Comment by whitenight1985** [comment]
![image](https://user-images.githubusercontent.com/109531969/179701603-37349f91-9649-46d5-baf7-4bb69f73b9a6.png)
I want to know how he solves it.
Is this a port issue?If anyone knows, please, please tell me this problem has been bothering me for a long time.

**Comment by mrrogers16** [comment]
I am getting the same error as above. Did anyone find a fix for this?
