### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by anon-user-com** [malwaredllc/byob#515]
When I run python file a get an error ![image](https://user-images.githubusercontent.com/64283589/139113157-e4946407-353e-461e-a700-48e1cbf3ee83.jpeg) also I can't generate executable file.

**Comment by fireFerry** [comment]
Did you port forward?

**Comment by anon-user-com** [comment]
No I didn’t. Should I do it on my router?

**Comment by fireFerry** [comment]
Yes, you need to port forward ports 1337-1339.

**Comment by anon-user-com** [comment]
> Yes, you need to port forward ports 1337-1339.

Yeah I do some research and I found that. But now I don't prefer this way for security reasons so can I host it on Heroku please what should I do. If you can help me please!

**Comment by fireFerry** [comment]
We don't support hosting this on a VPS. What's risky about this? If you close your ports while you're not using byob and make sure it's behind a secure machine, nothing can happen.

**Comment by anon-user-com** [comment]
> We don't support hosting this on a VPS. What's risky about this? If you close your ports while you're not using byob and make sure it's behind a secure machine, nothing can happen.

Yeah maybe this is a thing but my ip change periodically so I need a static ip I will use ngrok maybe but I should do some research.

**Comment by fireFerry** [comment]
Ngrok is only capable of port forwarding 1 port, so it isn't going to work. Even with a dynamic ip your ip shouldn't change that regularly.

**Comment by anon-user-com** [comment]
Okay thank you for your support I will do and some research as well. I want to know about generating executable file not working any solution.

**Comment by fireFerry** [comment]
It can have a number of reasons, it may be quicker if you join our discord server for support: https://discord.gg/8FsSrw7
