### ISSUE TITLE
[BUG] Shell cannot accept commands with spaces

### ISSUE THREAD

**Issue by danthegoodman1** [malwaredllc/byob#52]
**Example**
*agent connects to server*
`shell 1`
*shell pops up*
`mkdir hey`
_returns:_ `mkdir: missing file operand`
`mkdir --help`
_returns_ `No JSON object could be decoded`
**everything is frozen, no way to ctrl-c out of program, have to reboot**

This happens pretty much anytime you try a command with a space in it, it has no idea what to do. If you pass `echo hey` it returns a blank, if you pass `echo` it returns the same blank.

However, single word commands like `whoami` work just fine.

**Comment by malwaredllc** [comment]
Thanks for bringing this to my attention. This issue should now be fixed.
