### ISSUE TITLE
Docker Can't Find win-x32

### ISSUE THREAD

**Issue by SinSinati5** [malwaredllc/byob#520]
Docker can't find it and I can't find it on docker hub either.  How should I fix this?

**Comment by fireFerry** [comment]
the dockerfiles needed for byob are located in docker-pyinstaller.

**Comment by SinSinati5** [comment]
What do you mean? Can you tell me how to make it work?  It says it can't pull it.

It gives me this Error:
Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
b"See 'docker run --help'."


and I have signed in to docker and this is running as sudo.

**Comment by fireFerry** [comment]
Can you tell me on which os you're hosting byob and if you're using a vm?

**Comment by SinSinati5** [comment]
I'm using Kali Linux and im not on a vm.

**Comment by fireFerry** [comment]
Are you using bare metal then? And did you install docker the proper way using their docs?

**Comment by SinSinati5** [comment]
I believe I have bare metal.  But for docker I think I just did sudo apt-get install docker

**Comment by SinSinati5** [comment]
I also forgot to include this in the error

"Unable to find image 'win-x32:latest' locally"

**Comment by fireFerry** [comment]
Bare metal is just Kali on the actual disk, not virtualized. `sudo apt-get docker` is not the correct way to install docker, please read the docker wiki.
