### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by NLketamingo420** [malwaredllc/byob#521]
I am gettings this error after running "sudo ./startup.sh"

Building Docker images - this will take a while, please be patient...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
To use some Byob features, you must reboot your system. If this is not your first time running this script, please answer no. Reboot now? [Y/n]: n
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/peppie/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    c2 = server.C2(debug=_debug)
  File "/home/peppie/byob/web-gui/buildyourownbotnet/server.py", line 68, in __init__
    self.socket = self._init_socket(self.port)
  File "/home/peppie/byob/web-gui/buildyourownbotnet/server.py", line 123, in _init_socket
    s.bind(('0.0.0.0', port))
PermissionError: [Errno 13] Permission denied

**Comment by fireFerry** [comment]
Seems llike you didn't quite set your file permissions right. Try setting them to read/write and to the correct owner.

**Comment by NLketamingo420** [comment]
> Seems llike you didn't quite set your file permissions right. Try setting them to read/write and to the correct owner.

do you mean like this?

┌──(peppie㉿Peppie-PC)-[~]
└─$ ls -l
total 0
drwxrwxrwx 1 peppie peppie 512 Nov  1 06:44 byob

**Comment by fireFerry** [comment]
The error you sent in the first message is pure file permissions setup wrong.

the Docker error however, seems like a different error. How did you install docker?

**Comment by NLketamingo420** [comment]
How can i set the file permissions correctly? i did "sudo chmod -R u=rwx,g=rwx,o+rwx byob" on the byob folder.

i also tried this commands and then i get this:

peppie@Peppie-PC:~$ sudo service docker start
 * Starting Docker: docker                                                                                       [ OK ]
peppie@Peppie-PC:~$ sudo service docker status
 * Docker is not running

**Comment by fireFerry** [comment]
That's only to start docker, how did you install docker?

**Comment by NLketamingo420** [comment]
just in the source its self in the folder web-gui, i used that file get-docker.sh to install it, And after that i followed this small guide for installing docker https://docs.docker.com/engine/install/ubuntu/

**Comment by fireFerry** [comment]
It seems like you're using kali Linux, that guide is for Ubuntu. I recommend you to fully reinstall docker.

**Comment by NLketamingo420** [comment]
I am using Ubuntu

I tested some more things to rule out possible causes, the results I got I saved in a notepad that I can add tomorrow, but what I did notice was that I can't possibly get access for //var/run/docker, I manually set all permissions for these folders and the files in them, and linux itself also sees that Docker is just installed and can function properly, but it keeps getting the same error, I have already tried by using sudo su first and even tested kali linux but still no success.

Do you happen to have a few things I could try? or is there a way to install docker?

I suspect that Docker itself is just fine, but Docker daemon is the culprit, can this be correct?

**Comment by fireFerry** [comment]
This error indicates that docker isn't running. if you do `sudo systemctl docker status` and if it does not say Active running, then docker is not running and byob won't work then. I suggest you completely uninstall and reinstall docker the way the docs are describing, and then running `docker run hello-world` to see if docker is successfully installed.
