### ISSUE TITLE
Problem making windows, linux payloads

### ISSUE THREAD

**Issue by johnusroot0101** [malwaredllc/byob#523]
When I generate the Linux payload 'amd64' I get this message "Unable to find image 'nix-amd64:latest' locally" docker: Error response from daemon: pull acess denied for nix-amd64, repository does not exist or may require denied: request access  to the resource is denied."
Then after it displays the message it repeats b' '

If I had help with this I would be very thankful!

**Comment by fireFerry** [comment]
This means the docker images aren't correctly installed. On which os are you hosting byob, and are you using a vm or not?

**Comment by johnusroot0101** [comment]
Yes, I am indeed using a vm and i'm running a ubuntu server. Thanks for responding to my issue!

**Comment by johnusroot0101** [comment]
> This means the docker images aren't correctly installed. On which os are you hosting byob, and are you using a vm or not?

Yes, I am indeed using a vm and i'm running a ubuntu server. Thanks for responding to my issue!

**Comment by fireFerry** [comment]
No problem, then if you installed docker correctly (using their official docs) it should work fine. But if you installed docker with `sudo apt-get install docker.io`, then things won't work as that's an outdated way of installing docker. Did you install docker the new way or let startup.sh do it, or did you use docker.io?

**Comment by johnusroot0101** [comment]
> No problem, then if you installed docker correctly (using their official docs) it should work fine. But if you installed docker with `sudo apt-get install docker.io`, then things won't work as that's an outdated way of installing docker. Did you install docker the new way or let startup.sh do it, or did you use docker.io?

Yes, I used apt. I have tried byob few times it would just never work, but I've always used "apt-get install docker.io -y".
But, I will use the sh script next time I install byob. Sorry for getting back to you at such a late time. Thank you!
