### ISSUE TITLE
Payload and Bots don't show up

### ISSUE THREAD

**Issue by SinSinati5** [malwaredllc/byob#524]
After I generate a windows payload, it doesn't show up on my payload list so I had to go to the output folder where the .exe file was located and take it from there.  After I did that I ran the file on my other computer and it gives me the error:

The procedure entry point GetDaylightFlag could not be located in the dynamic library link
C:\Users\LENOVO~1\AppData\Local\Temp\_MEI132642\ucrtbase.dll.

After I press OK the rest of the operation runs and finishes but I still can't see my other laptop on the control panel.

What I want to know is how to make the payload appear on the payloads tab and how to fix the problem above.

Thankyou so much

**Comment by fireFerry** [comment]
> After I generate a windows payload, it doesn't show up on my payload list so I had to go to the output folder where the .exe file was located and take it from there.

This is not recommended and may cause the executable not to work. It needs to be downloaded from the web-gui itself

> The procedure entry point GetDaylightFlag could not be located in the dynamic library link
C:\Users\LENOVO~1\AppData\Local\Temp_MEI132642\ucrtbase.dll.

This is a non-fatal error and has no impact on the functionality.

> What I want to know is how to make the payload appear on the payloads tab and how to fix the problem above.

As executable payloads don't give any type of error output, please run the python payload in a terminal window.

**Comment by SinSinati5** [comment]
But what should I do to get the exe?

**Comment by fireFerry** [comment]
You need to go to the web-gui, and click generate executable, wait a few minutes, and it will appear.

**Comment by SinSinati5** [comment]
Alright imma try that, thnx

**Comment by SinSinati5** [comment]
I let the thing finish this time and it worked but there was a problem:

This was the error on the web gui:

Error: compilation timed out or failed. Please go to Discord support server for help.

This was the end of the log on the terminal:

b'50707 INFO: Building EXE from EXE-00.toc completed successfully.'
Exception in api.routes.payload.payload_generate: [Errno 2] No such file or directory: '/home/sina/github/byob/web-gui/buildyourownbotnet/output/SinSinati5/src/dist/windows/byob_win_x32_o3H.exe'

Any idea what this is?

**Comment by fireFerry** [comment]
This is probably because you're using Kali Linux. Kali is known to cause issues with docker and byob, that's why we recommend using ubuntu 20.04 lts.

**Comment by SinSinati5** [comment]
Any way to fix it?

**Comment by fireFerry** [comment]
Yes, by switching to Ubuntu 20.04 lts.

If you want to continue using Kali, I recommend joining the Discord server for support: https://discord.io/byob

**Comment by SinSinati5** [comment]
Alright thankyou

**Comment by anon-user-com** [comment]
> This is probably because you're using Kali Linux. Kali is known to cause issues with docker and byob, that's why we recommend using ubuntu 20.04 lts.

Wait a minute so if I use ubuntu instead of kali is more stable and will work.

**Comment by fireFerry** [comment]
Yes, that's correct.
