### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by anon-user-com** [malwaredllc/byob#525]
I want to use web-gui on hosting platforms like infitityfree, 000webhost, or heroku it's possible I think but can anyone help me if it's possible I want to do this because I don't want to do port forwarding on my router and I want to keep payloads for a long time and my ip maybe will change.

**Comment by fireFerry** [comment]
We don't support hosting byob on any vps-type of services.

**Comment by Lillythefox** [comment]
> 
> 
> I want to use web-gui on hosting platforms like infitityfree, 000webhost, or heroku it's possible I think but can anyone help me if it's possible I want to do this because I don't want to do port forwarding on my router and I want to keep payloads for a long time and my ip maybe will change.

they dont _support_ it but i have got I working on azure with this list of commands 

`sudo apt update && sudo apt install git 
git clone https://github.com/malwaredllc/byob.git
cd ./byob/web-gui
sudo apt install screen 
cd byob/web-gui 
(If it's your first time with byob on vps)
screen 
(Press enter when it shows you stuff)
./startup.sh
And when it asks to restart do then
Ctrl + A Ctrl + D
(But if you have run byob before on the vps then do)
screen -dmS python3 run.py
And to connect to it to see errors and stuff do 
screen -ls 
Look for your screen id then do
screen -r (screen id)
But with no brackets`
