### ISSUE TITLE
I am not able to execute my payload on target machine 

### ISSUE THREAD

**Issue by root-brownie** [malwaredllc/byob#526]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python version [e.g. 2.7, 3.7 etc]

**Additional context**

**Comment by fireFerry** [comment]
@malwaredllc Close please
