### ISSUE TITLE
Ngrok or Portmap.io

### ISSUE THREAD

**Issue by RocketNinja15** [malwaredllc/byob#531]
Would it be possible to use ngrok or Portmap.is to route the CC server without you having to port forward on your local router.

**Comment by uhuhuhuhuhuhuhuh** [comment]
could be possible but you would need to rewrite a bunch of stuff so yeah

**Comment by RocketNinja15** [comment]
> could be possible but you would need to rewrite a bunch of stuff so yeah

what would you have to re-write

**Comment by debian-user-france1** [comment]
> Would it be possible to use ngrok or Portmap.is to route the CC server without you having to port forward on your local router.

There is a command that finds out your IP. You can find it out by running it without internet. Then just comment that out and you can set your IP. The problem is you can't use ngrok unpaid because you only get 1 port.

**Comment by debian-user-france1** [comment]
You also can run 3 ngroks with a paid account and use iptables to redirect an ngrok port to 1337, then the next to 1338 etc

**Comment by RocketNinja15** [comment]
> You also can run 3 ngroks with a paid account and use iptables to redirect an ngrok port to 1337, then the next to 1338 etc

Wait what do you mean

**Comment by debian-user-france1** [comment]
First you would have to pay ngrok.

ngrok.io
