### ISSUE TITLE
All of my ports are open. But payload not working.

### ISSUE THREAD

**Issue by Lubuluk** [malwaredllc/byob#534]
1337-1338-1339 Are open. I Am checking them in the vm machine and in my pc they are open. But payloads are not working. Non of them.
![Screenshot_26](https://user-images.githubusercontent.com/95049683/143726788-3e7e81f6-9156-42be-a03a-241680e37490.png)

![Screenshot_27](https://user-images.githubusercontent.com/95049683/143726790-88f1d9ff-2c4d-4251-b089-e8babb404f37.png)

This are the logs that ı get on python payload. I Change 2 routers for this. And it didint work aswell. Before anyone asking. The ports are tcp/udp. And they are opening when ı run the web-gui.

 And btw if its help. When ı run windows payload. İts get 2 errors. And then shut it self. I See peoples payloads are not closing afther the run. They are keep running.

**Comment by Lubuluk** [comment]
And btw if its help. When ı run windows payload. İts get 2 errors. And then shut it self. I See peoples payloads are not closing afther the run. They are keep running.

**Comment by tpguy825** [comment]
On windows and this happens aswell

**Comment by neves8232** [comment]
Currently facing the same problem, it might be with the bridge network configuration over the VM, but till now didn't found a solution
