### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by ibex107** [malwaredllc/byob#535]
When I try to run a payload generated by the client.py script I always get this error.

ModuleNotFoundError: No module named 'numpy'

**Comment by luizmlo** [comment]
This error happens when python tries to execute something from a library that is not installed, in this case its numpy
To fix this you should install the missing library by running
python3 -m pip install numpy

**Comment by skill3472** [comment]
@luizmlo numpy might be there, and it **still can go undetected**. To fix that error if you make sure that numpy is in fact installed is checking if the python packages folder is in your system path _(if you are on linux, don't know anything about that on windows)_.
