### ISSUE TITLE
cant make a payload 

### ISSUE THREAD

**Issue by mariojojoni** [malwaredllc/byob#537]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
everytime i try to get payload i get a screen thet tells me that'' i broke sth 500'' 

**Desktop (please complete the following information):**
 - OS: [kali linux ]

**Comment by areno-dev** [comment]
> ### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.
> **Describe the bug** everytime i try to get payload i get a screen thet tells me that'' i broke sth 500''
> 
> **Desktop (please complete the following information):**
> 
> * OS: [kali linux ]

Exactly same happens with me ! I used it on Both "Black Arch" & "Ubuntu" But i am encountering same error everytime. Please Fix It !!!
