### ISSUE TITLE
Payloads errors: connection timed out 

### ISSUE THREAD

**Issue by Hiosaky** [malwaredllc/byob#539]
I'm having trouble generating payloads. I cannot create the ​​Windows and Linux executables. The only payload I can create is the python script, but when I try to run it I get a timeout error.

The error I got when trying to create binary payloads (Windows and Linux): 
![This is an image](https://i.ibb.co/pKF751g/foto.jpg)

The error I get when trying to run the payload python script:
![This is an image](https://i.ibb.co/6tqMMpt/screen.jpg)

What can is causing these problems? Is it necessary to allow any port?

**Comment by msm2005** [comment]
Im getting the same error I think its from the firewall, I forwarded the listening ports (4444,4445,4446,4447,4448) buit I get the same error or, (<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> )

**Comment by fireFerry** [comment]
You will need to port forward ports 1337-1339

**Comment by Hiosaky** [comment]
> You will need to port forward ports 1337-1339

With that I managed to solve the problem! Thanks.

**Comment by TONYDZ25** [comment]
Traceback (most recent call last):
  File "/home/tony/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/tony/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/tony/byob/web-gui/buildyourownbotnet/server.py", line 32, in <module>
    from .models import db
  File "/home/tony/byob/web-gui/buildyourownbotnet/models.py", line 2, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'
 

help pls
