### ISSUE TITLE
reformatting the payload seems to make it undetectable to all av providers

### ISSUE THREAD

**Issue by debian-user-france1** [malwaredllc/byob#544]
Reformatting the payload seems to make it undetectable to all av providers. Please add a randomizer to change the code a bit and add random spaces/print () commands to your generator! When will it get fixed haha :)?

**Comment by debian-user-france1** [comment]
https://www.virustotal.com/gui/file/ada432ee299449b8dad14ed5f72708a4b5c463ed1ac9a62d362c024aeba62923?nocache=1  -  my reformatted payload

**Comment by becktrack** [comment]
can you tell me exacly what you did like what changes did you adee and what reformatting you did so i can try adding this feature and make a pull request

**Comment by debian-user-france1** [comment]
It looks like that the Windows defender detects the default payload. I just added a line and for python3 a print ('Hello World') and for python2 print 'Hello World' (without brackets)

Then uploading to virustotal the file seems to go through but maybe virustotal doesn't give the AVs the needed information for advanced search..
