### ISSUE TITLE
web-gui dosnt start because of depencies errors (i guess)

### ISSUE THREAD

**Issue by k1llerfr0g22** [malwaredllc/byob#548]
After installing both requirements.txt's (byob-master\web-gui and byob-master\byob) i still get the "unable to locate directory containing user-installed packages".

I also installed some python flask libs manually that have been needed (i got some " ModuleNotFoundError: No module named '<package>' " errors). 
I got some numpy install errors but fixed.
I got some pycryptdome install errors, I installed pycryptdome manually ( `pip install pycryptodomex` ) 

Im using python version 3.9.9 on Windows (Build 19043)

I tested the command line version and it worked fine (i just started it and done nothing further).

sorry for the bad english im just a 14y/o german dude

**Comment by fireFerry** [comment]
The web-gui version of byob is Linux only, so you will need to use a vm or something else.

**Comment by k1llerfr0g22** [comment]
its fine because imo windows is bad, i only got 1 device with windows, all my other devices are on manjaro

**Comment by timmosaurusrex** [comment]
I am using a raspberry pi zero 2 w with the latest raspberry pi os lite and I have the same error. Does anyone know what I can do to fix that?
