### ISSUE TITLE
stagers.py getting deleted and returning invalid argument error

### ISSUE THREAD

**Issue by leonmissoul** [malwaredllc/byob#549]
When i run the client.py file with the correct arguments the proram returns a invalid argument error:
OSError: [Errno 22] Invalid argument: 'core/stagers.py'

I found out that the file stagers.py somehow gets deleted automatically when running client.py.
How is this possible and how can i resolve this?

**Comment by fireFerry** [comment]
This is probably being caused by antivirus software.
