### ISSUE TITLE
cant make windows executable payloads 

### ISSUE THREAD

**Issue by Kxawan** [malwaredllc/byob#550]
help me why i cant make payloads windows
b'docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.'
b"See 'docker run --help'."

**Comment by Kxawan** [comment]
and i use wsl in windows 10to use byob

**Comment by fireFerry** [comment]
Wsl isn't supported, I recommend you use something like a vm.

**Comment by Kxawan** [comment]
okay thank you
