### ISSUE TITLE
dll issue

### ISSUE THREAD

**Issue by Cie1Phantomh1ve** [malwaredllc/byob#551]
When I execute on test machines, I get this error: The procedure entry point GetDaylightFlag could not be located in the dynamic link library C:\Users\Username\AppData\Local\Temp\_MEI26522\ucrtbase.dll

the program fails every time.

**Comment by fireFerry** [comment]
You can ignore that warning, it has no effect on the payload

**Comment by Cie1Phantomh1ve** [comment]
the bot refuses to show up
also, adding ngrok port forwarding would be cool

**Comment by fireFerry** [comment]
Did you port forward?
And ngrok port forwarding wouldn't work, as byob requires 3 ports, and it would also make it easier to use byob maliciously, so feel free to add it yourself, but it won't be added in the main repo.

**Comment by Cie1Phantomh1ve** [comment]
oh,ok, that makes sense

**Comment by Cie1Phantomh1ve** [comment]
which ports do I need to forward?

**Comment by Lillythefox** [comment]
> Did you port forward? And ngrok port forwarding wouldn't work, as byob requires 3 ports, and it would also make it easier to use byob maliciously, so feel free to add it yourself, but it won't be added in the main repo.

I wouldn't say ngrok tunnelling would make it more malicious as ngrok keeps logs

**Comment by soham12246** [comment]
btw the gui is so damn cool

**Comment by nikoli0218** [comment]
Again it has already been used malicously ...just make the thing work already and stop wasting ppls time.

**Comment by winterrdog** [comment]
> Again it has already been used  ...just make the thing work already and stop wasting ppls time.

Hey @nikoli0218 ,
What's not working for u? I have seen a lot of your messages in other threads. 

What's the matter so that we can check what's wrong with the code?

**Comment by nikoli0218** [comment]
#1 (the biggest issue) the modules dont work at all i was told to recode them or use as a template. Im not a coder nor was this tool intended to make ppl learn coding. #2 I have asked multiple times if it is possible to imoort other modules and how they have to formated in order for them to work and I get no response ..it clearly states you can import modules on main page. #3 (this is on my end somewhere) I have it working fine on 1 router that both victim vm and attacker (kali) is on but the moment kali is on another network victim shows offline and it is not. #4 generating payloads...(this one is confusing) ..I have 2 routers tplink and arris ...everything is portforwarded generating payloads works on both, but when i generate payload while kali is connected to arris router and run it on victim vm that is connected to tplink i get no connection no or error msg just nothing. If i run same payload while kali is on tplink router with victim vm on tplink i get new connection then it goes offline after a min. ...i had it working with both on tplink router victim stayed online (modules still didnt work) ...i tried to set it up so i could test it while kali and victim on dif networks like i said and once i ran the arris generated payload on victim it seems to have broken something (as defined above) and nothing shows up on kali even though exe runs fine no irregular errors on victim i get no new connection msg no nothing
