### ISSUE TITLE
Devices not showing on Control Panel 

### ISSUE THREAD

**Issue by Idotechshit** [malwaredllc/byob#553]
Payloads are not showing on the control panel

**Comment by fireFerry** [comment]
Please give some more explanation, otherwise we cannot help you.

**Comment by gushteranin** [comment]
Hello again. I need help please. I install BYOB in virtual box. after the install i create payload. So the ip on the VM is [10.42.0.137](), i install the generated payload on the same machine where Virtual box is running, the windows 11 with Ip [10.42.0.55](), Virtual box ping that ip, and windows 10 ping the virtual machine. we have connection. I even open the controll panel from "victim machine" and i log in and download the payload from there.

 But victim machine does not show on the Bots menu.
Both machines sees eachother but no bots showing. 

Can you please help ?
Any advice will be great help.

**Comment by wheldman** [comment]
I'm having the same issue. Here's my setup:
1) pfSense running in a VirtualBox VM. Adapter 1 is set to bridged, adapter 2 is set to Internal network.
2) Kali Linux running BYOB in a VirtualBox VM. The web-gui is running. I have started the server with the command python3 server.py --host 192.168.1.100 --port 8080. (Do I need this command?)
3) Ubuntu Linux also running in a VirtualBox VM.  - I installed gufw and I'm allowing out ports 1337, 1338, and 1339 anywhere.
4) I downloaded the payload to the Ubuntu machine.
5) I run the payload with the command python3 <payload_name.py>. 

If I go back to the BYOB control panel on the Kali box and refresh it, I do not see the payload running on the target machine. 
Ultimately the payload times out.

**Comment by fireFerry** [comment]
server.py is for cli byob, so you're getting these messed up, and you need to make sure you port forward

**Comment by wheldman** [comment]
OK, two port-forwarding questions:

1) From Kali out yes?
2) Ports 1337-1339 yes?

**Comment by debian-user-france1** [comment]
Port 1337-1339 on attacker machine.

**Comment by wheldman** [comment]
Very good. Thank-you!! Oracle VirtualBox is super weird about port-forwarding. I have to set it up on the victim machine as well. What port? 80?

**Comment by debian-user-france1** [comment]
You do not have  to portforward on the victim network.

**Comment by wheldman** [comment]
OK, so I'm making progress. If, on the victim Ubuntu machine, I curl 10.0.2.15:1338 (the Kali machine running BYOB), I get a response. I also get a response from 1339, but **not** 1337, although the port-forwarding is enabled.

When I try to run the payload, I get this error: <urlopen error [Errno 111] connection refused>

Any ideas?

**Comment by wheldman** [comment]
I guess my big question now is this: What port is the victim machine using to connect to the attacking machine?

**Comment by fireFerry** [comment]
You need to port forward ports 1337-1339 to the machine you're hosting byob on.

**Comment by BlueCute** [comment]
All work fine. fireFerry
I just have one question. Can i run CMD on a victim machine from Byob console ? I ask because byob console has limited options.
Kind Regards

**Comment by debian-user-france1** [comment]
Ubuntu? Try ufw disable or ufw allow 1337

**Comment by debian-user-france1** [comment]
> I guess my big question now is this: What port is the victim machine using to connect to the attacking machine?

Nothing it just downloads the stager from 1337 the other thing from 1338 and 1339 is for comunication if I didn't miss anything.

**Comment by wheldman** [comment]
Well, if I use the command _netstat -lntu_ on Kali it shows me that 1337, 1338 and 1339 are indeed open (see first screenshot). If I disable the Ubuntu firewall altogether with _sudo ufw disable_ that command works (second screenshot). But if I then run _python3 <payload>_ it brings back two pages worth of errors (see screenshots 3 and 4). Doesn't seem to matter if I disable ufw or enable it, I get the same exact output from the Python script.

![Ubuntu disable firewall](https://user-images.githubusercontent.com/5065936/156888273-596d235a-9647-49f6-abfc-85946cae50e7.png)
![Ubuntu Python error 1](https://user-images.githubusercontent.com/5065936/156888275-a2fbd34f-4e83-4263-b863-6efb6a6ca952.png)
![Ubuntu Python error 2](https://user-images.githubusercontent.com/5065936/156888276-9c34ab34-0009-42d3-b050-d54fbd471f05.png)
![Kali Netstat output](https://user-images.githubusercontent.com/5065936/156888277-c4c8e2b9-706c-4253-a962-c6c16663dc04.png)
.

**Comment by debian-user-france1** [comment]
Execute this from ubuntu (victim): sudo nmap ATTACKER-IP

**Comment by wheldman** [comment]
Here's the response back
![Results of sudo nmap](https://user-images.githubusercontent.com/5065936/156892233-723a7ff7-b969-4244-80ca-62e11de6275e.png)
.

**Comment by wheldman** [comment]
Oh duh. I didn't realize you wanted me to replace ATTACKER-IP with the actual IP address of the attacker box. I'll get that screen output to you momentarily. This is interesting. Even though netstat -lntu on the Kali box shows ports 1337-1339 open, when I run sudo nmap <kali_ip> it only shows port 5000 open (see screenshot).
![Results of sudo nmap from Ubuntu box](https://user-images.githubusercontent.com/5065936/156893381-cdf9d5a6-c05b-4a3f-b5a2-f2e186a14053.png)

**Comment by debian-user-france1** [comment]
Either your ports aren't forwarded or something is blocking portforwarding. Just don't use Ubuntu I had the same problem too. Wait ur using kali Linux. Hmm.. I don't know - maybe the victim and the attacker aren't in the same Virtualbox network?

**Comment by wheldman** [comment]
Well, it's interesting that you mention that. VirtualBox has this thing called NAT Network. It allows port forwarding. From the VB main screen, if you click File -> Preferences -> Network you'll see that you can add a NAT network.

There are two reasons for using NAT network:

1. For some reason, if you just use NAT for both Kali and Ubuntu inside VB, the two machines pick up the _same_ IP addresses! You can test this yourself: bring up both Kali and Ubuntu configured with plain old NAT. Use the _ip addr_ command to see their addresses. They are both the same! Now set up the NAT Network thing for both and you will see that they pick up different addresses (from DHCP, of course). _However_ as far as I know, you cannot do port forwarding with just NAT in VB. You have to enable NAT Network. That's how I set up port forwarding on the Kali box. 
2. So both my Kali and Ubuntu VMs are running inside NAT Network. I can ping the Kali box from Ubuntu and vice-versa. If I run netstat inside Kali, it shows all of the required ports open. If I issue the _sudo nmap_ command from Ubuntu back to the attacker box, it only shows port 5000 open.

I think I'm getting closer. It has something to do with setting up port forwarding in VB. Not sure if I should use just NAT or NAT Network
![Port forwarding Kali](https://user-images.githubusercontent.com/5065936/156896763-73cc81db-0d7c-4a4f-afd9-be0c09e0cfa7.png)
?

**Comment by debian-user-france1** [comment]
It's not possible to have one IP with two OSes. You don't have one network. You must choose Nat Network, choose ONE NETWORK and do the portforwarding there.

**Comment by debian-user-france1** [comment]
Wait what did u do. I think it's fine but you have to set the correct guest IP and the correct Port (the same as the attacker port).
