### ISSUE TITLE
Windows executables won't generate (error 500)

### ISSUE THREAD

**Issue by tpguy825** [malwaredllc/byob#558]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
Whenever you go to create a windows executable, it returns an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Payloads'
2. Select 'Executable', 'Windows', 'x32'
3. Click 'Generate'

**Expected behaviour**
for it to generate an executable.

**Screenshots**
Steps 2 & 3
![steps 2 and 3](https://user-images.githubusercontent.com/75158953/156241904-b500416e-17dc-4e5d-857d-ea7fe7f6e031.png)
Step 4
![step 4](https://user-images.githubusercontent.com/75158953/156242009-b6bd3d46-561c-48e0-8f12-1baebcba37c2.png)

**Desktop (please complete the following information):**
 - OS: Windows (Running Docker Desktop 4.5.1)
 - Python version 2.7.18

**Comment by debian-user-france1** [comment]
I thought this project needs Python 3? You should do following to get your version: python3 --version

**Comment by tpguy825** [comment]
I gave up on the web gui and have switched to CLI as it actually works

**Comment by tpguy825** [comment]
> I thought this project needs Python 3? You should do following to get your version: python3 --version

3.10.2
