### ISSUE TITLE
windows executable keeps timing out 

### ISSUE THREAD

**Issue by ilancol** [malwaredllc/byob#559]
hello im trying to make a windows executable file but it keeps timing out and when i look back at the terminal :

(343 bytes written to output/ilancool1/src/byob_win_x32_gwW.py)
        Compiling executable...

b'007c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.'
b'007c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.'
b'007c:err:systray:initialize_systray Could not create tray window

Could someone tell me how to fix it!!

**Comment by tpguy825** [comment]
What are you runnig it on? (windows, linux, docker, etc)

**Comment by ilancol** [comment]
im running it in kali

**Comment by tpguy825** [comment]
Seems to suggest it's missing a driver or something

**Comment by foxwhite25** [comment]
I have found a simular situation, maybe this could help https://github.com/Winetricks/winetricks/issues/934#issuecomment-364886153
