### ISSUE TITLE
Colorama

### ISSUE THREAD

**Issue by Weberowsky** [malwaredllc/byob#563]
Hi, can you please replace colorama with normal color codes? I cant fricking install that colorama.. 
I tried manualy, from requirements, from setup.py even through adding relase to the path

**Comment by tpguy825** [comment]
What python version are you using?

**Comment by Weberowsky** [comment]
nvm, fixed that error, now i have "unable to locate directory containing
user-installed packages", windows 11 home python 3.10

niedz., 6 mar 2022 o 12:07 Toby Payne ***@***.***> napisał(a):

**Comment by tpguy825** [comment]
Try reinstalling python

**Comment by fireFerry** [comment]
Please use Linux for byob, preferably ubuntu 20.04 lts. Windows may cause issues.
