### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tpguy825** [malwaredllc/byob#564]
Whenever I try to run the generated python payload on my raspberry pi all I get is this. Any suggestions?
![image](https://user-images.githubusercontent.com/75158953/156922687-e5a5c5ad-0afb-4c9e-947f-2ab5642c3a6b.png)

I have searched all over google and nothing is working.

**Comment by fireFerry** [comment]
From what I can see, you're not currently in the `byob/web-gui` folder.
