### ISSUE TITLE
Client has no id.

### ISSUE THREAD

**Issue by sinaj2889** [malwaredllc/byob#566]
I just tested it with my smartphone but it didn't get a id so I couldn't reverse tcp. And is it possible to send commands to bots if the payload is not  running?

**Comment by RandomGamerVer** [comment]
If ur payload is still running on the target computer then just type "sessions" in the server terminal and it will show you all the connected bots and their number on the top, In ur case u just ran the first payload so it will be session ID 0 so just do "shell 0" and hopefully it will work. About the other question idk about that tbh

**Comment by soham12246** [comment]
i guess it's not made for android operating systems so may not work in your smartphone

**Comment by malwaredllc** [comment]
@sinaj2889 how did you test it on your smartphone? Do you have a python interpreter on your Android or did you use a third party tool to package the payload as an apk?

**Comment by soham12246** [comment]
can i do that too ?

**Comment by sinaj2889** [comment]
I ran byob CLI on Termux and then run the script on a new Session but now I get an id but if I use webcam image or keylogger it just doesn't do anything but I figured out how to get a tcp connection but the commands don't work so I used a python payload

**Comment by sinaj2889** [comment]
> i guess it's not made for android operating systems so may not work in your smartphone 

It worked but some commands don't but I think the modules are python too

**Comment by sinaj2889** [comment]
> @sinaj2889 how did you test it on your smartphone? Do you have a python interpreter on your Android or did you use a third party tool to package the payload as an apk?

Did no one of you never heard of Termux?
