### ISSUE TITLE
Important disclaimer

### ISSUE THREAD

**Issue by Lillythefox** [malwaredllc/byob#572]
Please add a disclaimer in large bold text (bigger than the current one) that BYOB is not associated with the IT army of Ukraine, as many of their telegram users are sending people here. If we don't we could draw some bad attention.
(This is not in support of Russia we are simply protecting the project from misuse)

**Comment by nikoli0218** [comment]
This should be the last thing answered or "fixed" considering the buggyness of the program already...this tool has already been used in the wild so why not just finish it and make it work ..the disclaimer is there which is enough if ppl want to use it maliciously they will find a way ..for ppl trying to learn it has just become a serious road block. And for ppl doing a school project it's creating failing scores. This tool has literally taken the wind from my sails and making me second guess my future in this field ...smh its dissapointing because like i have said in other threads it could be a great tool but its buggy and has no support. Well it does hace "support" if you can call it that. Only get help if it is convenient for him.." oh your using kali i recomend ubunt" end of support .

**Comment by Lillythefox** [comment]
> This should be the last thing answered or "fixed" considering the buggyness of the program already...this tool has already been used in the wild so why not just finish it and make it work ..the disclaimer is there which is enough if ppl want to use it maliciously they will find a way ..for ppl trying to learn it has just become a serious road block. And for ppl doing a school project it's creating failing scores. This tool has literally taken the wind from my sails and making me second guess my future in this field ...smh its dissapointing because like i have said in other threads it could be a great tool but its buggy and has no support. Well it does have "support" if you can call it that. Only get help if it is convenient for him.." oh your using kali i recomend ubunto" end of support .

First of all, BYOB uses docker to compile the windows executable and if you have ever used kali you will know it is a very stripped-down OS, it's not BYOB's fault that docker doesn't work. I have personally used the many times and it has always worked.

**Comment by timotiose** [comment]
> This should be the last thing answered or "fixed" considering the buggyness of the program already...this tool has already been used in the wild so why not just finish it and make it work ..the disclaimer is there which is enough if ppl want to use it maliciously they will find a way ..for ppl trying to learn it has just become a serious road block. And for ppl doing a school project it's creating failing scores. This tool has literally taken the wind from my sails and making me second guess my future in this field ...smh its dissapointing because like i have said in other threads it could be a great tool but its buggy and has no support. Well it does have "support" if you can call it that. Only get help if it is convenient for him.." oh your using kali i recomend ubunto" end of support .

First of you failing to read the README and undstanding how to work is it is not the devs fault, second the devs try there best if you want to flame them and say there not doing good enough then you try and do it, go on ill be watching.

**Comment by timotiose** [comment]
> Please add a disclaimer in large bold text (bigger than the current one) that BYOB is not associated with the IT army of Ukraine, as many of their telegram users are sending people here. If we don't we could draw some bad attention. (This is not in support of Russia we are simply protecting the project from misuse)

Dont think that necasary. What ukraine do with a free open source project is entierly up to them. This project has never (as far as im aware) and never will (as far as im aware) be associated with any online hacker groups.
