### ISSUE TITLE
Shell not working; Showing error invalid response

### ISSUE THREAD

**Issue by shivamswims456** [malwaredllc/byob#574]
![Capture](https://user-images.githubusercontent.com/18476828/159138501-217c47fc-9d0e-4065-8fc0-7fec59f4f971.PNG)

**Comment by shivamswims456** [comment]
Server ubuntu20
Client windows 10
Payload executeable and script (both)

**Comment by nikoli0218** [comment]
I am getting this same issue ..I get one command off then bot shows offline.


Pretty sure going to get response to this "use persistence module" even though the modules do not work. I have been tinkering with this for months to no end and get little to no help from support. Also when I get past 1 problem there's just another 1 waiting ...all this tool is doing is stealing time from ppl and maybe teaching ppl how to troubleshoot..which isn't a total loss troubleshooting is a must know in this world but how much is too much ..this tool needs some serious overhauling.
