### ISSUE TITLE
i cant connect 

### ISSUE THREAD

**Issue by Ewj71** [malwaredllc/byob#577]
I have byob running and all set up on my raspberry pi but i cant connect when i use the ip it gives me (http://127.0.0.1:5000)
i cant get in or if i try the local ip of the pi (192.168.0.86.5000)
it doesnt work what is the problem here?

**Comment by Ewj71** [comment]
idk but this may be a problem
![image](https://user-images.githubusercontent.com/69757318/160944591-627e4b0f-b66f-486a-820c-661b433f7b68.png)

**Comment by nikoli0218** [comment]
Pip3 install flask? See if that works.

**Comment by timotiose** [comment]
> Pip3 install flask? See if that works.

or pip3 install flask_login as its a sepreat module

**Comment by Birb02** [comment]
use pip3 to install flask then run sudo python3 run.py (Use py3)

**Comment by Persia-Shall-Rise** [comment]
I followed all the steps, but when I run "sudo python3 run.py" I get the following error 
![image](https://user-images.githubusercontent.com/109740130/180886641-729c1e68-6354-4798-b3d5-59f685b5283d.png)
