### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by nikoli0218** [malwaredllc/byob#578]
Modules not working not getting any help in discord either. Is this tool to learn botnets or to learn coding im confused. Support just gives generic answers and calls it good ...thats if your question even gets answered. Again this could be an immensely awsome tool could be if the bugs were worked out and had real support

**Comment by skyliner1123** [comment]
yeah i keep on getting ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by timotiose** [comment]
> yeah i keep on getting ModuleNotFoundError: No module named 'flask_bcrypt'

Have you at any moment considered typing 'pip install flask_bcrypt'
