### ISSUE TITLE
Not Able to run the client successfully.

### ISSUE THREAD

**Issue by XxNinjaGodxX** [malwaredllc/byob#58]
I have been testing the program on my computer (not a VM) and tried running 
`python client.py 192.168.1.x 8080`
and this is what I got returned:
`DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: numpy
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'numpy' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading numpy...
DEBUG:__main__:Trying to import 'numpy' as package from: 'http://192.168.1.251:8092/numpy/__init__.py'
INFO:__main__:[-] 'numpy' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'numpy' as module from: 'http://192.168.1.251:8092/numpy.py'
INFO:__main__:[-] 'numpy' is not a module (HTTP Error 404: File not found)
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:[-] Found locally!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama.initialise
DEBUG:__main__:Path: ['/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/colorama']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'colorama.initialise' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama.initialise...
DEBUG:__main__:Trying to import 'colorama.initialise' as package from: 'http://192.168.1.251:8092/colorama/initialise/__init__.py'
INFO:__main__:[-] 'colorama.initialise' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'colorama.initialise' as module from: 'http://192.168.1.251:8092/colorama/initialise.py'
DEBUG:__main__:[+] Importing 'colorama.initialise'
DEBUG:__main__:[+] Ready to execute 'colorama.initialise' code
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama.initialise.atexit
DEBUG:__main__:Path: ['http://192.168.1.251:8092/colorama/']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'colorama.initialise.atexit' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama.initialise.atexit...
INFO:__main__:[+] Module "colorama.initialise.atexit" loaded as a top level module!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama.initialise.contextlib
DEBUG:__main__:Path: ['http://192.168.1.251:8092/colorama/']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'colorama.initialise.contextlib' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama.initialise.contextlib...
INFO:__main__:[+] Module "colorama.initialise.contextlib" loaded as a top level module!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama.initialise.sys
DEBUG:__main__:Path: ['http://192.168.1.251:8092/colorama/']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'colorama.initialise.sys' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama.initialise.sys...
INFO:__main__:[+] Module "colorama.initialise.sys" loaded as a top level module!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama.initialise.ansitowin32
DEBUG:__main__:Path: ['http://192.168.1.251:8092/colorama/']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'colorama.initialise.ansitowin32' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama.initialise.ansitowin32...
DEBUG:__main__:Trying to import 'colorama.initialise.ansitowin32' as package from: 'http://192.168.1.251:8092/colorama/initialise/ansitowin32/__init__.py'
INFO:__main__:[-] 'colorama.initialise.ansitowin32' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'colorama.initialise.ansitowin32' as module from: 'http://192.168.1.251:8092/colorama/initialise/ansitowin32.py'
INFO:__main__:[-] 'colorama.initialise.ansitowin32' is not a module (HTTP Error 404: File not found)
`
Im just trying to connect my server to the client running on the same machine

**Comment by malwaredllc** [comment]
That debugging output looks normal - your server should be receiving a connection from the client.

**Comment by malwaredllc** [comment]
I just pushed some bug fixes yesterday, so try again with a fresh install and it should work - but let me know if the issue persists.
