### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by skyliner1123** [malwaredllc/byob#580]
i keep on getting this error "ModuleNotFoundError: No module named 'flask_bcrypt'" when i do "sudo python3 run.py"
what can i do

**Comment by Alexanderfem** [comment]
run `pip install flask_bcrypt`

**Comment by kittykatgoboom1** [comment]
> i keep on getting this error "ModuleNotFoundError: No module named 'flask_bcrypt'" when i do "sudo python3 run.py" what can i do

Honestly, it kinda feels like you're not even trying my guy. You could have easily googled that exact string ( if it was really even necessary ) and earned this answer yourself and started a habit of putting effort into solving your own problems before giving up and never trying.

**Comment by Ahnagle** [comment]
Powershell?
No in Kali linux. Why an I running this command? Sorry still kinda new and right now I am hacked and trying to figure out how to not just get rid of the attack. But also I'd like my pound of flesh and I'm still stumbling around in the dark about how to move forward. I just dont have a teacher. My college is for exactly this but Im only 2nd term into a bachelor's account. Could use some direction

On Apr 23, 2022 10:19 AM, Alexanderfem ***@***.***> wrote:
________________________________

[ EXTERNAL EMAIL: Do not click any links or open attachments unless you know the sender and trust the content. ]

________________________________

run pip install flask_bcrypt
