### ISSUE TITLE
hangs on installing build dependencies

### ISSUE THREAD

**Issue by antoniov00gaming** [malwaredllc/byob#581]
Newest kali build, raspberri pi 4 8gb ram.
docker is installed

**Comment by kittykatgoboom1** [comment]
There is a wiki that the dev put effort into for everyone's convenience. It's always a good habit to verify if the repo you're browing has a wiki or just rtfm if available. 

Here is the wiki section regarding installations issues regarding linux setups: https://github.com/malwaredllc/byob/wiki/Installing-Requirements-on-Linux

**Comment by alvin-tosh** [comment]
it hangs while installing dependencies and request a restart of the machine. then start over to completion but when running run.py i throws an traceback error
