### ISSUE TITLE
i cant able to complete the installation of requirements.txt in web-gui folder

### ISSUE THREAD

**Issue by ReddyKousic** [malwaredllc/byob#589]
![image](https://user-images.githubusercontent.com/85285392/174522777-b4b50753-a23d-4621-a75c-6785a588c6f1.png)

**Comment by RusBigLeba** [comment]
Check this out
[a similar case](https://stackoverflow.com/questions/71870382/failed-to-build-wheel-for-opencv)
It might be helpful.
