### ISSUE TITLE
executable payload wont generate

### ISSUE THREAD

**Issue by HangWithCmm** [malwaredllc/byob#594]
no matter how long a leave it after a while the progress bar disappears and there no payload

**Comment by xiongzhenggang** [comment]
@HangWithCmm  Is there some errorlog?

**Comment by HangWithCmm** [comment]
I think I found the issue it’s because I don’t have ports 1337 to 1339 forwarded on my wifi but I don’t do that. Is there some other way to forward those ports without having to do it on my actual Wifi?

**Comment by Kalvelign** [comment]
ngrok.io is the solution for using backdoor and stuff without opening port on nat/firewall

**Comment by HangWithCmm** [comment]
@Kalvelign  How would i do that?

**Comment by Kalvelign** [comment]
look on youtbe there is plenty youtube video on how to use it, is quiet eazy and strait fordward

**Comment by HangWithCmm** [comment]
@Kalvelign ok thank you do you have any video recommendations

**Comment by Kalvelign** [comment]
this man https://youtu.be/DCxt9SAnkyc is using it to expose a website to the internet but is the same process for your backdoor on the backdoor control server port ("one of the two you need to open check the docs")

**Comment by HangWithCmm** [comment]
@Kalvelign So would i just do "ngrok http <port>" also what ports do i need to do?

**Comment by Kalvelign** [comment]
actully you need a tcp tunnel so is more "ngrok tcp" and for the port you need to lookup what port does byob use flr cotrolling backdoor because one is for 1ccessing the ui and the other is for controlling the backdoor

**Comment by HangWithCmm** [comment]
Are there anyother command or just "ngrok tcp" also do i need to tcp the port byob web gui is running on?

**Comment by HangWithCmm** [comment]
@Kalvelign

**Comment by HangWithCmm** [comment]
@Kalvelign Are there any other commands or just "ngrok tcp" also do i need to tcp the port byob web gui is running on?

**Comment by Kalvelign** [comment]
you need to specified the port on where the c2 og byob is running you can see example of the command here : https://ngrok.com/docs/secure-tunnels#tcp-remote-addr

**Comment by HangWithCmm** [comment]
@Kalvelign im confused what do i need to do???

**Comment by Kalvelign** [comment]
"ngrok tcp 1337 " or the port you need to fordward

**Comment by HangWithCmm** [comment]
@Kalvelign Ok thank you for all your help

**Comment by Kalvelign** [comment]
np ! :)
