### ISSUE TITLE
unable to locate directory containing user-installed packages

### ISSUE THREAD

**Issue by alvin-tosh** [malwaredllc/byob#595]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python version [e.g. 2.7, 3.7 etc]

**Additional context**
![byob](https://user-images.githubusercontent.com/13796386/178260561-09812a65-b65e-499a-8088-a1f3333fc53f.png)

**Comment by GoldenEagle75** [comment]
I had the same problem but found the solution in another issue: https://github.com/malwaredllc/byob/issues/500#issuecomment-955140803
