### ISSUE TITLE
PayLoads + Ports

### ISSUE THREAD

**Issue by IDontGetIt22** [malwaredllc/byob#599]
Hello,
I am New to all of this so i hope i do nothing wrong.
I Read about the port thing but how do i know what port i need to forward?
Second thing is when i Creat Payloads its just loading and after that there is no new Payload in the bottom menu.
Just the Python Payload is working for creation.

The Error when i try to install the Python Payload
![code](https://user-images.githubusercontent.com/110306380/181947287-a603292d-c1e5-4b99-bc7d-656928d4313b.png)

The Ips i get 
![ips](https://user-images.githubusercontent.com/110306380/181947451-13099e2c-f1ef-4f26-8f9e-faf62008d0bf.png)

Thank you in Advance.
And pls i am an 100% Idiot so if some one know explain it like you would try to teach a 5 year old.

Brg

**Comment by cyb3rspace** [comment]
Having the exact same issue. Still not fixed.

**Comment by alphaO4** [comment]
Hey
It seems like something is blocking the connection hence the  "Connection refused"

Did you Port Forward the port on your receiving server? 
If not there are plenty of resources online. Just google "Name of your router + port forwarding".

**Comment by inepts** [comment]
I have the same situation
