### ISSUE TITLE
BYOB fails to start because of "unbound_message" error

### ISSUE THREAD

**Issue by marcosimioni** [malwaredllc/byob#604]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
Launching BYOB with `python3 run.py` fails to start because of a Flask `unbound_message` error.

**To Reproduce**
1. Follow installation instructions and prep with `startup.sh`, reboot
2. Run BYOB with `python3 run.py`
3. Observe it fails with an `unbound_message` error, see screenshot below.

**Expected behavior**
Shouldn't fail.

**Screenshots**
<img width="742" alt="image" src="https://user-images.githubusercontent.com/22682005/186115613-674884cf-31af-4194-a3d9-c4973d989993.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Python version 3.8.10

**Additional context**
Solved by downgrading Flask to 2.1.3 with `pip install flask==2.1.3`.
Should probably pin it in the requirements file.

**Comment by Tenshiiiiii** [comment]
![image_2022-10-05_112235905](https://user-images.githubusercontent.com/111651613/193974593-149e1f04-b7af-46a8-a8e4-a58c3545e483.png)

do you get this after installing?

**Comment by Zaeem20** [comment]
> ![image_2022-10-05_112235905](https://user-images.githubusercontent.com/111651613/193974593-149e1f04-b7af-46a8-a8e4-a58c3545e483.png)
> 
> do you get this after installing?

change permissions of all files by chmod

**Comment by xpg14** [comment]
> > ![image_2022-10-05_112235905](https://user-images.githubusercontent.com/111651613/193974593-149e1f04-b7af-46a8-a8e4-a58c3545e483.png)
> > do you get this after installing?
> 
> change permissions of all files by chmod

how do i do that

**Comment by Solidbeast42** [comment]
> > ![image_2022-10-05_112235905](https://user-images.githubusercontent.com/111651613/193974593-149e1f04-b7af-46a8-a8e4-a58c3545e483.png)
> > do you get this after installing?
> 
> change permissions of all files by chmod

how do I do that

**Comment by Karalojko** [comment]
Just run it with admin perms: sudo python3 run.py

**Comment by Solidbeast42** [comment]
> Just run it with admin perms: sudo python3 run.py

didn't work

**Comment by Zaeem20** [comment]
just change it using chmod
eg: chmod 700 filename

@Solidbeast42

**Comment by Solidbeast42** [comment]
> 

that dident work 💀

**Comment by Zaeem20** [comment]
can you show me ss the list the files with permission use `ls -l`

**Comment by Solidbeast42** [comment]
> can you show me ss the list the files with permission use `ls -l`

![image](https://user-images.githubusercontent.com/82831433/205468030-72017c4c-7ea5-4732-a988-57f1b251594e.png)

**Comment by Zaeem20** [comment]
change permissions of files in `buildyourownbotnet's` directory
by simply doing `chmod 777 *`

**Comment by Solidbeast42** [comment]
> ls -l

that didn't work

**Comment by Zaeem20** [comment]
may be you are not doing it correctly

**Comment by Solidbeast42** [comment]
> may be you are not doing it correctly

I did follow instructions but Idrk

**Comment by MrBanane6969** [comment]
Reallly No Normal issues?
do you even know how to use Linux???
