### ISSUE TITLE
No module named 'flask_bcrypt'

### ISSUE THREAD

**Issue by Jamesnoblade** [malwaredllc/byob#605]
I can't start byob
Traceback (most recent call last):
  File "/home/kali/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/kali/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/kali/byob/web-gui/buildyourownbotnet/server.py", line 32, in <module>
    from .models import db
  File "/home/kali/byob/web-gui/buildyourownbotnet/models.py", line 2, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by frankzengjj** [comment]
Have you tried install flask_bcrypt? such as `pip install flask-bcrypt`

**Comment by M1cr0K1ller** [comment]
I have the same issue. and i have installed flask_bcrypt using `pip install flask-bcrypt`

**Comment by Lviru5** [comment]
Perform these things to clear all issues 👍🏻 : 

1. install pip3 (Which doesn't come with python3)
    
sudo apt-get update
sudo apt install python3-pip

2. Change the path of pip3 (Virtualenv path issue)

echo "export PATH=\"/home/mark/.local/bin:\$PATH\"" >> ~/.bashrc && source ~/.bashrc

3.  Change some versions in requirements.txt (Compatibility issues)

Change  : Werkzeug==2.0.0    TO   Werkzeug==2.2.2


After doing all the above then :  Run => Sudo ./startup.sh

It'll take some time and start on port 5000 😄

**Comment by Lviru5** [comment]
Perform these things to clear all issues 👍🏻 :

install pip3 (Which doesn't come with python3)
sudo apt-get update
sudo apt install python3-pip

Change the path of pip3 (Virtualenv path issue)
echo "export PATH="/home/mark/.local/bin:$PATH"" >> ~/.bashrc && source ~/.bashrc

Change some versions in requirements.txt (Compatibility issues)
Change : Werkzeug==2.0.0 TO Werkzeug==2.2.2

After doing all the above then : Run => Sudo ./startup.sh

It'll take some time and start on port 5000 😄

**Comment by ron123493** [comment]
I have the same problem and this solution didn't helped me. Did someone solved that?

**Comment by Zaeem20** [comment]
this tool won't work in python 3.10 or higher, it tried it in my pyenv instance,
@ron123493 just check your python version, and do pip install flask_bcrypt accordingly

**Comment by MrBanane6969** [comment]
Github-actions? WHAT ARE YOU DOING HERE
