### ISSUE TITLE
The web gui isn't working

### ISSUE THREAD

**Issue by SixteenAngels** [malwaredllc/byob#610]
"/home/don/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/don/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/don/byob/web-gui/buildyourownbotnet/server.py", line 32, in <module>
    from .models import db
  File "/home/don/byob/web-gui/buildyourownbotnet/models.py", line 2, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by Inplex-sys** [comment]
try `pip3 install flask-bcrypt`

**Comment by Donfrass** [comment]
Got the same error

**Comment by Donfrass** [comment]
Does it work on kali ?

**Comment by garix-png** [comment]
yes it does, i tried it

**Comment by Donfrass** [comment]
> Does it work on kali ?

can i contact you via email

**Comment by RhochR** [comment]
I have the same issue. Can anyone help me please?
