### ISSUE TITLE
Sessions are displayed but no actions can be performed

### ISSUE THREAD

**Issue by g00gl3d** [malwaredllc/byob#614]
so I succeeded in configuring byob on graphical web interface, I can generate payload, now here is my problem: 

after generating a payload I launch it on my windows 10 VM
the session is displayed successfully in the options I have administrator rights etc, but when I try to make screenshots and other trying all the options nothing works nothing applies, so I decided to look at the logs of my actions it displays me "none" in the result, when I make commands via the shell it does not work, basically it's like nothing applies

![image](https://user-images.githubusercontent.com/116079531/196616815-ab863d3b-c362-408e-a88c-e4d72b9bf07f.png)

**Comment by DHax132** [comment]
I have the same problem
