### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by 0067sdsm** [malwaredllc/byob#619]
when i try and run the requirements.txt this happens:
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

and when i try and run the get-docker.sh this happens:
# Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.

and when i run the run.py this happens:
Traceback (most recent call last):
  File "/home/sdsm0067/mytools/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/sdsm0067/mytools/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/sdsm0067/mytools/byob/web-gui/buildyourownbotnet/server.py", line 32, in <module>
    from .models import db
  File "/home/sdsm0067/mytools/byob/web-gui/buildyourownbotnet/models.py", line 2, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by 0067sdsm** [comment]
and then this:
python3 run.py
unable to locate directory containing user-installed packages

**Comment by Karalojko** [comment]
> and then this: python3 run.py unable to locate directory containing user-installed packages

try installing the packages manually (search up a guide if u dont know how to do it)
ubuntu 20.04 and python version 3.7.9 is recommended

**Comment by 0067sdsm** [comment]
Ok thanks, did any1 else have this error?

**Comment by sweeder** [comment]
I'm having this issue now, I almost completed the install but I keep getting this error message:
  File "/home/$USER/Desktop/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app

**Comment by Gazirovich** [comment]
same issue

**Comment by 0067sdsm** [comment]
I made it work by using ubuntu btw guys
