### ISSUE TITLE
b'0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.' b'0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.' b'0050:err:systray:initialize_systray Could not create tray window' b"  DEPRECATION: WMI is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559"

### ISSUE THREAD

**Issue by HariPineapple** [malwaredllc/byob#622]
b'0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.'
b'0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.'
b'0050:err:systray:initialize_systray Could not create tray window'
b"  DEPRECATION: WMI is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559"

**Comment by youssefallali** [comment]
i also have the same problem i tried everything but didn't work any help please guys ?

**Comment by Rexicon226** [comment]
same problem

**Comment by georgepelal** [comment]
same problem but i also get the numpy error and I think they are related
