### ISSUE TITLE
unable to locate directory containing user-installed packages

### ISSUE THREAD

**Issue by darkviiolet** [malwaredllc/byob#625]
I keep getting this whenever i run this command

`sudo python3 run.py`

even tho i didnt get any errors with the /.startup.sh

I'm using a Linux Kali 2022.3

**Comment by Karalojko** [comment]
BYOB was made to work in ubuntu 20.04

**Comment by darkviiolet** [comment]
isn't there a way i can add it to kali linux?

**Comment by kyron500** [comment]
I managed to get the web-gui running under Kali Linux 2022.3.
You can run it using Anaconda and create a Python 3.7.9 Environment.

Then, into the web-gui folder, change the requirements.txt to this:

Werkzeug
SQLAlchemy
flask==2.2.0
flask_session
flask_wtf
Flask_SQLAlchemy
Flask_Login
Flask_Bcrypt
flask_mail
wtforms
mss==3.3.0
WMI==1.4.9
numpy==1.21.5
pyxhook==1.0.0
twilio==6.14.0
colorama==0.3.9
requests==2.20.0
pycryptodomex==3.8.1
py-cryptonight==1.0.0
opencv-python;python_version>'3'
pypiwin32==223;sys.platform=='win32'
pyHook==1.5.1;sys.platform=='win32'

hope it works for you

**Comment by darkviiolet** [comment]
@kyron500 any idea what can be the issue causing stopping me from generating working payload?

**Comment by swordphish3d** [comment]
your a madcunt... thankyou fixed for me on ubuntu

**Comment by qhaved** [comment]
kyron500's fix didn't work for me
