### ISSUE TITLE
problem plese help  ImportError: No module named flask

### ISSUE THREAD

**Issue by TONYDZ25** [malwaredllc/byob#627]
└─# sudo python2 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/tony/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
ImportError: No module named flask

**Comment by kyron500** [comment]
I managed to get this running using Python 3.7.9 on Windows 10 64bit (https://www.python.org/downloads/release/python-379/)
Also, I manually installed PyHook using the whl file:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook --> _pyHook-1.5.1-cp37-cp37m-win_amd64_ --> pip install .\pyHook-1.5.1-cp37-cp37m-win_amd64.whl

And I did some changes in the requirements file inside the _web-gui_ folder (_requirements.txt_):

Werkzeug
SQLAlchemy
flask==2.2
flask_session
flask_wtf
Flask_SQLAlchemy
Flask_Login
Flask_Bcrypt
flask_mail
wtforms
mss==3.3.0
WMI==1.4.9
numpy==1.17.3
pyxhook==1.0.0
twilio==6.14.0
colorama==0.3.9
requests==2.20.0
pycryptodomex==3.8.1
py-cryptonight==0.3.4
opencv-python;python_version>'3'
pypiwin32==223;sys.platform=='win32'
pyHook==1.5.1;sys.platform=='win32'

hopefully it will help you
