### ISSUE TITLE
Cant make "x32, amd64 and i386" executables

### ISSUE THREAD

**Issue by kittttttttttttttty** [malwaredllc/byob#629]
So when I try to make x32, amd64, and i386 executables it first shows this error message:
b"Unable to find image 'nix-amd64:latest' locally"
b"docker: Error response from daemon: pull access denied for nix-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
Then it just spams b' '
can anyone help out?
here is an image and by the way, I am on a mac.
<img width="1440" alt="thin" src="https://user-images.githubusercontent.com/80906572/206792712-d931841a-437e-451f-9a45-d1bf632e3e19.png">

**Comment by Areno-Dev** [comment]
bro i got the same problem on kali linux.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/90553873/207884502-e08489df-42af-4d47-981c-80d3d037e712.png">

**Comment by MaciejkaG** [comment]
bump

**Comment by originalbokbok** [comment]
sorry, this may sounds really elementary but have you tried logging in to Docker? I cant remember exact command, something along the lines of

`docker login -u [username] -p [password]`

a quick search on google or `docker --help` will give the definite syntax.

another possibility is that you don't have docker hub running. Nothing can be done in a docker sense without the hub daemon running in the background.

Hopefully just something that simple?

**Comment by Prasoon-Rai** [comment]
> sorry, this may sounds really elementary but have you tried logging in to Docker? I cant remember exact command, something along the lines of
> 
> `docker login -u [username] -p [password]`
> 
> a quick search on google or `docker --help` will give the definite syntax.
> 
> another possibility is that you don't have docker hub running. Nothing can be done in a docker sense without the hub daemon running in the background.
> 
> Hopefully just something that simple?

Yes I have tried that but still no luck...
