### ISSUE TITLE
--freeze file !

### ISSUE THREAD

**Issue by AraFurieux** [malwaredllc/byob#63]
I have use the -freeze all is good ... when i test it on windows he doesn't cpt the exe file and when i set .exe ... the version is not adapted 
[>] Modules
	Adding modules... -(3 modules added to client)

[>] Imports
	Adding imports...- (26 imports from 3 modules)

[>] Payload
	Encrypting payload.../ (117,292 bytes increased to 156,408 bytes (33.0% larger)                        
	Uploading payload... - (hosting payload at: http://192.168.182.7:1338//payloads/wI0.py)

[>] Stager
	Uploading stager...  (hosting stager at: http://192.168.182.7:1338//stagers/wI0.py)

[>] Dropper
	Writing dropper...  (207 bytes written to byob_wI0.py)
	Compiling executable...
513 INFO: PyInstaller: 3.3.1
513 INFO: Python: 2.7.15+
513 INFO: Platform: Linux-4.18.0-parrot10-amd64-x86_64-with-Parrot-4.2.2-stable
627 INFO: UPX is available.
643 INFO: Extending PYTHONPATH with paths
['/home/boris/byob', '/home/boris/byob/byob']
644 INFO: Will encrypt Python bytecode with key: =A=Y;7wnKLFMN7BW
644 INFO: Adding dependencies on pyi_crypto.py module
644 INFO: checking Analysis
645 INFO: Building Analysis because out00-Analysis.toc is non existent
645 INFO: Initializing module dependency graph...
647 INFO: Initializing module graph hooks...
663 INFO: Analyzing hidden import 'base64'
2693 INFO: Analyzing hidden import 'json'
2808 INFO: Analyzing hidden import 'zlib'
2808 INFO: Analyzing hidden import 'urllib'
3408 INFO: Analyzing hidden import 'uuid'
3530 INFO: Analyzing hidden import 'numpy'
6226 INFO: Processing pre-safe import module hook   _xmlplus
6664 INFO: Processing pre-find module path hook   distutils
13101 INFO: Processing pre-safe import module hook   six.moves
22020 INFO: Analyzing hidden import 'colorama'
22133 INFO: Analyzing hidden import 'requests'
26949 INFO: Analyzing hidden import 'Crypto.Cipher._AES'
27102 INFO: running Analysis out00-Analysis.toc
27142 INFO: Caching module hooks...
27146 INFO: Analyzing /home/boris/byob/byob/byob_wI0.py
27167 INFO: Loading module hooks...
27167 INFO: Loading module hook "hook-distutils.py"...
27184 INFO: Loading module hook "hook-sysconfig.py"...
27190 INFO: Loading module hook "hook-xml.py"...
27191 INFO: Loading module hook "hook-httplib.py"...
27199 INFO: Loading module hook "hook-pydoc.py"...
27201 INFO: Excluding import 'Tkinter'
27203 INFO:   Removing import of Tkinter from module pydoc
27203 INFO: Loading module hook "hook-encodings.py"...
27720 INFO: Loading module hook "hook-_tkinter.py"...
27904 INFO: checking Tree
27904 INFO: Building Tree because out00-Tree.toc is non existent
27904 INFO: Building Tree out00-Tree.toc
27955 INFO: checking Tree
27955 INFO: Building Tree because out01-Tree.toc is non existent
27955 INFO: Building Tree out01-Tree.toc
27969 INFO: Loading module hook "hook-xml.dom.domreg.py"...
27984 INFO: Loading module hook "hook-pkg_resources.py"...
28536 INFO: Processing pre-safe import module hook   win32com
28804 INFO: Loading module hook "hook-requests.py"...
29065 INFO: Loading module hook "hook-certifi.py"...
29067 INFO: Loading module hook "hook-setuptools.py"...
29132 INFO: Loading module hook "hook-cryptography.py"...
29404 INFO: Loading module hook "hook-pytest.py"...
30723 INFO: Loading module hook "hook-numpy.core.py"...
32186 INFO: Looking for ctypes DLLs
33029 INFO: Analyzing run-time hooks ...
33043 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
33048 INFO: Including run-time hook 'pyi_rth__tkinter.py'
33050 INFO: Including run-time hook 'pyi_rth_pkgres.py'
33073 INFO: Looking for dynamic libraries
34655 INFO: Looking for eggs
34656 INFO: Python library not in binary dependencies. Doing additional searching...
34753 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
34769 INFO: Warnings written to /home/boris/byob/byob/build/byob_wI0/warnbyob_wI0.txt
34864 INFO: Graph cross-reference written to /home/boris/byob/byob/build/byob_wI0/xref-byob_wI0.html
35076 INFO: checking PYZ
35077 INFO: Building PYZ because out00-PYZ.toc is non existent
35077 INFO: Building PYZ (ZlibArchive) /home/boris/byob/byob/build/byob_wI0/out00-PYZ.pyz
37004 INFO: Building PYZ (ZlibArchive) /home/boris/byob/byob/build/byob_wI0/out00-PYZ.pyz completed successfully.
37145 INFO: checking PKG
37145 INFO: Building PKG because out00-PKG.toc is non existent
37145 INFO: Building PKG (CArchive) out00-PKG.pkg
52497 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
52554 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-64bit/run
52554 INFO: checking EXE
52554 INFO: Building EXE because out00-EXE.toc is non existent
52554 INFO: Building EXE from out00-EXE.toc
52583 INFO: Appending archive to ELF section in EXE /home/boris/byob/byob/dist/byob_wI0
52898 INFO: Building EXE from out00-EXE.toc completed successfully.
(28,064,144 bytes saved to file: /home/boris/byob/byob/dist/byob_wI0)

Thank you

**Comment by malwaredllc** [comment]
You cannot cross-compile executables for different platforms.

To compile a PE executable for Windows (*.exe), you must run `client.py` on a Windows machine.

You compiled an ELF executable because you ran `client.py` on a Linux machine.
