### ISSUE TITLE
ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by ArabicCat** [malwaredllc/byob#631]
OS: ubuntu 22.04 LTS
I do: python3 run.py and then i get this:

error:
Traceback (most recent call last):
  File "/home/lakaka/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/lakaka/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by plosee** [comment]
do pip install flask

**Comment by ArabicCat** [comment]
> do pip install flask

already did that but does not work

**Comment by plosee** [comment]
try reinstalling flask or updating python if its outdates. some modules work only on older python versions and flask might be one of them. if you dont wanna update python then look for another flask version that support the current version you have.
