### ISSUE TITLE
Problem with windows : __init__.py

### ISSUE THREAD

**Issue by AraFurieux** [malwaredllc/byob#64]
we have launch the setup.py and  all is ok ! but with __init__.py ... Error ... can you help me please ? Thank you !

**Comment by AraFurieux** [comment]
**C:\Users\TEST\Desktop\byob-master\byob>py** __init__.py
Traceback (most recent call last):
  File "__init__.py", line 137, in <module>
    main()
  File "__init__.py", line 135, in main
    exec("import {}".format(module))
  File "<string>", line 1, in <module>
  File "C:\Users\FLSTUDIO\Desktop\byob-master\byob\client.py", line 93, in <module>
    import colorama
ImportError: No module named colorama

**Comment by AraFurieux** [comment]
We don't have the requirements-winodws.txt ... but requirements.txt well and pyphok 1.5.1 will not installing

**Comment by malwaredllc** [comment]
Run `pip install -r requirements.txt` and then try again.

**Comment by AraFurieux** [comment]
I have test it .. it doesn't work

**Comment by AraFurieux** [comment]
C:\Users\FLSTUDIO\Desktop\byob-master\byob>pip install -r requirements.txt
Collecting mss==3.3.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d1/bc/1965b94c015666f0dce53248e219802137cfe3927109843706d7c4c48f78/mss-3.3.0-py2.py3-none-any.whl
Collecting WMI==1.4.9 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/03/2d/cbf13257c0115bef37b6b743758411cec70c565405cbd08d0f7059bc715f/WMI-1.4.9.zip
Collecting numpy==1.15.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/96/d6/53a59338c613e0c3ec7e3052bbf068a5457a005a5f7ad4ae005167c3597e/numpy-1.15.2-cp37-none-win_amd64.whl
Collecting pyxhook==1.0.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/70/d1/8f56e13b002502ad85975f2dcebb5d1026551e34cafc77ae70a294a67eed/pyxhook-1.0.0.tar.gz
Collecting twilio==6.14.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/4c/b5/f341339851a53a76dd476979f5a67595990d9d45417b1cd65c140154ae4b/twilio-6.14.0-py2.py3-none-any.whl
Collecting colorama==0.3.9 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting requests==2.18.4 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting PyInstaller==3.3.1 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz
Collecting opencv-python==3.4.3.18 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/82/de/32bdf7b20f9d08008dda2073a48141ab4ad829deaca7aa660e9c64d02dae/opencv_python-3.4.3.18-cp37-cp37m-win_amd64.whl
Collecting pyHook==1.5.1 (from -r requirements.txt (line 10))
  Could not find a version that satisfies the requirement pyHook==1.5.1 (from -r requirements.txt (line 10)) (from versions: )
No matching distribution found for pyHook==1.5.1 (from -r requirements.txt (line 10))
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by AraFurieux** [comment]
![capture](https://user-images.githubusercontent.com/42409531/47271759-60b5fa80-d57c-11e8-9976-30faa2f2a6e1.PNG)

**Comment by AraFurieux** [comment]
C:\Users\FLSTUDIO\Desktop\byob-master\byob>pip install colorama --user
Collecting colorama
  Using cached https://files.pythonhosted.org/packages/0a/93/6e8289231675d561d476d656c2ee3a868c1cca207e16c118d4503b25e2bf/colorama-0.4.0-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.4.0

C:\Users\FLSTUDIO\Desktop\byob-master\byob>py server.py
Error: missing package 'colorama' is required

**Comment by malwaredllc** [comment]
You must be using python3 because `urllib2` is part of the python2 standard library.

Use python2 and it will work.
