### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by User-790** [malwaredllc/byob#644]
Has anyone else been getting this error? 
I am using python3 and has been updated right before this installation. Any suggestions?

 ```
# note: this error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
```

**Comment by LordGryJoy** [comment]
getting same err can anyone help fix my issue .

**Comment by bmkay** [comment]
Same here.  Seems to be related to the PIP version used by the docker image and a lack of backwards compatibility.  However, I rolled-back my PIP to version 21.0 and it's still not installing the packages.
I also tried manually installing the packages using: /path/to/pip install -r requirements.txt but that also didn't work.  It seems this GIT hasn't been maintained for a while, resulting in version errors.

**Comment by georgepelal** [comment]
i also get this

**Comment by RavageHunter** [comment]
me 4

**Comment by Rohit7777777** [comment]
Even I get the same error it say's the following:
  note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
