### ISSUE TITLE
Bot is connected but nothing seems to work.

### ISSUE THREAD

**Issue by fasma89** [malwaredllc/byob#648]
I have set up byob and my web server ,i have run the payload to my local machine which has Windows 10 running.
Machine is connected as a Bot , but when i try to shell some commands i get "Error: client returned invalid response: "0"
Basically Presistence nor every module seems to work to remote machine, and I always get "0" response back. What am I doing wrong?

-  Byob Server:
 - OS: [e.g. Ubuntu 20.04]
 - Python version [3.8]]

**Comment by TheCatGuy12321** [comment]
I'm also getting this error.

**Comment by TheCatGuy12321** [comment]
Maybe try disabling antivirus?

**Comment by rotkohl69** [comment]
Facing the same issue. Server also on Ubuntu, client is windows 11.
