### ISSUE TITLE
Windows payload generator only has x32 bit option.

### ISSUE THREAD

**Issue by Raccoon727** [malwaredllc/byob#652]
I installed byob ran the startup.sh script and everything but in the web graphical user interface at localhost:5000 at the Payloads section when I go to generate a Windows payload it only has 32 bit option. When I go to Linux payload it has x32 bit and amd64 architectures but in Windows it only has 32 bit. If the target Windows 10 operating system is 64 bit will it work ? How can i get other architectures to show in the options?

**Comment by RhochR** [comment]
It will work on x64, even if you just select x32.
