### ISSUE TITLE
ModuleNotFoundError: 'flask_bcrypt

### ISSUE THREAD

**Issue by FreydUA** [malwaredllc/byob#654]
I have already download flask bcrypt but still it isnt working.
![image](https://user-images.githubusercontent.com/113863137/226473149-2d65ebc6-9a9f-458f-b950-72738377f44f.png)
Also I tried same issues answers but nothing...
Help Pls

**Comment by KosteQ314** [comment]
I have the same error tried reinstalling flask and updating python but still the same problem I hope they'll fix it soon

**Comment by FreydUA** [comment]
so I resolve it by trying:

pip install flask-bcrypt
pip3 install flask-bcrypt
pipenv install flask-bcrypt

**Comment by Jammstheshreklord** [comment]
simply use 1 brain cell to typr `sudo apt install flask_bcrypt` then run the startup.sh again with `sudo ./startup.sh`
