### ISSUE TITLE
Pip problem 

### ISSUE THREAD

**Issue by AraFurieux** [malwaredllc/byob#66]
I have a problem with pip (i have the 2.7.15)  see : C:\Users\FLSTUDIO\Desktop\byob-master\byob>python setup.py
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
DEBUG:__main__:Error in pip package installer: Command 'where pip' returned non-zero exit status 1
DEBUG:pip._internal.utils.misc:lzma module is not available
DEBUG:pip._internal.vcs:Registered VCS backend: git
DEBUG:pip._internal.vcs:Registered VCS backend: hg
DEBUG:pip._internal.vcs:Registered VCS backend: svn
DEBUG:pip._internal.vcs:Registered VCS backend: bzr
DEBUG:pip._internal.configuration:For variant 'global', will try loading 'C:\ProgramData\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'user', will try loading 'C:\Users\FLSTUDIO\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'user', will try loading 'C:\Users\FLSTUDIO\AppData\Roaming\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'global', will try loading 'C:\ProgramData\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'user', will try loading 'C:\Users\FLSTUDIO\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'user', will try loading 'C:\Users\FLSTUDIO\AppData\Roaming\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'global', will try loading 'C:\ProgramData\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'user', will try loading 'C:\Users\FLSTUDIO\pip\pip.ini'
DEBUG:pip._internal.configuration:For variant 'user', will try loading 'C:\Users\FLSTUDIO\AppData\Roaming\pip\pip.ini'
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-18.1

**Comment by malwaredllc** [comment]
If you don't have pip installed when running `setup.py`, it will automatically install pip for you but you will need to run `setup.py` again to install the Python packages in `requirements.txt`.

So just run it again and it will work now.
