### ISSUE TITLE
Windows executable isn't generating

### ISSUE THREAD

**Issue by JacobWasTaken** [malwaredllc/byob#668]
When I try to generate a windows executable it first says
`/usr/bin/docker
(343 bytes written to output/jacob/src/byob_win_x32_qec.py)
	Compiling executable...`
then
`b'005c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.'
b'005c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."'
b'005c:err:systray:initialize_systray Could not create tray window'`
![image](https://github.com/malwaredllc/byob/assets/102453197/6d0512fc-d163-4e1c-ab60-0b0e6c9676f5)
I installed docker completely correctly, installed all the requirements, and did a fresh install and it gives that error.

**Comment by ETHICALrichPERSON** [comment]
@JacobWasTaken Did you ever figure it out? I'm currently experiencing the exact same issue. Any help is appreciated
