### ISSUE TITLE
Usage readme

### ISSUE THREAD

**Issue by Kif11** [malwaredllc/byob#67]
How about adding some usage info?

**Comment by marxenegls** [comment]
i stumbled on a similar project , or rather a pdf of a java based byob published by the SANS Institute 
[byob-build-botnet-33729.pdf](https://github.com/malwaredllc/byob/files/2544547/byob-build-botnet-33729.pdf) 
hope it can be of some help ..

**Comment by malwaredllc** [comment]
There's some usage information in README.md, and using the `--help` argument when running `client.py` or `server.py`.

However, I will look into adding some usage examples and/or a more detailed walkthrough/demonstration of how to use BYOB.
