### ISSUE TITLE
stager download link not working

### ISSUE THREAD

**Issue by p0syd0n** [malwaredllc/byob#673]
**Describe the bug**
The link that is given in the payload is faulty. For a python payload: I deobfuscated the payload, and got the url that it was downloading:
http://103.84.116.226:1338/stagers/zc8.py
I then tried to visit it on my browser and it did not respond. I nmapped it and saw that only port 53 was open.

**To Reproduce**
visit:
http://103.84.116.226:1338/stagers/zc8.py

**Expected behavior**
the client would connect to the botnet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: kali newest
 - Python version 3.10.9

**Comment by Bortikr23** [comment]
I have this same issue, the link wont work. I dont know how to fix it
