### ISSUE TITLE
mac os run ????

### ISSUE THREAD

**Issue by pullghjunkkk** [malwaredllc/byob#674]
chikkachun@chikdeMBP ~ % git clone https://github.com/malwaredllc/byob.git
Cloning into 'byob'...
remote: Enumerating objects: 6533, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6533 (delta 0), reused 1 (delta 0), pack-reused 6530
Receiving objects: 100% (6533/6533), 38.60 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (2952/2952), done.
chikkachun@chikdeMBP ~ % cd Desktop/byob-master/byob
cd: no such file or directory: Desktop/byob-master/byob
chikkachun@chikdeMBP ~ % cd byob/web-gui
chikkachun@chikdeMBP web-gui % setup.sh
zsh: command not found: setup.sh
chikkachun@chikdeMBP web-gui % python3 run.py
Traceback (most recent call last):
  File "/Users/chikkachun/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/Users/chikkachun/byob/web-gui/buildyourownbotnet/__init__.py", line 8, in <module>
    from flask_login import LoginManager
ModuleNotFoundError: No module named 'flask_login'
chikkachun@chikdeMBP web-gui % python setup.py
zsh: command not found: python
chikkachun@chikdeMBP web-gui % python -m pip install requirements.txt
zsh: command not found: python
chikkachun@chikdeMBP web-gui % python server.py --host YourIp --port YourPort
zsh: command not found: python
chikkachun@chikdeMBP web-gui %

**Comment by bigstinkymanboobs** [comment]
imagine being stupid AND using macos
