### ISSUE TITLE
unable to locate directory containing user-installed packages

### ISSUE THREAD

**Issue by nickonick1** [malwaredllc/byob#675]
hi please help me i am having this problem
![image](https://github.com/malwaredllc/byob/assets/99060505/6daf1292-75c0-49bb-84c3-f375e447005d)

**Comment by Varrsidom** [comment]
same

**Comment by Ashutosh-Bhardwaj-26** [comment]
any solution for it?

**Comment by ppaauuoo** [comment]
https://github.com/malwaredllc/byob/issues/587#issuecomment-1144410181

I did what this comment suggests, and it works.
