### ISSUE TITLE
Can't create Windows exe x32 payload 

### ISSUE THREAD

**Issue by bxzdy** [malwaredllc/byob#677]
I finally made it through startup.sh and now when I want to generate a payload python works normal but when I want to create an executable payload it keeps loading then in the shell there's a b' ' loop.

**Comment by MechanicEnigma8** [comment]
Same.

**Comment by youssefallali** [comment]
This is happening because you haven't installed the docker images install
them
If you have installed docker using the "apt install docker.io -y " command,
it's not gonna work install docker from the main website of docker and it
should work
