### ISSUE TITLE
having problems with run.py

### ISSUE THREAD

**Issue by bcwlkr** [malwaredllc/byob#686]
when running run.py i get the message:

Traceback (most recent call last):
  File "/home/brecken/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/brecken/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/brecken/byob/web-gui/buildyourownbotnet/server.py", line 32, in <module>
    from .models import db
  File "/home/brecken/byob/web-gui/buildyourownbotnet/models.py", line 2, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

Update: I am using Kali Linux and tried using venv and a clean install in venv, that has NOT fixed my issue.

Theory: going through the web-gui folder, I don't a .models to call db from, if anyone knows if this was (or is) a package for Python please tell.

**Comment by DanceMonkey276** [comment]
If you haven't done so yet, you could try installing the requirements:
`pip install -r requirements.txt`
I would reccomend using a virtual environment for this project. You can do so by entering following command:
`python3 -m venv venv`
Then you activate the virtual environment using
`source venv/bin/activate`

This all is for Linux. If you need any more help, feel free to add another comment!

**Comment by DanceMonkey276** [comment]
Are you using Linux?

**Comment by bcwlkr** [comment]
I'm using Kali, I figured out how to use vinv but I still get the error

**Comment by bcwlkr** [comment]
> Are you using Linux?

I'm using Kali, I figured out vinv but when running it I still get the aforementioned error

**Comment by DanceMonkey276** [comment]
Have you tried rerunning the startup.sh script? Worst case, you would have to delete the entire thing and get a new, clean install.

**Comment by ThePuteh** [comment]
> when running run.py i get the message:
> 
> Traceback (most recent call last): File "/home/brecken/byob/web-gui/run.py", line 1, in from buildyourownbotnet import create_app File "/home/brecken/byob/web-gui/buildyourownbotnet/**init**.py", line 16, in from buildyourownbotnet import client, server File "/home/brecken/byob/web-gui/buildyourownbotnet/server.py", line 32, in from .models import db File "/home/brecken/byob/web-gui/buildyourownbotnet/models.py", line 2, in from flask_bcrypt import Bcrypt ModuleNotFoundError: No module named 'flask_bcrypt'
> 
> Update: I am using Kali Linux and tried using venv and a clean install in venv, that has NOT fixed my issue.
> 
> Theory: going through the web-gui folder, I don't a .models to call db from, if anyone knows if this was (or is) a package for Python please tell.

Should use pip to seperate install without requirements.txt of this >>> ModuleNotFoundError: No module named 'flask_bcrypt'

pip that flask_bcrypt only ...
