### ISSUE TITLE
Just doesn't work on python 3.7

### ISSUE THREAD

**Issue by TheBrokenWasp** [malwaredllc/byob#69]
I have tried multiple ways of getting this to work, there is no tutorial on it that I can find so I tried myself, setup.py doesn't work because of errors of this: `logging.basicConfig(level=logging.DEBUG, handler=logging.StreamHandler())` client.py doesn't work simply because of dependencies (I also did pip install -r requierments.txt, it installed some of them but then it got an error and skipped over the rest, also don't force it to use other versions of the dependencies unless the newer versions don't work!!!) and I haven't even gotten to server yet as I assume it is worthless without a client so yeah it would be much appreciated if all of this got fixed, I'm not very good at coding in general but I'll help if I can :)

**Comment by malwaredllc** [comment]
This project was designed for python2; support for python3 is still in development.
