### ISSUE TITLE
No module named 'flask'

### ISSUE THREAD

**Issue by audiofolks** [malwaredllc/byob#713]
is there a solution ??

Traceback (most recent call last):
File "/home/onion/tools/byob/web-gui/run . py", line 1, in <module>
from buildyourownbotnet import create_app
File "/home/onion/tools/byob/web-gui/buildyourownbotnet/___init___.py", line 2,
in <module>
from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by audiofolks** [comment]
note: This error originates from a subprocess, and is likely not a problem wit
h pip.
subprocess-exited-with-error
error:
pip subprocess to install build dependencies
did not run successfully.
exit code: 1
See above for output.

**Comment by audiofolks** [comment]
on my python
versions(3.11.2): flask==2.1.3, numpy==1.24.2, opencv-python==4.8.1.78 and it worked

**Comment by DuckyPolice** [comment]
then import flask: `pip install flask`

**Comment by sdfgbhngfdsdfghjk** [comment]
install flask or do pip install -r requirements.txt
