### ISSUE TITLE
numpy==1.21.2 version not supported

### ISSUE THREAD

**Issue by CSaV720** [malwaredllc/byob#719]
I'm on Kali Linux on Chromebook . when I went to install requirements from pip using "pip install -r requirements.txt. it goes to download the files and says its a support problem with the version (numpy doesnt have stable 1.21.2 only 1.22.0. and the only way i can install is to backdate python to 3.7 when im currently on 3.11 python. ) 

![Screenshot 2024-08-07 6 02 29 PM](https://github.com/user-attachments/assets/60f93099-6422-454f-837c-3c288cf9bcdd)

**Comment by CSaV720** [comment]
prior to this I was installing using a python venv so there was no bottle necks (source venv/bin/activate) and was running as root.

**Comment by HenHen2000** [comment]
In the requirements.txt file remove the "==1.21.2" from the end of numpy.

**Comment by CSaV720** [comment]
> In the requirements.txt file remove the "==1.21.2" from the end of numpy.

I still have the issue even though its already install by regular "pip install numpy"

**Comment by CSaV720** [comment]
> In the requirements.txt file remove the "==1.21.2" from the end of numpy.

but thank ya I'll try it by configuring with nano.
