### ISSUE TITLE
Killing a Client

### ISSUE THREAD

**Issue by XeroShi** [malwaredllc/byob#73]
I was testing client on my computer and not a VM (A mistake on my behalf.) I was wondering why the command "kill" does not work?

`[xeroshi @ /Users/xeroshi/Desktop/byob]>help

        command <arg>                                         description                                
 bg [id]                         background a session (default: the current session)                         
 broadcast <command>             broadcast a task to all active sessions                                     
 clients                         show all clients that have joined the server                                
 debug <code>                    run python code directly on server (debugging MUST be enabled)              
 exit                            quit the server                                                             
 help                            show usage help for server commands                                         
 kill <id>                       end a session                                                               
 options                         show currently configured settings                                          
 query <statement>               query the SQLite database                                                   
 ransom [id]                     encrypt client files & ransom encryption key for a Bitcoin payment          
 results [id]                    display all completed task results for a client (default: all clients)      
 sessions                        show active client sessions                                                 
 set <setting> [option=value]    change the value of a setting                                               
 shell <id>                      interact with a client with a reverse TCP shell through an active session   
 tasks [id]                      display all incomplete tasks for a client (default: all clients)            
 webcam <mode>                   capture image/video from the webcam of a client device                      

[xeroshi @ /Users/xeroshi/Desktop/byob]>kill 1
parent=run , child=session_remove , args={'self': <__main__.C2 instance at 0x101992ea8>, 'session_id': '1'}
[xeroshi @ /Users/xeroshi/Desktop/byob]>
`

**Comment by malwaredllc** [comment]
I am unable to reproduce this issue. I tested the `kill` command on Linux, Windows and macOS, and the session was successfully disconnected in every case.

**Comment by jrmessiah** [comment]
This guy is telling the truth

dont be such an arrogant cunt malwaredllc.

this script it shite. period just like ur attitude

**Comment by malwaredllc** [comment]
@jrmessiah Woahhhh, calm down man. If you are seeing the same issue, can you please provide a screenshot and information about your environment?
