### ISSUE TITLE
TOO BIG EXE FILE

### ISSUE THREAD

**Issue by RrUZi** [malwaredllc/byob#78]
The executable file I compiled is actually 200+MB, how to attach it into a Word document?

**Comment by Fuitad** [comment]
Did you add --compress? You need to have UPX in the same directory as byob.

**Comment by RrUZi** [comment]
When I add UPX(_upx-3.95-win64_) to the folder byob, the generated .exe still has 200MB+. My Python version is _Python 2.7.15 :: Anaconda, Inc._ 
++++++++++++++++++++++++++++++++++++++++++++++++++++++
C:\Users\admin\Desktop\byob>python client.py 127.0.0.1 8000 --compress --freeze


[>] Modules
        Adding modules... -(3 modules added to client)

[>] Imports
        Adding imports...-(27 imports from 3 modules)

[>] Payload
        Compressing payload... - (118,264 bytes reduced to 64,291 bytes (-46.0% smaller)
        Uploading payload... -(hosting payload at: http://127.0.0.1:8001///payloads/wVQ.py)

[>] Stager
        Compressing stager... -(2,193 bytes reduced to 2,151 bytes (-2.0% smaller)
        Uploading stager... -(hosting stager at: http://127.0.0.1:8001///stagers/wVQ.py)

[>] Dropper
        Writing dropper...  (203 bytes written to byob_wVQ.py)
        Compiling executable...
967 INFO: PyInstaller: 3.3.1
967 INFO: Python: 2.7.15
967 INFO: Platform: Windows-7-6.1.7601-SP1
1029 INFO: UPX is available.
1029 INFO: Extending PYTHONPATH with paths
['C:\\Users\\admin\\Desktop', 'C:\\Users\\admin\\Desktop\\byob']
1029 INFO: Will encrypt Python bytecode with key: 0rJFHKgh6WdMAa>e
1029 INFO: Adding dependencies on pyi_crypto.py module
1029 INFO: checking Analysis
1029 INFO: Building Analysis because out00-Analysis.toc is non existent
1029 INFO: Initializing module dependency graph...
1029 INFO: Initializing module graph hooks...
1029 INFO: Analyzing hidden import 'base64'
3697 INFO: Analyzing hidden import 'json'
3900 INFO: Analyzing hidden import 'zlib'
3900 INFO: Analyzing hidden import 'urllib'
4851 INFO: Analyzing hidden import 'uuid'
5335 INFO: Analyzing hidden import 'numpy'
11045 INFO: Processing pre-find module path hook   distutils
14476 INFO: Processing pre-safe import module hook   six.moves
15303 INFO: Processing pre-safe import module hook   _xmlplus
32010 INFO: Analyzing hidden import 'colorama'
32213 INFO: Analyzing hidden import 'requests'
32822 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
39796 INFO: Analyzing hidden import 'Crypto.Cipher._AES'
40045 INFO: running Analysis out00-Analysis.toc
40217 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Users\admin\Anaconda2\python.exe
46815 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_acd19a1fe1da248a
.manifest
46894 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f
.manifest
46956 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
46971 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251.m
anifest
46971 INFO: Searching for file msvcr90.dll
46986 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcr90.dll
47003 INFO: Searching for file msvcp90.dll
47003 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcp90.dll
47019 INFO: Searching for file msvcm90.dll
47019 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcm90.dll
47081 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_acd19a1fe1da248a
.manifest
47096 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f
.manifest
47111 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
47627 INFO: Caching module hooks...
47642 INFO: Analyzing \Users\admin\Desktop\byob\byob_wVQ.py
47674 INFO: Loading module hooks...
47674 INFO: Loading module hook "hook-distutils.py"...
47688 INFO: Loading module hook "hook-sysconfig.py"...
47704 INFO: Loading module hook "hook-xml.py"...
47954 INFO: Loading module hook "hook-cryptography.py"...
49404 INFO: Loading module hook "hook-pycparser.py"...
49858 INFO: Loading module hook "hook-httplib.py"...
49858 INFO: Loading module hook "hook-pydoc.py"...
49872 INFO: Excluding import 'Tkinter'
49888 INFO:   Removing import of Tkinter from module pydoc
49904 INFO: Loading module hook "hook-_tkinter.py"...
50606 INFO: checking Tree
50606 INFO: Building Tree because out00-Tree.toc is non existent
50606 INFO: Building Tree out00-Tree.toc
51042 INFO: checking Tree
51059 INFO: Building Tree because out01-Tree.toc is non existent
51075 INFO: Building Tree out01-Tree.toc
51137 INFO: Loading module hook "hook-pkg_resources.py"...
52026 INFO: Processing pre-safe import module hook   win32com
52775 INFO: Loading module hook "hook-requests.py"...
52805 INFO: Loading module hook "hook-certifi.py"...
52822 INFO: Loading module hook "hook-pywintypes.py"...
53382 INFO: Loading module hook "hook-setuptools.py"...
53460 INFO: Loading module hook "hook-encodings.py"...
56066 INFO: Loading module hook "hook-pytest.py"...
58203 INFO: Loading module hook "hook-numpy.core.py"...
58375 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
58391 INFO: Loading module hook "hook-win32com.py"...
60013 INFO: Loading module hook "hook-pythoncom.py"...
60559 INFO: Loading module hook "hook-xml.dom.domreg.py"...
60668 INFO: Looking for ctypes DLLs
60871 INFO: Analyzing run-time hooks ...
60902 INFO: Including run-time hook 'pyi_rth__tkinter.py'
60934 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
60964 INFO: Including run-time hook 'pyi_rth_pkgres.py'
60980 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
61042 INFO: Looking for dynamic libraries
65348 WARNING: lib not found: msmpi.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_blacs_msmpi_ilp64.dll
66628 WARNING: lib not found: mpich2mpi.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_blacs_mpich2_lp64.dll
72180 WARNING: lib not found: pgc14.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_pgi_thread.dll
72227 WARNING: lib not found: pgf90rtl.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_pgi_thread.dll
72305 WARNING: lib not found: pgf90.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_pgi_thread.dll
72400 WARNING: lib not found: msmpi.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_blacs_msmpi_lp64.dll
72898 WARNING: lib not found: impi.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_blacs_intelmpi_ilp64.dll
102539 WARNING: lib not found: tbb.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_tbb_thread.dll
105019 WARNING: lib not found: impi.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_blacs_intelmpi_lp64.dll
108060 WARNING: lib not found: mpich2mpi.dll dependency of C:\Users\admin\Anaconda2\Library\bin\mkl_blacs_mpich2_ilp64.dll
108154 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_a554a30de6a6e58
2.manifest
108249 INFO: Searching for assembly amd64_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
108263 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146.
manifest
108310 INFO: Searching for file mfc90.dll
108326 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfc90.dll
108326 INFO: Searching for file mfc90u.dll
108326 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfc90u.dll
108326 INFO: Searching for file mfcm90.dll
108326 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfcm90.dll
108326 INFO: Searching for file mfcm90u.dll
108326 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfcm90u.dll
108420 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_a554a30de6a6e58
2.manifest
108420 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
134815 INFO: Looking for eggs
134861 INFO: Using Python library C:\Users\admin\Anaconda2\python27.dll
134878 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161),
 publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022
, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b')]
134956 INFO: Warnings written to C:\Users\admin\Desktop\byob\build\byob_wVQ\warnbyob_wVQ.txt
135267 INFO: Graph cross-reference written to C:\Users\admin\Desktop\byob\build\byob_wVQ\xref-byob_wVQ.html
135984 INFO: checking PYZ
136000 INFO: Building PYZ because out00-PYZ.toc is non existent
136032 INFO: Building PYZ (ZlibArchive) C:\Users\admin\Desktop\byob\build\byob_wVQ\out00-PYZ.pyz
138825 INFO: Building PYZ (ZlibArchive) C:\Users\admin\Desktop\byob\build\byob_wVQ\out00-PYZ.pyz completed successfully.
139198 INFO: checking PKG
139230 INFO: Building PKG because out00-PKG.toc is non existent
139230 INFO: Building PKG (CArchive) out00-PKG.pkg
139448 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
139494 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\python27.dll
139494 INFO: Updating resource type 24 name 2 language 1033
170476 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
170585 INFO: Redirecting Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
170585 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\win32ui.pyd
170601 INFO: Updating resource type 24 name 2 language 1033
173487 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\mfc90.dll
173549 INFO: Updating resource type 24 name 1000 language 1033
174486 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\mfc90u.dll
174782 INFO: Updating resource type 24 name 1000 language 1033
175687 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
175703 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\tcl85.dll
175703 INFO: Updating resource type 24 name 2 language 1033
176685 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\tk85.dll
176733 INFO: Updating resource type 24 name 1 language 1033
176763 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
176763 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\tk85.dll
176763 INFO: Updating resource type 24 name 2 language 1033
176888 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
176888 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\libeay32.dll
176888 INFO: Updating resource type 24 name 2 language 1033
176935 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
176935 INFO: Updating manifest in C:\Users\admin\AppData\Roaming\pyinstaller\bincache00_py27_64bit\ssleay32.dll
176935 INFO: Updating resource type 24 name 2 language 1033
177543 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
272611 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
272968 INFO: Bootloader C:\Users\admin\Anaconda2\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
273016 INFO: checking EXE
273062 INFO: Building EXE because out00-EXE.toc is non existent
273109 INFO: Building EXE from out00-EXE.toc
273171 INFO: Appending archive to EXE C:\Users\admin\Desktop\byob\dist\byob_wVQ.exe
274966 INFO: Building EXE from out00-EXE.toc completed successfully.
(255,511,909 bytes saved to file: /Users/admin/Desktop/byob\dist\byob_wVQ.exe)

++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by malwaredllc** [comment]
Binary executables generated by PyInstaller tend to have large file sizes due to the fact that the Python interpreter is embedded in the executable along with all the packages/modules in the standard library. This is one of the disadvantages of compiling Python scripts into binary executables rather than using a low-level language with fewer dependencies like C.
