### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by vladimirpe00** [malwaredllc/byob#90]
Hello first thanks a lot for such great tool I'm facing an issue on windows 10 when I try to run the executable version "This app can't run on you PC" like it's broken.

I built the client using the command below:

client.py --encrypt --compress --freeze --name bot.exe --pastebin API host port module Keylogger,Spreader,Persistence

client.py --freeze --name bot.exe

with no luck any recommendation? 

thanks

**Comment by malwaredllc** [comment]
1. PyInstaller is used to freeze the Python script into a binary executable. PyInstaller does not support cross-compiling for different platforms, so if you intend to run the executable on a Windows machine, you will need to generate it on a Windows machine.

2. `.exe` will be appended to the filename of the generated executable automatically, you don't need to add it using the `--name` argument (example usage: `--name bot`)
