### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tboss12310** [malwaredllc/byob#91]
py client.py
Traceback (most recent call last):
  File "client.py", line 93, in <module>
    import colorama
ImportError: No module named colorama

**Comment by vladimirpe00** [comment]
#for python 2
pip install colorama 

#for python 3
pip3 install colorama 

when you get such error just install the required dependency using pip command

**Comment by tboss12310** [comment]
thank you it works now

**Comment by malwaredllc** [comment]
Instead of manually installing each dependency with pip, simply run `setup.py` which will install all required packages.
Alternatively, you can run `pip install -r requirements.txt` which will do the same thing.

**Comment by Kkaiirz** [comment]
Hey, I'm having a problem with a slightly different error:
Traceback (most recent call last):
  File "client.py", line 98, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
