### ISSUE TITLE
Error: failed to execute scrupt pyiboot01_bootstrap

### ISSUE THREAD

**Issue by vladimirpe00** [malwaredllc/byob#92]
Hello it's me again thanks a lot for the 1st issue resolving I was able to freeze the code successfully but when I try to execute the compiled .exe I'm getting this error

"failed to execute scrupt pyiboot01_bootstrap"

I already have the MS VC runtime installed any suggestion?

settings used:

Python version 2.7
Windows 10
Pyinstaller

thanks in advance

**Comment by malwaredllc** [comment]
I am unable to reproduce this issue. I have tested BYOB executable binaries on Linux, Windows and macOS and did not encounter this error. However, I do recognize the error and have seen it before when attempting to run executable binaries compiled by PyInstaller, the package BYOB uses to freeze Python scripts.
