### ISSUE TITLE
missing package 'colorama' is required

### ISSUE THREAD

**Issue by monzanifabio** [malwaredllc/byob#97]
After installing the requirements and running the setup.py I run python server.py and it return:
Error: missing package 'colorama' is required despite being installed in the previous step.
I'm running it on OSX 10.14.3 and tried both python 2.7.10 and python 3.7.2.

**Comment by malwaredllc** [comment]
When you ran `pip install -r requirements.txt` was there any error messages about colorama? "Error: missing package 'colorama'" would only appear if it failed to install properly.

**Comment by intrct** [comment]
Any update on this? 

Cannot replicate on my linux systems, and my hackintosh OS isn't available to x-plat verify.

**Comment by s1nceri7y** [comment]
i got the same on Windows using "cmd".
I solved the problem using `pip install colorama`, so i think we should update version numbers in "requirements.txt". (0.4.1 is actual one)
P.s. the same thing happened w/ pyinstaller

**Comment by intrct** [comment]
I believe the issue is because in the Windows instance, the setup file used to leverage the first instance of "pip" it loaded, which may not be the one for the active python environment.

The python -m pip fix should have resolved this as well... has this been tested in a more recent release?
