### ISSUE TITLE
NO Module named payloads 

### ISSUE THREAD

**Issue by niloy007** [malwaredllc/byob#98]
![1](https://user-images.githubusercontent.com/48841246/54850165-910eea00-4d10-11e9-891b-a09ecb9c3e1c.PNG)
This error comes whenever i try this command ... i am noob so any help would be much appreciated..

**Comment by malwaredllc** [comment]
Use `python client.py --help` for usage information about generating a client.

**Comment by niloy007** [comment]
![123123](https://user-images.githubusercontent.com/48841246/54862505-4c15a280-4d66-11e9-84cf-622a30bc2937.PNG)
Same Problem

**Comment by mroneup** [comment]
the same problem happens to me.
this lib is useless now without payloads.py
